In [1]:
import numpy as np
import pandas as pd
import scanpy as sc

In [9]:
adata_path='/usr/src/app/storage/kwang/Kwang1_scvi_integrated.h5ad'
adata = sc.read_h5ad(adata_path)
adata

AnnData object with n_obs × n_vars = 25814 × 33696
    obs: 'Batch', 'Sample', 'n_genes', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_20_genes', 'pct_counts_mt', 'pct_counts_ribo', 'pct_counts_hb', 'Outlier', 'doublet_score', 'predicted_doublet', 'clf_doublet', 'clf_score', 'Doublet', 'leiden', 'majority_voting', 'conf_score', 'low_label', 'low_score', 'ref_droplet_label', 'ref_droplet_score', 'ref_facs_label', 'ref_facs_score', 'predicted', 'transfer_score', '_scvi_batch', '_scvi_labels', 'overcluster', 'low_major', 'predicted_major', 'ref_droplet_major', 'ref_facs_major', 'SingleR_main', 'SingleR_main.pruned', 'SingleR_fine', 'SingleR_fine.pruned', 'SingleR_TabulaMuris', 'SingleR_TabulaMuris.pruned', 'SingleR_main_major', 'SingleR_fine_major', 'SingleR_TabulaMuris_major'
    var: 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection', 'mean', 'std'
    uns: 'Doublet_colors', 'Outlier_colors', 'SingleR_TabulaMuris_colors', 'SingleR_fine_colors', 'SingleR_main_colors', '_scvi_manager_uuid', '_scvi_uuid', 'hvg', 'leiden', 'leiden_colors', 'log1p', 'low_major_colors', 'neighbors', 'overcluster', 'overcluster_colors', 'pca', 'predicted_major_colors', 'rank_genes_groups', 'ref_droplet_label_colors', 'ref_facs_label_colors', 'umap'
    obsm: 'X_pca', 'X_pca_harmony', 'X_scVI', 'X_umap', '_scvi_extra_categorical_covs', '_scvi_extra_continuous_covs'
    varm: 'PCs'
    layers: 'counts', 'scvi_normalized'
    obsp: 'connectivities', 'distances'

In [8]:
adata.obs.predicted

CCACCTTGTTCGTCCT-1-WT_uninfected                                                  alveolar macrophage
ATGGGATAGGTTGCAC-1-WT_uninfected                                                               T cell
GCGTTTCCACAATCCC-1-WT_uninfected                                                          plasma cell
TGAGCTATCACGGACT-1-WT_uninfected                                                               T cell
GCTCAGTAGGGCTATC-1-WT_uninfected                                                  alveolar macrophage
                                                                           ...
ATAGGGTAGGCTGTAC-1-Shh_SPL_KO_infected_(PR8_virus)                                             B cell
TCATGTTCATGATCGG-1-Shh_SPL_KO_infected_(PR8_virus)                                         neutrophil
GTAAGGGTCTATGAGT-1-Shh_SPL_KO_infected_(PR8_virus)                                alveolar macrophage
CACCAATGTCTAAGGA-1-Shh_SPL_KO_infected_(PR8_virus)    ciliated columnar cell of tracheobronchial tree
CTTGTAAGTGAACCGG-1-Shh_SPL_KO_infected_(PR8_virus)                                         neutrophil
Name: predicted, Length: 25814, dtype: category
Categories (28, object): ['B cell', 'CD4-positive, alpha-beta T cell', 'CD8-positive, alpha-beta T cell', 'NK cell', ..., 'regulatory T cell', 'smooth muscle cell of the pulmonary artery', 'type II pneumocyte', 'vein endothelial cell']

In [10]:
adata.obs = adata.obs.rename(columns={'low_label': 'celltypist_label', 'low_score': 'celltypist_score', 'ref_droplet_label': 'celltypist_ref_label', 'ref_droplet_score': 'celltypist_ref_score', 'SingleR_TabulaMuris': 'SingleR_user_ref', 'predicted': 'scANVI_predicted', 'transfer_score': 'scANVI_transfer_score'})

In [11]:
adata.write_h5ad(adata_path)

In [6]:
obsSets = [
    {
        'name': 'SingleR_main',
        'path': 'obs/SingleR_main'
    },
    {
        'name': 'SingleR_fine',
        'path': 'obs/SingleR_fine'
    },
    {
        'name': 'SingleR_user_ref',
        'path': 'obs/SingleR_user_ref'
    },
    {
        'name': 'Cluster',
        'path': 'obs/leiden'
    },
    {
        'name': 'cell_ontology_class',
        'path': 'obs/cell_ontology_class'
    }
]
if len(obsSets) > 0: obsSets = [item['path'].replace("obs/", "") for item in obsSets if item['name'] != "Cluster"]
obsSets
# # Use a list comprehension to extract just the 'path' values
# paths_only = [item['path'].replace("obs/", "") for item in obsSets if item['name'] != "Cluster"]

# print(paths_only)

['SingleR_main', 'SingleR_fine', 'SingleR_user_ref', 'cell_ontology_class']

In [7]:
obsSets = [
    {
        'name': 'SingleR_main',
        'path': 'obs/SingleR_main'
    },
    {
        'name': 'SingleR_fine',
        'path': 'obs/SingleR_fine'
    },
    {
        'name': 'SingleR_user_ref',
        'path': 'obs/SingleR_user_ref'
    },
    {
        'name': 'Cluster',
        'path': 'obs/leiden'
    },
    {
        'name': 'cell_ontology_class',
        'path': 'obs/cell_ontology_class'
    }
]

In [8]:
if not any(item['name'] == 'cell_label' for item in obsSets):
    obsSets.append({
        'name': 'cell_label',
        'path': 'obs/cell_label'
    })

obsSets

[{'name': 'SingleR_main', 'path': 'obs/SingleR_main'},
 {'name': 'SingleR_fine', 'path': 'obs/SingleR_fine'},
 {'name': 'SingleR_user_ref', 'path': 'obs/SingleR_user_ref'},
 {'name': 'Cluster', 'path': 'obs/leiden'},
 {'name': 'cell_ontology_class', 'path': 'obs/cell_ontology_class'},
 {'name': 'cell_label', 'path': 'obs/cell_label'}]

In [7]:
l = [
    {
        "SingleR Annotation": "/usr/src/app/storage/Benchmarks/dropletKidney_1755575402041/QC/annotation/c7cd74fd8ed1f2efbb8557a01c789b29/droplet_Kidney_annotation.h5ad"
    },
    {
        "SingleR Annotation": "/usr/src/app/storage/Benchmarks/dropletKidney_1755575402041/QC/annotation/c7cd74fd8ed1f2efbb8557a01c789b29/droplet_Kidney_annotation.h5ad"
    }
]

seen = set()
unique_data = [d for d in l if d["SingleR Annotation"] not in seen and not seen.add(d["SingleR Annotation"])]

print(unique_data)

[{'SingleR Annotation': '/usr/src/app/storage/Benchmarks/dropletKidney_1755575402041/QC/annotation/c7cd74fd8ed1f2efbb8557a01c789b29/droplet_Kidney_annotation.h5ad'}]

In [6]:
unique_data = [x for x in l if x[SingleR Annotation'] not in seen and not seen.add(x['SingleR Annotation'])]
unique_data

SyntaxError: unterminated string literal (detected at line 1) (2120565796.py, line 1)

In [3]:
adata.obs = adata.obs.rename(columns={'ref_facs_Liver_Seurat_label': 'celltypist_ref_label', 'ref_facs_Liver_Seurat_score': 'celltypist_ref_score'})

In [3]:
adata.obs

,orig.ident,n_counts,n_genes,channel,tissue,subtissue,mouse.sex,mouse.id,percent.ercc,percent.ribo,...,celltypist_ref_label,celltypist_ref_score,SingleR_main,SingleR_fine,SingleR_user_ref,Batch,scANVI_predicted,scANVI_transfer_score,X_scVI_leiden,X_scVI_louvain
10X_P4_5_AAACCTGAGATGCCAG,10X,567.0,188,10X_P4_5,Kidney,,M,3-M-8,0.0,0.244693,...,leukocyte,0.698506,T cells,T cells,leukocyte,Unknown,leukocyte,0.360830,0,7
10X_P4_5_AAACCTGAGTGTCCAT,10X,810.0,251,10X_P4_5,Kidney,,M,3-M-8,0.0,0.081146,...,endothelial cell,0.999023,Endothelial cells,Endothelial cells,endothelial cell,Unknown,endothelial cell,0.978121,1,3
10X_P4_5_AAACCTGCAAGGCTCC,10X,1099.0,278,10X_P4_5,Kidney,,M,3-M-8,0.0,0.110893,...,endothelial cell,0.452945,Cardiomyocytes,Cardiomyocytes,endothelial cell,Unknown,endothelial cell,0.688448,2,8
10X_P4_5_AAACGGGAGCTGAACG,10X,512.0,179,10X_P4_5,Kidney,,M,3-M-8,0.0,0.098671,...,kidney collecting duct epithelial cell,0.933321,Oligodendrocytes,Hepatocytes,kidney collecting duct epithelial cell,Unknown,kidney collecting duct epithelial cell,0.817517,3,6
10X_P4_5_AAACGGGCAGGACCCT,10X,457.0,171,10X_P4_5,Kidney,,M,3-M-8,0.0,0.066408,...,epithelial cell of proximal tubule,0.938000,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,Unknown,epithelial cell of proximal tubule,0.971038,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10X_P7_5_TTTGCGCTCGGTTAAC,10X,1085.0,179,10X_P7_5,Kidney,,F,3-F-57,0.0,0.075776,...,kidney collecting duct epithelial cell,0.999838,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,Unknown,kidney collecting duct epithelial cell,0.970771,3,5
10X_P7_5_TTTGTCAAGGCATTGG,10X,564.0,153,10X_P7_5,Kidney,,F,3-F-57,0.0,0.108880,...,kidney collecting duct epithelial cell,0.999072,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,Unknown,kidney collecting duct epithelial cell,0.966201,6,1
10X_P7_5_TTTGTCACACGCCAGT,10X,469.0,110,10X_P7_5,Kidney,,F,3-F-57,0.0,0.079894,...,kidney collecting duct epithelial cell,0.999030,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,Unknown,kidney collecting duct epithelial cell,0.933710,3,5
10X_P7_5_TTTGTCACATGGATGG,10X,803.0,193,10X_P7_5,Kidney,,F,3-F-57,0.0,0.098761,...,epithelial cell of proximal tubule,0.996598,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,Unknown,epithelial cell of proximal tubule,0.983485,4,4
10X_P7_5_TTTGTCAGTCCGACGT,10X,392.0,117,10X_P7_5,Kidney,,F,3-F-57,0.0,0.102564,...,epithelial cell of proximal tubule,0.999411,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,Unknown,epithelial cell of proximal tubule,0.980891,4,4

In [6]:
adata.obsm['X_umap'].shape

(2559, 2)

In [12]:
adata.obs['cell_label'] = "Unknown"
adata.obs

,Batch,Sample,n_genes,n_genes_by_counts,log1p_n_genes_by_counts,total_counts,log1p_total_counts,pct_counts_in_top_20_genes,pct_counts_mt,pct_counts_ribo,...,SingleR_main,SingleR_main.pruned,SingleR_fine,SingleR_fine.pruned,SingleR_user_ref,SingleR_TabulaMuris.pruned,SingleR_main_major,SingleR_fine_major,SingleR_TabulaMuris_major,cell_label
CCACCTTGTTCGTCCT-1-WT_uninfected,WT uninfected,WT uninfected,8747,8747,9.076580,90975.0,11.418351,9.213520,1.570761,0.0,...,Macrophages,Macrophages,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,Unknown
ATGGGATAGGTTGCAC-1-WT_uninfected,WT uninfected,WT uninfected,7830,7830,8.965845,87949.0,11.384524,12.149086,0.161457,0.0,...,T cells,T cells,T cells,T cells,myeloid cell,myeloid cell,T cells,T cells,natural killer cell,Unknown
GCGTTTCCACAATCCC-1-WT_uninfected,WT uninfected,WT uninfected,5408,5408,8.595820,84527.0,11.344838,68.781573,0.333621,0.0,...,B cells,NaN,B cells,NaN,type II pneumocyte,type II pneumocyte,B cells,B cells,myeloid cell,Unknown
TGAGCTATCACGGACT-1-WT_uninfected,WT uninfected,WT uninfected,7921,7921,8.977399,76575.0,11.246039,10.362390,2.735880,0.0,...,T cells,T cells,T cells,T cells,myeloid cell,myeloid cell,T cells,T cells,natural killer cell,Unknown
GCTCAGTAGGGCTATC-1-WT_uninfected,WT uninfected,WT uninfected,7773,7773,8.958540,69222.0,11.145088,11.931178,1.905464,0.0,...,Macrophages,Macrophages,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,Unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ATAGGGTAGGCTGTAC-1-Shh_SPL_KO_infected_(PR8_virus),Shh SPL KO infected (PR8 virus),Shh SPL KO infected (PR8 virus),224,224,5.416100,362.0,5.894403,37.845304,0.000000,0.0,...,B cells,NaN,B cells,NaN,B cell,NaN,B cells,B cells,B cell,Unknown
TCATGTTCATGATCGG-1-Shh_SPL_KO_infected_(PR8_virus),Shh SPL KO infected (PR8 virus),Shh SPL KO infected (PR8 virus),243,243,5.497168,379.0,5.940171,28.496042,0.000000,0.0,...,Granulocytes,NaN,Granulocytes,NaN,leukocyte,NaN,Granulocytes,Granulocytes,leukocyte,Unknown
GTAAGGGTCTATGAGT-1-Shh_SPL_KO_infected_(PR8_virus),Shh SPL KO infected (PR8 virus),Shh SPL KO infected (PR8 virus),357,357,5.880533,470.0,6.154858,27.659574,0.000000,0.0,...,Macrophages,NaN,Microglia activated,Microglia activated,alveolar macrophage,NaN,Macrophages,Macrophages,alveolar macrophage,Unknown
CACCAATGTCTAAGGA-1-Shh_SPL_KO_infected_(PR8_virus),Shh SPL KO infected (PR8 virus),Shh SPL KO infected (PR8 virus),322,322,5.777652,472.0,6.159095,21.186441,0.000000,0.0,...,Epithelial cells,Epithelial cells,Ependymal,Ependymal,type II pneumocyte,type II pneumocyte,Adipocytes,Adipocytes,type II pneumocyte,Unknown
CTTGTAAGTGAACCGG-1-Shh_SPL_KO_infected_(PR8_virus),Shh SPL KO infected (PR8 virus),Shh SPL KO infected (PR8 virus),233,233,5.455321,470.0,6.154858,40.638298,0.000000,0.0,...,Granulocytes,NaN,Granulocytes,NaN,leukocyte,leukocyte,Granulocytes,Granulocytes,leukocyte,Unknown

In [6]:
adata.obs.columns

Index(['orig.ident', 'n_counts', 'n_genes', 'channel', 'tissue', 'subtissue',
       'mouse.sex', 'mouse.id', 'percent.ercc', 'percent.ribo',
       'cell_ontology_class', 'res.0.5', 'cluster.ids', 'cell_ontology_id',
       'subsetA', 'subsetA_cluster.ids', 'pct_counts_mt', 'pct_counts_rb',
       'pct_counts_hb', 'percent.plat', 'RNA_snn_res.0.5', 'seurat_clusters',
       'doublet_score', 'doublet_class', 'leiden', 'louvain', 'split_idx',
       '_scvi_batch', '_scvi_labels', 'leiden_X_scVI', 'louvain_X_scVI',
       'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts',
       'log1p_total_counts', 'pct_counts_in_top_20_genes', 'total_counts_mt',
       'log1p_total_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo',
       'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb',
       'outlier', 'predicted_doublet', 'clf_doublet', 'clf_score',
       'X_pca_harmony_leiden', 'X_pca_harmony_louvain', 'predicted_labels',
       'over_clustering', 'majority_voting', 'conf_score', 'celltypist_label',
       'celltypist_score', 'celltypist_ref_label', 'celltypist_ref_score'],
      dtype='object')

In [5]:
adata

AnnData object with n_obs × n_vars = 2559 × 1738
    obs: 'orig.ident', 'n_counts', 'n_genes', 'channel', 'tissue', 'subtissue', 'mouse.sex', 'mouse.id', 'percent.ercc', 'percent.ribo', 'cell_ontology_class', 'res.0.5', 'previous_cell_ontology_class', 'cluster.ids', 'cell_ontology_id', 'pct_counts_mt', 'pct_counts_rb', 'pct_counts_hb', 'percent.plat', 'RNA_snn_res.0.5', 'seurat_clusters', 'doublet_score', 'doublet_class', 'leiden', 'louvain', 'split_idx', '_scvi_batch', '_scvi_labels', 'leiden_X_scVI', 'louvain_X_scVI', 'predicted_labels', 'over_clustering', 'majority_voting', 'conf_score', 'celltypist_label', 'celltypist_score', 'celltypist_ref_label', 'celltypist_ref_score', 'SingleR_main', 'SingleR_fine', 'SingleR_user_ref', 'Batch', 'scANVI_predicted', 'scANVI_transfer_score', 'X_scVI_leiden', 'X_scVI_louvain'
    var: 'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'highly_variable', 'n_cells'
    uns: 'X_scVI_leiden', 'X_scVI_louvain', '_scvi_manager_uuid', '_scvi_uuid', 'leiden', 'leiden_X_scVI', 'log1p', 'louvain', 'louvain_X_scVI', 'neighbors', 'over_clustering', 'pca', 'rank_genes_groups'
    obsm: 'X_mde', 'X_pca', 'X_scVI', 'X_tsne', 'X_tsne_3D', 'X_umap', 'X_umap_3D'
    varm: 'PCs'
    layers: 'normalized_X', 'raw_counts', 'scale.data', 'scvi_normalized'
    obsp: 'connectivities', 'distances'

In [6]:
adata.obs.leiden

10X_P4_5_AAACCTGAGATGCCAG     9
10X_P4_5_AAACCTGAGTGTCCAT     4
10X_P4_5_AAACCTGCAAGGCTCC    10
10X_P4_5_AAACGGGAGCTGAACG    11
10X_P4_5_AAACGGGCAGGACCCT     5
                             ..
10X_P7_5_TTTGCGCTCGGTTAAC     6
10X_P7_5_TTTGTCAAGGCATTGG     0
10X_P7_5_TTTGTCACACGCCAGT     6
10X_P7_5_TTTGTCACATGGATGG     2
10X_P7_5_TTTGTCAGTCCGACGT     2
Name: leiden, Length: 2559, dtype: category
Categories (14, object): ['0', '1', '2', '3', ..., '10', '11', '12', '13']

In [28]:
def get_mode_scalar(x):
    m = x.mode()
    return m if not m.empty else None

In [41]:
# labels = adata.obs[['overcluster', 'celltypist_label', 'celltypist_ref_label', 'SingleR_main', 'SingleR_fine', 'SingleR_user_ref', 'scANVI_predicted']].groupby('overcluster').agg(lambda x: x.mode())
# labels = labels.map(lambda x: x if isinstance(x, (pd.Series, np.ndarray, list)) else x)

def first_mode(x):
    m = x.mode()
    return m.iat[0] if len(m) else None

labels = (
    adata.obs[['overcluster', 'celltypist_label', 'celltypist_ref_label',
               'SingleR_main', 'SingleR_fine', 'SingleR_user_ref',
               'scANVI_predicted']]
    .groupby('overcluster')
    .agg(first_mode)
)
scores = adata.obs[['overcluster', 'celltypist_score', 'celltypist_ref_score', 'scANVI_transfer_score']].groupby('overcluster').agg(lambda x: x.mean())

mapping_res = labels.merge(right = scores, left_index=True, right_index=True)

/tmp/ipykernel_813/3182152027.py:12: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby('overcluster')
/tmp/ipykernel_813/3182152027.py:15: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  scores = adata.obs[['overcluster', 'celltypist_score', 'celltypist_ref_score', 'scANVI_transfer_score']].groupby('overcluster').agg(lambda x: x.mean())

In [44]:
labels['majority_vote'] = labels.mode(axis=1).iloc[:, 0].fillna('Unknown')
labels

,celltypist_label,celltypist_ref_label,SingleR_main,SingleR_fine,SingleR_user_ref,scANVI_predicted,majority_vote
overcluster,,,,,,,
0,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,NK cell,NK cell
1,Tem/Trm cytotoxic T cells,"CD8-positive, alpha-beta T cell",T cells,T cells,T cell,"CD8-positive, alpha-beta T cell","CD8-positive, alpha-beta T cell"
2,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,alveolar macrophage
3,Monocytes,non-classical monocyte,Monocytes,Monocytes,non-classical monocyte,non-classical monocyte,Monocytes
4,Naive B cells,B cell,B cells,B cells,B cell,B cell,B cell
5,Monocytes,neutrophil,Granulocytes,Granulocytes,leukocyte,neutrophil,Granulocytes
6,Monocytes,intermediate monocyte,Monocytes,Monocytes,classical monocyte,myeloid dendritic cell,Monocytes
7,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell","CD4-positive, alpha-beta T cell"
8,Naive B cells,B cell,B cells,B cells,B cell,vein endothelial cell,B cell
9,Naive B cells,B cell,B cells,B cells,B cell,B cell,B cell
10,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell","CD4-positive, alpha-beta T cell"
11,Naive B cells,B cell,B cells,B cells,B cell,B cell,B cell
12,Naive B cells,B cell,B cells,B cells,B cell,B cell,B cell
13,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell","CD4-positive, alpha-beta T cell"
14,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,alveolar macrophage
15,Monocytes,B cell,B cells,B cells,B cell,B cell,B cell
16,Tem/Trm cytotoxic T cells,regulatory T cell,T cells,T cells,T cell,regulatory T cell,T cells
17,Regulatory T cells,regulatory T cell,T cells,T cells,T cell,regulatory T cell,T cells
18,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,alveolar macrophage
19,Naive B cells,B cell,B cells,B cells,B cell,B cell,B cell
20,Tem/Trm cytotoxic T cells,mature NK T cell,T cells,T cells,natural killer cell,mature NK T cell,T cells
21,Naive B cells,B cell,B cells,B cells,B cell,B cell,B cell
22,Alveolar macrophages,alveolar macrophage,Macrophages,Monocytes,alveolar macrophage,alveolar macrophage,alveolar macrophage
23,Monocytes,"CD8-positive, alpha-beta T cell",T cells,T cells,T cell,"CD8-positive, alpha-beta T cell","CD8-positive, alpha-beta T cell"
24,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell","CD4-positive, alpha-beta T cell"
25,Tem/Temra cytotoxic T cells,mature NK T cell,T cells,T cells,natural killer cell,mature NK T cell,T cells
26,Tem/Temra cytotoxic T cells,type II pneumocyte,Adipocytes,Adipocytes,type II pneumocyte,type II pneumocyte,type II pneumocyte
27,Naive B cells,B cell,B cells,B cells,B cell,B cell,B cell
28,Monocytes,T cell,T cells,T cells,myeloid cell,T cell,T cell
29,CD16+ NK cells,neutrophil,Granulocytes,Granulocytes,leukocyte,neutrophil,Granulocytes
30,Monocytes,T cell,T cells,T cells,myeloid cell,regulatory T cell,T cells
31,Regulatory T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell","CD4-positive, alpha-beta T cell"
32,Naive B cells,B cell,B cells,B cells,B cell,B cell,B cell
33,Tem/Temra cytotoxic T cells,club cell of bronchiole,Hepatocytes,Ependymal,ciliated columnar cell of tracheobronchial tree,club cell of bronchiole,club cell of bronchiole
34,Monocytes,myeloid dendritic cell,Monocytes,Monocytes,myeloid cell,myeloid dendritic cell,Monocytes
35,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,NK cell,NK cell
36,Monocytes,lung macrophage,Monocytes,Monocytes,classical monocyte,lung macrophage,Monocytes
37,Monocytes,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,alveolar macrophage
38,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,alveolar macrophage
39,Endothelial cells,bronchial smooth muscle cell,Endothelial cells,Endothelial cells,lung endothelial cell,smooth muscle cell of the pulmonary artery,Endothelial cells
40,Monocytes,T cell,T cells,T cells,natural killer cell,T cell,T cell
41,Naive B cells,B cell,B cells,B cells,B cell,B cell,B cell
42,Monocytes,T cell,T cells,T cells,T cell,T cell,T cell
43,Non-classical monocytes,classical monocyte,Monocytes,Monocytes,myeloid cell,myeloid dendritic cell,Monocytes
44,CD16+ NK cells,basophil,Granulocytes,Granulocytes,mast cell,basophil,Granulocytes
45,DC2,dendritic cell,Macrophages,B cells,myeloid cell,dendritic cell,dendritic cell
46,Monocytes,B cell,B cells,B cells,B cell,vein endothelial cell,B cell
47,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,mature NK T cell,NK cells
48,Monocytes,plasma cell,B cells,B cells,myeloid cell,plasma cell,B cells
49,Double-positive thymocytes,T cell,T cells,T cells,T cell,plasma cell,T cell

In [47]:
unique_labels = pd.unique(labels.values.ravel()).tolist()
unique_labels

['CD16- NK cells',
 'NK cell',
 'NK cells',
 'natural killer cell',
 'Tem/Trm cytotoxic T cells',
 'CD8-positive, alpha-beta T cell',
 'T cells',
 'T cell',
 'Alveolar macrophages',
 'alveolar macrophage',
 'Macrophages',
 'Monocytes',
 'non-classical monocyte',
 'Naive B cells',
 'B cell',
 'B cells',
 'neutrophil',
 'Granulocytes',
 'leukocyte',
 'intermediate monocyte',
 'classical monocyte',
 'myeloid dendritic cell',
 'Tcm/Naive helper T cells',
 'CD4-positive, alpha-beta T cell',
 'vein endothelial cell',
 'regulatory T cell',
 'Regulatory T cells',
 'mature NK T cell',
 'Tem/Temra cytotoxic T cells',
 'type II pneumocyte',
 'Adipocytes',
 'myeloid cell',
 'CD16+ NK cells',
 'club cell of bronchiole',
 'Hepatocytes',
 'Ependymal',
 'ciliated columnar cell of tracheobronchial tree',
 'lung macrophage',
 'Endothelial cells',
 'bronchial smooth muscle cell',
 'lung endothelial cell',
 'smooth muscle cell of the pulmonary artery',
 'Non-classical monocytes',
 'basophil',
 'mast cell',
 'DC2',
 'dendritic cell',
 'plasma cell',
 'Double-positive thymocytes']

In [42]:
mapping_res

,celltypist_label,celltypist_ref_label,SingleR_main,SingleR_fine,SingleR_user_ref,scANVI_predicted,celltypist_score,celltypist_ref_score,scANVI_transfer_score
overcluster,,,,,,,,,
0,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,NK cell,0.895466,0.999999,0.996787
1,Tem/Trm cytotoxic T cells,"CD8-positive, alpha-beta T cell",T cells,T cells,T cell,"CD8-positive, alpha-beta T cell",0.630908,0.738386,0.979727
2,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.213961,1.000000,0.999943
3,Monocytes,non-classical monocyte,Monocytes,Monocytes,non-classical monocyte,non-classical monocyte,0.782497,0.993336,0.988801
4,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.732274,1.000000,0.999095
5,Monocytes,neutrophil,Granulocytes,Granulocytes,leukocyte,neutrophil,0.920463,1.000000,0.999711
6,Monocytes,intermediate monocyte,Monocytes,Monocytes,classical monocyte,myeloid dendritic cell,0.726763,0.614637,0.986836
7,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.670952,0.937419,0.999440
8,Naive B cells,B cell,B cells,B cells,B cell,vein endothelial cell,0.486414,1.000000,0.949152
9,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.688623,1.000000,0.997401
10,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.657648,0.926794,0.998895
11,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.669002,1.000000,0.999565
12,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.653389,1.000000,0.997091
13,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.679175,0.875766,0.997039
14,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.211475,1.000000,0.999754
15,Monocytes,B cell,B cells,B cells,B cell,B cell,0.512745,0.998938,0.947005
16,Tem/Trm cytotoxic T cells,regulatory T cell,T cells,T cells,T cell,regulatory T cell,0.637648,0.980990,0.964668
17,Regulatory T cells,regulatory T cell,T cells,T cells,T cell,regulatory T cell,0.586515,0.889353,0.948677
18,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.180494,1.000000,0.996430
19,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.363484,0.999575,0.997496
20,Tem/Trm cytotoxic T cells,mature NK T cell,T cells,T cells,natural killer cell,mature NK T cell,0.953363,0.975796,0.990966
21,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.626014,1.000000,0.997107
22,Alveolar macrophages,alveolar macrophage,Macrophages,Monocytes,alveolar macrophage,alveolar macrophage,0.681230,0.992620,0.989131
23,Monocytes,"CD8-positive, alpha-beta T cell",T cells,T cells,T cell,"CD8-positive, alpha-beta T cell",0.438008,0.777511,0.889137
24,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.763462,0.761303,0.987557
25,Tem/Temra cytotoxic T cells,mature NK T cell,T cells,T cells,natural killer cell,mature NK T cell,0.832806,0.989733,0.973082
26,Tem/Temra cytotoxic T cells,type II pneumocyte,Adipocytes,Adipocytes,type II pneumocyte,type II pneumocyte,0.122436,0.971322,0.978777
27,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.665669,0.999985,0.997494
28,Monocytes,T cell,T cells,T cells,myeloid cell,T cell,0.498110,0.999693,0.985322
29,CD16+ NK cells,neutrophil,Granulocytes,Granulocytes,leukocyte,neutrophil,0.543650,0.973990,0.948912
30,Monocytes,T cell,T cells,T cells,myeloid cell,regulatory T cell,0.039679,0.938878,0.935878
31,Regulatory T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.503067,0.814105,0.940865
32,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.808726,1.000000,0.951031
33,Tem/Temra cytotoxic T cells,club cell of bronchiole,Hepatocytes,Ependymal,ciliated columnar cell of tracheobronchial tree,club cell of bronchiole,0.506561,0.766281,0.986854
34,Monocytes,myeloid dendritic cell,Monocytes,Monocytes,myeloid cell,myeloid dendritic cell,0.243165,0.976505,0.976010
35,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,NK cell,0.688880,0.768050,0.940423
36,Monocytes,lung macrophage,Monocytes,Monocytes,classical monocyte,lung macrophage,0.413371,0.829754,0.973225
37,Monocytes,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.204667,1.000000,0.991495
38,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.087976,0.993620,0.997387
39,Endothelial cells,bronchial smooth muscle cell,Endothelial cells,Endothelial cells,lung endothelial cell,smooth muscle cell of the pulmonary artery,0.479676,0.986211,0.952282
40,Monocytes,T cell,T cells,T cells,natural killer cell,T cell,0.805031,0.990675,0.978623
41,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.651780,1.000000,0.995593
42,Monocytes,T cell,T cells,T cells,T cell,T cell,0.536491,0.828359,0.916143
43,Non-classical monocytes,classical monocyte,Monocytes,Monocytes,myeloid cell,myeloid dendritic cell,0.774565,0.930673,0.917074
44,CD16+ NK cells,basophil,Granulocytes,Granulocytes,mast cell,basophil,0.674560,1.000000,0.973069
45,DC2,dendritic cell,Macrophages,B cells,myeloid cell,dendritic cell,0.064725,0.973631,1.000000
46,Monocytes,B cell,B cells,B cells,B cell,vein endothelial cell,0.242576,1.000000,0.999876
47,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,mature NK T cell,0.799856,0.995141,0.895356
48,Monocytes,plasma cell,B cells,B cells,myeloid cell,plasma cell,0.125643,0.979157,0.999998
49,Double-positive thymocytes,T cell,T cells,T cells,T cell,plasma cell,0.622099,0.696061,0.909164

In [43]:
mapping_res['SingleR_fine'][45]

/tmp/ipykernel_813/3931336037.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  mapping_res['SingleR_fine'][45]

'B cells'

In [34]:
labels

,celltypist_label,celltypist_ref_label,SingleR_main,SingleR_fine,SingleR_user_ref,scANVI_predicted
overcluster,,,,,,
0,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,NK cell
1,Tem/Trm cytotoxic T cells,"CD8-positive, alpha-beta T cell",T cells,T cells,T cell,"CD8-positive, alpha-beta T cell"
2,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage
3,Monocytes,non-classical monocyte,Monocytes,Monocytes,non-classical monocyte,non-classical monocyte
4,Naive B cells,B cell,B cells,B cells,B cell,B cell
5,Monocytes,neutrophil,Granulocytes,Granulocytes,leukocyte,neutrophil
6,Monocytes,intermediate monocyte,Monocytes,Monocytes,classical monocyte,myeloid dendritic cell
7,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell"
8,Naive B cells,B cell,B cells,B cells,B cell,vein endothelial cell
9,Naive B cells,B cell,B cells,B cells,B cell,B cell
10,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell"
11,Naive B cells,B cell,B cells,B cells,B cell,B cell
12,Naive B cells,B cell,B cells,B cells,B cell,B cell
13,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell"
14,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage
15,Monocytes,B cell,B cells,B cells,B cell,B cell
16,Tem/Trm cytotoxic T cells,regulatory T cell,T cells,T cells,T cell,regulatory T cell
17,Regulatory T cells,regulatory T cell,T cells,T cells,T cell,regulatory T cell
18,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage
19,Naive B cells,B cell,B cells,B cells,B cell,B cell
20,Tem/Trm cytotoxic T cells,mature NK T cell,T cells,T cells,natural killer cell,mature NK T cell
21,Naive B cells,B cell,B cells,B cells,B cell,B cell
22,Alveolar macrophages,alveolar macrophage,Macrophages,Monocytes,alveolar macrophage,alveolar macrophage
23,Monocytes,"CD8-positive, alpha-beta T cell",T cells,T cells,T cell,"CD8-positive, alpha-beta T cell"
24,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell"
25,Tem/Temra cytotoxic T cells,mature NK T cell,T cells,T cells,natural killer cell,mature NK T cell
26,Tem/Temra cytotoxic T cells,type II pneumocyte,Adipocytes,Adipocytes,type II pneumocyte,type II pneumocyte
27,Naive B cells,B cell,B cells,B cells,B cell,B cell
28,Monocytes,T cell,T cells,T cells,myeloid cell,T cell
29,CD16+ NK cells,neutrophil,Granulocytes,Granulocytes,leukocyte,neutrophil
30,Monocytes,T cell,T cells,T cells,myeloid cell,regulatory T cell
31,Regulatory T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell"
32,Naive B cells,B cell,B cells,B cells,B cell,B cell
33,Tem/Temra cytotoxic T cells,club cell of bronchiole,Hepatocytes,Ependymal,ciliated columnar cell of tracheobronchial tree,club cell of bronchiole
34,Monocytes,myeloid dendritic cell,Monocytes,Monocytes,myeloid cell,myeloid dendritic cell
35,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,NK cell
36,Monocytes,lung macrophage,Monocytes,Monocytes,classical monocyte,lung macrophage
37,Monocytes,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage
38,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage
39,Endothelial cells,bronchial smooth muscle cell,Endothelial cells,Endothelial cells,lung endothelial cell,smooth muscle cell of the pulmonary artery
40,Monocytes,T cell,T cells,T cells,natural killer cell,T cell
41,Naive B cells,B cell,B cells,B cells,B cell,B cell
42,Monocytes,T cell,T cells,T cells,T cell,T cell
43,Non-classical monocytes,classical monocyte,Monocytes,Monocytes,myeloid cell,myeloid dendritic cell
44,CD16+ NK cells,basophil,Granulocytes,Granulocytes,mast cell,basophil
45,DC2,dendritic cell,Macrophages,"['B cells', 'Dendritic cells'] Categories (23,...",myeloid cell,dendritic cell
46,Monocytes,B cell,B cells,B cells,B cell,vein endothelial cell
47,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,mature NK T cell
48,Monocytes,plasma cell,B cells,B cells,myeloid cell,plasma cell
49,Double-positive thymocytes,T cell,T cells,T cells,T cell,plasma cell

In [35]:
mapping_res

,celltypist_label,celltypist_ref_label,SingleR_main,SingleR_fine,SingleR_user_ref,scANVI_predicted,celltypist_score,celltypist_ref_score,scANVI_transfer_score
overcluster,,,,,,,,,
0,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,NK cell,0.895466,0.999999,0.996787
1,Tem/Trm cytotoxic T cells,"CD8-positive, alpha-beta T cell",T cells,T cells,T cell,"CD8-positive, alpha-beta T cell",0.630908,0.738386,0.979727
2,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.213961,1.000000,0.999943
3,Monocytes,non-classical monocyte,Monocytes,Monocytes,non-classical monocyte,non-classical monocyte,0.782497,0.993336,0.988801
4,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.732274,1.000000,0.999095
5,Monocytes,neutrophil,Granulocytes,Granulocytes,leukocyte,neutrophil,0.920463,1.000000,0.999711
6,Monocytes,intermediate monocyte,Monocytes,Monocytes,classical monocyte,myeloid dendritic cell,0.726763,0.614637,0.986836
7,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.670952,0.937419,0.999440
8,Naive B cells,B cell,B cells,B cells,B cell,vein endothelial cell,0.486414,1.000000,0.949152
9,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.688623,1.000000,0.997401
10,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.657648,0.926794,0.998895
11,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.669002,1.000000,0.999565
12,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.653389,1.000000,0.997091
13,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.679175,0.875766,0.997039
14,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.211475,1.000000,0.999754
15,Monocytes,B cell,B cells,B cells,B cell,B cell,0.512745,0.998938,0.947005
16,Tem/Trm cytotoxic T cells,regulatory T cell,T cells,T cells,T cell,regulatory T cell,0.637648,0.980990,0.964668
17,Regulatory T cells,regulatory T cell,T cells,T cells,T cell,regulatory T cell,0.586515,0.889353,0.948677
18,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.180494,1.000000,0.996430
19,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.363484,0.999575,0.997496
20,Tem/Trm cytotoxic T cells,mature NK T cell,T cells,T cells,natural killer cell,mature NK T cell,0.953363,0.975796,0.990966
21,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.626014,1.000000,0.997107
22,Alveolar macrophages,alveolar macrophage,Macrophages,Monocytes,alveolar macrophage,alveolar macrophage,0.681230,0.992620,0.989131
23,Monocytes,"CD8-positive, alpha-beta T cell",T cells,T cells,T cell,"CD8-positive, alpha-beta T cell",0.438008,0.777511,0.889137
24,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.763462,0.761303,0.987557
25,Tem/Temra cytotoxic T cells,mature NK T cell,T cells,T cells,natural killer cell,mature NK T cell,0.832806,0.989733,0.973082
26,Tem/Temra cytotoxic T cells,type II pneumocyte,Adipocytes,Adipocytes,type II pneumocyte,type II pneumocyte,0.122436,0.971322,0.978777
27,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.665669,0.999985,0.997494
28,Monocytes,T cell,T cells,T cells,myeloid cell,T cell,0.498110,0.999693,0.985322
29,CD16+ NK cells,neutrophil,Granulocytes,Granulocytes,leukocyte,neutrophil,0.543650,0.973990,0.948912
30,Monocytes,T cell,T cells,T cells,myeloid cell,regulatory T cell,0.039679,0.938878,0.935878
31,Regulatory T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.503067,0.814105,0.940865
32,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.808726,1.000000,0.951031
33,Tem/Temra cytotoxic T cells,club cell of bronchiole,Hepatocytes,Ependymal,ciliated columnar cell of tracheobronchial tree,club cell of bronchiole,0.506561,0.766281,0.986854
34,Monocytes,myeloid dendritic cell,Monocytes,Monocytes,myeloid cell,myeloid dendritic cell,0.243165,0.976505,0.976010
35,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,NK cell,0.688880,0.768050,0.940423
36,Monocytes,lung macrophage,Monocytes,Monocytes,classical monocyte,lung macrophage,0.413371,0.829754,0.973225
37,Monocytes,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.204667,1.000000,0.991495
38,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.087976,0.993620,0.997387
39,Endothelial cells,bronchial smooth muscle cell,Endothelial cells,Endothelial cells,lung endothelial cell,smooth muscle cell of the pulmonary artery,0.479676,0.986211,0.952282
40,Monocytes,T cell,T cells,T cells,natural killer cell,T cell,0.805031,0.990675,0.978623
41,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.651780,1.000000,0.995593
42,Monocytes,T cell,T cells,T cells,T cell,T cell,0.536491,0.828359,0.916143
43,Non-classical monocytes,classical monocyte,Monocytes,Monocytes,myeloid cell,myeloid dendritic cell,0.774565,0.930673,0.917074
44,CD16+ NK cells,basophil,Granulocytes,Granulocytes,mast cell,basophil,0.674560,1.000000,0.973069
45,DC2,dendritic cell,Macrophages,"['B cells', 'Dendritic cells'] Categories (23,...",myeloid cell,dendritic cell,0.064725,0.973631,1.000000
46,Monocytes,B cell,B cells,B cells,B cell,vein endothelial cell,0.242576,1.000000,0.999876
47,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,mature NK T cell,0.799856,0.995141,0.895356
48,Monocytes,plasma cell,B cells,B cells,myeloid cell,plasma cell,0.125643,0.979157,0.999998
49,Double-positive thymocytes,T cell,T cells,T cells,T cell,plasma cell,0.622099,0.696061,0.909164

In [39]:
import pandas as pd
import numpy as np

def keep_first_element(x):
    """Return first element if x is array-like; otherwise return x."""
    
    # Handle pandas categorical
    if isinstance(x, pd.Categorical):
        return x[0] if len(x) > 0 else None

    # Handle list / tuple / numpy array
    if isinstance(x, (list, tuple, np.ndarray)):
        return x[0] if len(x) > 0 else None

    # Handle pandas Series
    if isinstance(x, pd.Series):
        return x.iloc[0] if len(x) > 0 else None

    return x


def flatten_dataframe(df):
    return df.map(keep_first_element)

df_clean = flatten_dataframe(mapping_res)
df_clean

,celltypist_label,celltypist_ref_label,SingleR_main,SingleR_fine,SingleR_user_ref,scANVI_predicted,celltypist_score,celltypist_ref_score,scANVI_transfer_score
overcluster,,,,,,,,,
0,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,NK cell,0.895466,0.999999,0.996787
1,Tem/Trm cytotoxic T cells,"CD8-positive, alpha-beta T cell",T cells,T cells,T cell,"CD8-positive, alpha-beta T cell",0.630908,0.738386,0.979727
2,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.213961,1.000000,0.999943
3,Monocytes,non-classical monocyte,Monocytes,Monocytes,non-classical monocyte,non-classical monocyte,0.782497,0.993336,0.988801
4,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.732274,1.000000,0.999095
5,Monocytes,neutrophil,Granulocytes,Granulocytes,leukocyte,neutrophil,0.920463,1.000000,0.999711
6,Monocytes,intermediate monocyte,Monocytes,Monocytes,classical monocyte,myeloid dendritic cell,0.726763,0.614637,0.986836
7,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.670952,0.937419,0.999440
8,Naive B cells,B cell,B cells,B cells,B cell,vein endothelial cell,0.486414,1.000000,0.949152
9,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.688623,1.000000,0.997401
10,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.657648,0.926794,0.998895
11,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.669002,1.000000,0.999565
12,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.653389,1.000000,0.997091
13,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.679175,0.875766,0.997039
14,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.211475,1.000000,0.999754
15,Monocytes,B cell,B cells,B cells,B cell,B cell,0.512745,0.998938,0.947005
16,Tem/Trm cytotoxic T cells,regulatory T cell,T cells,T cells,T cell,regulatory T cell,0.637648,0.980990,0.964668
17,Regulatory T cells,regulatory T cell,T cells,T cells,T cell,regulatory T cell,0.586515,0.889353,0.948677
18,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.180494,1.000000,0.996430
19,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.363484,0.999575,0.997496
20,Tem/Trm cytotoxic T cells,mature NK T cell,T cells,T cells,natural killer cell,mature NK T cell,0.953363,0.975796,0.990966
21,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.626014,1.000000,0.997107
22,Alveolar macrophages,alveolar macrophage,Macrophages,Monocytes,alveolar macrophage,alveolar macrophage,0.681230,0.992620,0.989131
23,Monocytes,"CD8-positive, alpha-beta T cell",T cells,T cells,T cell,"CD8-positive, alpha-beta T cell",0.438008,0.777511,0.889137
24,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.763462,0.761303,0.987557
25,Tem/Temra cytotoxic T cells,mature NK T cell,T cells,T cells,natural killer cell,mature NK T cell,0.832806,0.989733,0.973082
26,Tem/Temra cytotoxic T cells,type II pneumocyte,Adipocytes,Adipocytes,type II pneumocyte,type II pneumocyte,0.122436,0.971322,0.978777
27,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.665669,0.999985,0.997494
28,Monocytes,T cell,T cells,T cells,myeloid cell,T cell,0.498110,0.999693,0.985322
29,CD16+ NK cells,neutrophil,Granulocytes,Granulocytes,leukocyte,neutrophil,0.543650,0.973990,0.948912
30,Monocytes,T cell,T cells,T cells,myeloid cell,regulatory T cell,0.039679,0.938878,0.935878
31,Regulatory T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.503067,0.814105,0.940865
32,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.808726,1.000000,0.951031
33,Tem/Temra cytotoxic T cells,club cell of bronchiole,Hepatocytes,Ependymal,ciliated columnar cell of tracheobronchial tree,club cell of bronchiole,0.506561,0.766281,0.986854
34,Monocytes,myeloid dendritic cell,Monocytes,Monocytes,myeloid cell,myeloid dendritic cell,0.243165,0.976505,0.976010
35,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,NK cell,0.688880,0.768050,0.940423
36,Monocytes,lung macrophage,Monocytes,Monocytes,classical monocyte,lung macrophage,0.413371,0.829754,0.973225
37,Monocytes,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.204667,1.000000,0.991495
38,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.087976,0.993620,0.997387
39,Endothelial cells,bronchial smooth muscle cell,Endothelial cells,Endothelial cells,lung endothelial cell,smooth muscle cell of the pulmonary artery,0.479676,0.986211,0.952282
40,Monocytes,T cell,T cells,T cells,natural killer cell,T cell,0.805031,0.990675,0.978623
41,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.651780,1.000000,0.995593
42,Monocytes,T cell,T cells,T cells,T cell,T cell,0.536491,0.828359,0.916143
43,Non-classical monocytes,classical monocyte,Monocytes,Monocytes,myeloid cell,myeloid dendritic cell,0.774565,0.930673,0.917074
44,CD16+ NK cells,basophil,Granulocytes,Granulocytes,mast cell,basophil,0.674560,1.000000,0.973069
45,DC2,dendritic cell,Macrophages,B cells,myeloid cell,dendritic cell,0.064725,0.973631,1.000000
46,Monocytes,B cell,B cells,B cells,B cell,vein endothelial cell,0.242576,1.000000,0.999876
47,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,mature NK T cell,0.799856,0.995141,0.895356
48,Monocytes,plasma cell,B cells,B cells,myeloid cell,plasma cell,0.125643,0.979157,0.999998
49,Double-positive thymocytes,T cell,T cells,T cells,T cell,plasma cell,0.622099,0.696061,0.909164

In [40]:
df_clean['SingleR_fine'][45]

/tmp/ipykernel_813/3836182033.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_clean['SingleR_fine'][45]

'B cells'

In [17]:
def extract_first(val):
    # Check if value is a list, numpy array, or pandas Series
    if isinstance(val, (list, np.ndarray, pd.Series,)) and len(val) > 0:
        return val[0] # Return the first element
    return val

# Apply the function to every cell in the DataFrame
# Use .map() for Pandas 2.1.0+; use .applymap() for older versions
df_cleaned = mapping_res.applymap(extract_first)

df_cleaned

/tmp/ipykernel_813/1790068720.py:9: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_cleaned = mapping_res.applymap(extract_first)

,celltypist_label,celltypist_ref_label,SingleR_main,SingleR_fine,SingleR_user_ref,scANVI_predicted,celltypist_score,celltypist_ref_score,scANVI_transfer_score
overcluster,,,,,,,,,
0,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,NK cell,0.895466,0.999999,0.996787
1,Tem/Trm cytotoxic T cells,"CD8-positive, alpha-beta T cell",T cells,T cells,T cell,"CD8-positive, alpha-beta T cell",0.630908,0.738386,0.979727
2,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.213961,1.000000,0.999943
3,Monocytes,non-classical monocyte,Monocytes,Monocytes,non-classical monocyte,non-classical monocyte,0.782497,0.993336,0.988801
4,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.732274,1.000000,0.999095
5,Monocytes,neutrophil,Granulocytes,Granulocytes,leukocyte,neutrophil,0.920463,1.000000,0.999711
6,Monocytes,intermediate monocyte,Monocytes,Monocytes,classical monocyte,myeloid dendritic cell,0.726763,0.614637,0.986836
7,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.670952,0.937419,0.999440
8,Naive B cells,B cell,B cells,B cells,B cell,vein endothelial cell,0.486414,1.000000,0.949152
9,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.688623,1.000000,0.997401
10,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.657648,0.926794,0.998895
11,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.669002,1.000000,0.999565
12,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.653389,1.000000,0.997091
13,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.679175,0.875766,0.997039
14,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.211475,1.000000,0.999754
15,Monocytes,B cell,B cells,B cells,B cell,B cell,0.512745,0.998938,0.947005
16,Tem/Trm cytotoxic T cells,regulatory T cell,T cells,T cells,T cell,regulatory T cell,0.637648,0.980990,0.964668
17,Regulatory T cells,regulatory T cell,T cells,T cells,T cell,regulatory T cell,0.586515,0.889353,0.948677
18,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.180494,1.000000,0.996430
19,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.363484,0.999575,0.997496
20,Tem/Trm cytotoxic T cells,mature NK T cell,T cells,T cells,natural killer cell,mature NK T cell,0.953363,0.975796,0.990966
21,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.626014,1.000000,0.997107
22,Alveolar macrophages,alveolar macrophage,Macrophages,Monocytes,alveolar macrophage,alveolar macrophage,0.681230,0.992620,0.989131
23,Monocytes,"CD8-positive, alpha-beta T cell",T cells,T cells,T cell,"CD8-positive, alpha-beta T cell",0.438008,0.777511,0.889137
24,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.763462,0.761303,0.987557
25,Tem/Temra cytotoxic T cells,mature NK T cell,T cells,T cells,natural killer cell,mature NK T cell,0.832806,0.989733,0.973082
26,Tem/Temra cytotoxic T cells,type II pneumocyte,Adipocytes,Adipocytes,type II pneumocyte,type II pneumocyte,0.122436,0.971322,0.978777
27,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.665669,0.999985,0.997494
28,Monocytes,T cell,T cells,T cells,myeloid cell,T cell,0.498110,0.999693,0.985322
29,CD16+ NK cells,neutrophil,Granulocytes,Granulocytes,leukocyte,neutrophil,0.543650,0.973990,0.948912
30,Monocytes,T cell,T cells,T cells,myeloid cell,regulatory T cell,0.039679,0.938878,0.935878
31,Regulatory T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.503067,0.814105,0.940865
32,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.808726,1.000000,0.951031
33,Tem/Temra cytotoxic T cells,club cell of bronchiole,Hepatocytes,Ependymal,ciliated columnar cell of tracheobronchial tree,club cell of bronchiole,0.506561,0.766281,0.986854
34,Monocytes,myeloid dendritic cell,Monocytes,Monocytes,myeloid cell,myeloid dendritic cell,0.243165,0.976505,0.976010
35,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,NK cell,0.688880,0.768050,0.940423
36,Monocytes,lung macrophage,Monocytes,Monocytes,classical monocyte,lung macrophage,0.413371,0.829754,0.973225
37,Monocytes,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.204667,1.000000,0.991495
38,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.087976,0.993620,0.997387
39,Endothelial cells,bronchial smooth muscle cell,Endothelial cells,Endothelial cells,lung endothelial cell,smooth muscle cell of the pulmonary artery,0.479676,0.986211,0.952282
40,Monocytes,T cell,T cells,T cells,natural killer cell,T cell,0.805031,0.990675,0.978623
41,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.651780,1.000000,0.995593
42,Monocytes,T cell,T cells,T cells,T cell,T cell,0.536491,0.828359,0.916143
43,Non-classical monocytes,classical monocyte,Monocytes,Monocytes,myeloid cell,myeloid dendritic cell,0.774565,0.930673,0.917074
44,CD16+ NK cells,basophil,Granulocytes,Granulocytes,mast cell,basophil,0.674560,1.000000,0.973069
45,DC2,dendritic cell,Macrophages,"['B cells', 'Dendritic cells'] Categories (23,...",myeloid cell,dendritic cell,0.064725,0.973631,1.000000
46,Monocytes,B cell,B cells,B cells,B cell,vein endothelial cell,0.242576,1.000000,0.999876
47,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,mature NK T cell,0.799856,0.995141,0.895356
48,Monocytes,plasma cell,B cells,B cells,myeloid cell,plasma cell,0.125643,0.979157,0.999998
49,Double-positive thymocytes,T cell,T cells,T cells,T cell,plasma cell,0.622099,0.696061,0.909164

In [18]:
# 2. Specifically check and update Categorical columns if their categories are arrays
for col in df_cleaned.select_dtypes(include=['category']):
    # Categories are updated directly to ensure the dtype remains 'category'
    new_categories = [extract_first(cat) for cat in df_cleaned[col].cat.categories]
    df_cleaned[col] = df_cleaned[col].cat.rename_categories(new_categories)
df_cleaned

,celltypist_label,celltypist_ref_label,SingleR_main,SingleR_fine,SingleR_user_ref,scANVI_predicted,celltypist_score,celltypist_ref_score,scANVI_transfer_score
overcluster,,,,,,,,,
0,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,NK cell,0.895466,0.999999,0.996787
1,Tem/Trm cytotoxic T cells,"CD8-positive, alpha-beta T cell",T cells,T cells,T cell,"CD8-positive, alpha-beta T cell",0.630908,0.738386,0.979727
2,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.213961,1.000000,0.999943
3,Monocytes,non-classical monocyte,Monocytes,Monocytes,non-classical monocyte,non-classical monocyte,0.782497,0.993336,0.988801
4,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.732274,1.000000,0.999095
5,Monocytes,neutrophil,Granulocytes,Granulocytes,leukocyte,neutrophil,0.920463,1.000000,0.999711
6,Monocytes,intermediate monocyte,Monocytes,Monocytes,classical monocyte,myeloid dendritic cell,0.726763,0.614637,0.986836
7,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.670952,0.937419,0.999440
8,Naive B cells,B cell,B cells,B cells,B cell,vein endothelial cell,0.486414,1.000000,0.949152
9,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.688623,1.000000,0.997401
10,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.657648,0.926794,0.998895
11,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.669002,1.000000,0.999565
12,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.653389,1.000000,0.997091
13,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.679175,0.875766,0.997039
14,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.211475,1.000000,0.999754
15,Monocytes,B cell,B cells,B cells,B cell,B cell,0.512745,0.998938,0.947005
16,Tem/Trm cytotoxic T cells,regulatory T cell,T cells,T cells,T cell,regulatory T cell,0.637648,0.980990,0.964668
17,Regulatory T cells,regulatory T cell,T cells,T cells,T cell,regulatory T cell,0.586515,0.889353,0.948677
18,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.180494,1.000000,0.996430
19,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.363484,0.999575,0.997496
20,Tem/Trm cytotoxic T cells,mature NK T cell,T cells,T cells,natural killer cell,mature NK T cell,0.953363,0.975796,0.990966
21,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.626014,1.000000,0.997107
22,Alveolar macrophages,alveolar macrophage,Macrophages,Monocytes,alveolar macrophage,alveolar macrophage,0.681230,0.992620,0.989131
23,Monocytes,"CD8-positive, alpha-beta T cell",T cells,T cells,T cell,"CD8-positive, alpha-beta T cell",0.438008,0.777511,0.889137
24,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.763462,0.761303,0.987557
25,Tem/Temra cytotoxic T cells,mature NK T cell,T cells,T cells,natural killer cell,mature NK T cell,0.832806,0.989733,0.973082
26,Tem/Temra cytotoxic T cells,type II pneumocyte,Adipocytes,Adipocytes,type II pneumocyte,type II pneumocyte,0.122436,0.971322,0.978777
27,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.665669,0.999985,0.997494
28,Monocytes,T cell,T cells,T cells,myeloid cell,T cell,0.498110,0.999693,0.985322
29,CD16+ NK cells,neutrophil,Granulocytes,Granulocytes,leukocyte,neutrophil,0.543650,0.973990,0.948912
30,Monocytes,T cell,T cells,T cells,myeloid cell,regulatory T cell,0.039679,0.938878,0.935878
31,Regulatory T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.503067,0.814105,0.940865
32,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.808726,1.000000,0.951031
33,Tem/Temra cytotoxic T cells,club cell of bronchiole,Hepatocytes,Ependymal,ciliated columnar cell of tracheobronchial tree,club cell of bronchiole,0.506561,0.766281,0.986854
34,Monocytes,myeloid dendritic cell,Monocytes,Monocytes,myeloid cell,myeloid dendritic cell,0.243165,0.976505,0.976010
35,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,NK cell,0.688880,0.768050,0.940423
36,Monocytes,lung macrophage,Monocytes,Monocytes,classical monocyte,lung macrophage,0.413371,0.829754,0.973225
37,Monocytes,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.204667,1.000000,0.991495
38,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.087976,0.993620,0.997387
39,Endothelial cells,bronchial smooth muscle cell,Endothelial cells,Endothelial cells,lung endothelial cell,smooth muscle cell of the pulmonary artery,0.479676,0.986211,0.952282
40,Monocytes,T cell,T cells,T cells,natural killer cell,T cell,0.805031,0.990675,0.978623
41,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.651780,1.000000,0.995593
42,Monocytes,T cell,T cells,T cells,T cell,T cell,0.536491,0.828359,0.916143
43,Non-classical monocytes,classical monocyte,Monocytes,Monocytes,myeloid cell,myeloid dendritic cell,0.774565,0.930673,0.917074
44,CD16+ NK cells,basophil,Granulocytes,Granulocytes,mast cell,basophil,0.674560,1.000000,0.973069
45,DC2,dendritic cell,Macrophages,"['B cells', 'Dendritic cells'] Categories (23,...",myeloid cell,dendritic cell,0.064725,0.973631,1.000000
46,Monocytes,B cell,B cells,B cells,B cell,vein endothelial cell,0.242576,1.000000,0.999876
47,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,mature NK T cell,0.799856,0.995141,0.895356
48,Monocytes,plasma cell,B cells,B cells,myeloid cell,plasma cell,0.125643,0.979157,0.999998
49,Double-positive thymocytes,T cell,T cells,T cells,T cell,plasma cell,0.622099,0.696061,0.909164

In [21]:
def get_first(val):
    """提取集合类型中的第一个元素，否则返回原值"""
    # 检查是否为 list, ndarray 或 Series
    if isinstance(val, (list, np.ndarray, pd.Series)):
        return val[0] if len(val) > 0 else np.nan
    return val

for col in df_cleaned.columns:
    if pd.api.types.is_categorical_dtype(df_cleaned[col]):
        # 对于分类对象，必须修改其底层的 categories 映射
        new_categories = [get_first(cat) for cat in df_cleaned[col].cat.categories]
        df_cleaned[col] = df_cleaned[col].cat.rename_categories(new_categories)
    else:
        # 对于普通对象列，直接使用 map 映射
        df_cleaned[col] = df_cleaned[col].map(get_first)
df_cleaned

/tmp/ipykernel_813/2560177970.py:9: DeprecationWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, pd.CategoricalDtype) instead
  if pd.api.types.is_categorical_dtype(df_cleaned[col]):

,celltypist_label,celltypist_ref_label,SingleR_main,SingleR_fine,SingleR_user_ref,scANVI_predicted,celltypist_score,celltypist_ref_score,scANVI_transfer_score
overcluster,,,,,,,,,
0,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,NK cell,0.895466,0.999999,0.996787
1,Tem/Trm cytotoxic T cells,"CD8-positive, alpha-beta T cell",T cells,T cells,T cell,"CD8-positive, alpha-beta T cell",0.630908,0.738386,0.979727
2,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.213961,1.000000,0.999943
3,Monocytes,non-classical monocyte,Monocytes,Monocytes,non-classical monocyte,non-classical monocyte,0.782497,0.993336,0.988801
4,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.732274,1.000000,0.999095
5,Monocytes,neutrophil,Granulocytes,Granulocytes,leukocyte,neutrophil,0.920463,1.000000,0.999711
6,Monocytes,intermediate monocyte,Monocytes,Monocytes,classical monocyte,myeloid dendritic cell,0.726763,0.614637,0.986836
7,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.670952,0.937419,0.999440
8,Naive B cells,B cell,B cells,B cells,B cell,vein endothelial cell,0.486414,1.000000,0.949152
9,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.688623,1.000000,0.997401
10,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.657648,0.926794,0.998895
11,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.669002,1.000000,0.999565
12,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.653389,1.000000,0.997091
13,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.679175,0.875766,0.997039
14,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.211475,1.000000,0.999754
15,Monocytes,B cell,B cells,B cells,B cell,B cell,0.512745,0.998938,0.947005
16,Tem/Trm cytotoxic T cells,regulatory T cell,T cells,T cells,T cell,regulatory T cell,0.637648,0.980990,0.964668
17,Regulatory T cells,regulatory T cell,T cells,T cells,T cell,regulatory T cell,0.586515,0.889353,0.948677
18,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.180494,1.000000,0.996430
19,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.363484,0.999575,0.997496
20,Tem/Trm cytotoxic T cells,mature NK T cell,T cells,T cells,natural killer cell,mature NK T cell,0.953363,0.975796,0.990966
21,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.626014,1.000000,0.997107
22,Alveolar macrophages,alveolar macrophage,Macrophages,Monocytes,alveolar macrophage,alveolar macrophage,0.681230,0.992620,0.989131
23,Monocytes,"CD8-positive, alpha-beta T cell",T cells,T cells,T cell,"CD8-positive, alpha-beta T cell",0.438008,0.777511,0.889137
24,Tcm/Naive helper T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.763462,0.761303,0.987557
25,Tem/Temra cytotoxic T cells,mature NK T cell,T cells,T cells,natural killer cell,mature NK T cell,0.832806,0.989733,0.973082
26,Tem/Temra cytotoxic T cells,type II pneumocyte,Adipocytes,Adipocytes,type II pneumocyte,type II pneumocyte,0.122436,0.971322,0.978777
27,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.665669,0.999985,0.997494
28,Monocytes,T cell,T cells,T cells,myeloid cell,T cell,0.498110,0.999693,0.985322
29,CD16+ NK cells,neutrophil,Granulocytes,Granulocytes,leukocyte,neutrophil,0.543650,0.973990,0.948912
30,Monocytes,T cell,T cells,T cells,myeloid cell,regulatory T cell,0.039679,0.938878,0.935878
31,Regulatory T cells,"CD4-positive, alpha-beta T cell",T cells,T cells,T cell,"CD4-positive, alpha-beta T cell",0.503067,0.814105,0.940865
32,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.808726,1.000000,0.951031
33,Tem/Temra cytotoxic T cells,club cell of bronchiole,Hepatocytes,Ependymal,ciliated columnar cell of tracheobronchial tree,club cell of bronchiole,0.506561,0.766281,0.986854
34,Monocytes,myeloid dendritic cell,Monocytes,Monocytes,myeloid cell,myeloid dendritic cell,0.243165,0.976505,0.976010
35,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,NK cell,0.688880,0.768050,0.940423
36,Monocytes,lung macrophage,Monocytes,Monocytes,classical monocyte,lung macrophage,0.413371,0.829754,0.973225
37,Monocytes,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.204667,1.000000,0.991495
38,Alveolar macrophages,alveolar macrophage,Macrophages,Macrophages,alveolar macrophage,alveolar macrophage,0.087976,0.993620,0.997387
39,Endothelial cells,bronchial smooth muscle cell,Endothelial cells,Endothelial cells,lung endothelial cell,smooth muscle cell of the pulmonary artery,0.479676,0.986211,0.952282
40,Monocytes,T cell,T cells,T cells,natural killer cell,T cell,0.805031,0.990675,0.978623
41,Naive B cells,B cell,B cells,B cells,B cell,B cell,0.651780,1.000000,0.995593
42,Monocytes,T cell,T cells,T cells,T cell,T cell,0.536491,0.828359,0.916143
43,Non-classical monocytes,classical monocyte,Monocytes,Monocytes,myeloid cell,myeloid dendritic cell,0.774565,0.930673,0.917074
44,CD16+ NK cells,basophil,Granulocytes,Granulocytes,mast cell,basophil,0.674560,1.000000,0.973069
45,DC2,dendritic cell,Macrophages,"['B cells', 'Dendritic cells'] Categories (23,...",myeloid cell,dendritic cell,0.064725,0.973631,1.000000
46,Monocytes,B cell,B cells,B cells,B cell,vein endothelial cell,0.242576,1.000000,0.999876
47,CD16- NK cells,NK cell,NK cells,NK cells,natural killer cell,mature NK T cell,0.799856,0.995141,0.895356
48,Monocytes,plasma cell,B cells,B cells,myeloid cell,plasma cell,0.125643,0.979157,0.999998
49,Double-positive thymocytes,T cell,T cells,T cells,T cell,plasma cell,0.622099,0.696061,0.909164

In [38]:
df_cleaned['SingleR_fine'][45]

/tmp/ipykernel_813/2467991953.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df_cleaned['SingleR_fine'][45]

['B cells', 'Dendritic cells']
Categories (23, object): ['Adipocytes', 'B cells', 'Dendritic cells', 'Endothelial cells', ..., 'OPCs', 'T cells', 'aNSCs', 'qNSCs']

In [5]:
import json

def create_annotation_panel(obs, cluster_id='leiden', ground_truth=None, label_columns=['celltypist_label', 'celltypist_ref_label', 'SingleR_main', 'SingleR_fine', 'SingleR_user_ref', 'scANVI_predicted'], score_columns=['celltypist_score', 'celltypist_ref_score', 'scANVI_transfer_score']):
    unique_cell_labels = []
    obs_cols = []

    print(f"label columns: {label_columns}")
    print(f"score columns: {score_columns}")

    # Validate label and score columns
    for label_column in label_columns.copy():
        if label_column not in obs.columns:
            label_columns.remove(label_column)
    for score_column in score_columns.copy():
        if score_column not in obs.columns:
            score_columns.remove(score_column)
    
    print(f"Valid label columns: {label_columns}")
    print(f"Valid score columns: {score_columns}")

    # Add ground truth and cluster id at the front if they exist
    if ground_truth is not None and ground_truth in obs.columns:
        label_columns = [ground_truth] + label_columns
    else:
        # Retrieve unique cell type labels
        try:
            with open('/usr/src/app/storage/uniqueCellLabels.json', 'r', encoding='utf-8') as file:
                unique_cell_labels = json.load(file)
        except FileNotFoundError:
            print("The specified JSON file was not found.")
        except json.JSONDecodeError:
            print("Error decoding JSON. Ensure the file contains a valid list.")
        # Add cell type annotations to obsSets
        if len(unique_cell_labels) > 0:
            for label in unique_cell_labels:
                if label in obs.columns:
                    obs_cols.append(label)
            if len(obs_cols) > 0:
                label_columns = obs_cols + label_columns
    
    if "cell_label" in obs.columns and "cell_label" not in label_columns:
        label_columns = ["cell_label"] + label_columns

    if cluster_id in obs.columns:
        label_columns = [cluster_id] + label_columns
        score_columns = [cluster_id] + score_columns
    else:
        return None

    if len(label_columns) == 0:
        return None

    if len(label_columns) > 1:
        labels_df = obs[label_columns].groupby(cluster_id).agg(lambda x: x.mode())
        labels_df.insert(loc=1, column='majority_vote', value=labels_df.mode(axis=1)[0])
        # labels_df['majority_vote'] = labels_df.mode(axis=1)[0]
        if "cell_label" not in obs.columns:
            # labels_df["cell_label"] = labels_df['majority_vote']
            if ground_truth is not None and ground_truth in obs.columns:
                labels_df.insert(loc=0, column='cell_label', value=labels_df[ground_truth])
            else:
                labels_df.insert(loc=0, column='cell_label', value=labels_df['majority_vote'])
        try:
            unique_labels = labels_df.astype(object).stack().unique().tolist()
        except Exception as e:
            print(f"Error getting unique labels: {e}")
            unique_labels = labels_df["cell_label"].unique().tolist()         
    else:
        labels_df = pd.DataFrame(obs[cluster_id].unique(), columns=['Cluster'])
        unique_labels = None
        labels_df["cell_label"] = ''

    if len(score_columns) > 1:
        scores_df = obs[score_columns].groupby(cluster_id).agg(lambda x: x.mean())
        scores_df = scores_df.round(4)

        mapping_res = labels_df.merge(right = scores_df, left_index=True, right_index=True)
        mapping_res.insert(0, 'Cluster', mapping_res.index)
        mapping_res_dict = mapping_res.to_dict('list', index=True)
    else:
        if "Cluster" not in labels_df.columns:
            labels_df.insert(0, 'Cluster', labels_df.index)
        mapping_res_dict = labels_df.to_dict('list', index=True)

    return { "cluster_id": cluster_id, "table": mapping_res_dict, "unique_labels": unique_labels, }

In [6]:
ap = create_annotation_panel(adata.obs, cluster_id='overcluster')
ap

label columns: ['celltypist_label', 'celltypist_ref_label', 'SingleR_main', 'SingleR_fine', 'SingleR_user_ref', 'scANVI_predicted']
score columns: ['celltypist_score', 'celltypist_ref_score', 'scANVI_transfer_score']
Valid label columns: ['SingleR_main', 'SingleR_fine']
Valid score columns: []

/tmp/ipykernel_813/3457886125.py:54: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  labels_df = obs[label_columns].groupby(cluster_id).agg(lambda x: x.mode())

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [7]:
labels = adata.obs[['X_scVI_leiden', 'celltypist_label', 'celltypist_ref_label', 'SingleR_main', 'SingleR_fine', 'SingleR_user_ref', 'scANVI_predicted']].groupby('X_scVI_leiden').agg(lambda x: x.mode())
scores = adata.obs[['X_scVI_leiden', 'celltypist_score', 'celltypist_ref_score', 'scANVI_transfer_score']].groupby('X_scVI_leiden').agg(lambda x: x.mean())

mapping_res = labels.merge(right = scores, left_index=True, right_index=True)

KeyError: "['X_scVI_leiden', 'SingleR_main', 'SingleR_fine', 'SingleR_user_ref', 'scANVI_predicted'] not in index"

In [8]:
cluster = adata.obs['X_scVI_leiden'].unique()
cluster

['0', '1', '2', '3', '4', '5', '6', '7']
Categories (8, object): ['0', '1', '2', '3', '4', '5', '6', '7']

In [9]:
df = pd.DataFrame(adata.obs['X_scVI_leiden'].unique(), columns=['cluster'])
df

  cluster
0       0
1       1
2       2
3       3
4       4
5       5
6       6
7       7

In [10]:
unique_values = labels.stack().unique()
unique_values

array(['Macrophage', 'macrophage', 'Monocytes', 'Macrophages',
       'capillary 2', 'endothelial cell', 'Endothelial cells',
       'Stromal cell (DN)', 'Fibroblasts', 'Cardiomyocytes',
       'enterocyte of epithelium of large intestine',
       'kidney collecting duct epithelial cell', 'Epithelial cells',
       'Ependymal', 'Enterocyte.dist',
       'epithelial cell of proximal tubule', 'Hepatocytes', 'EP'],
      dtype=object)

In [11]:
labels['majority_vote'] = labels.mode(axis=1)[0]
labels['majority_vote']

X_scVI_leiden
0                                macrophage
1                          endothelial cell
2                          endothelial cell
3    kidney collecting duct epithelial cell
4        epithelial cell of proximal tubule
5        epithelial cell of proximal tubule
6    kidney collecting duct epithelial cell
7    kidney collecting duct epithelial cell
Name: majority_vote, dtype: object

In [12]:
labels["cell_type"] = labels['majority_vote']
labels

,celltypist_label,celltypist_ref_label,SingleR_main,SingleR_fine,SingleR_user_ref,scANVI_predicted,majority_vote,cell_type
X_scVI_leiden,,,,,,,,
0,Macrophage,macrophage,Monocytes,Macrophages,macrophage,macrophage,macrophage,macrophage
1,capillary 2,endothelial cell,Endothelial cells,Endothelial cells,endothelial cell,endothelial cell,endothelial cell,endothelial cell
2,Stromal cell (DN),endothelial cell,Fibroblasts,Cardiomyocytes,endothelial cell,endothelial cell,endothelial cell,endothelial cell
3,enterocyte of epithelium of large intestine,kidney collecting duct epithelial cell,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell
4,Enterocyte.dist,epithelial cell of proximal tubule,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,epithelial cell of proximal tubule,epithelial cell of proximal tubule,epithelial cell of proximal tubule
5,Enterocyte.dist,epithelial cell of proximal tubule,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,epithelial cell of proximal tubule,epithelial cell of proximal tubule,epithelial cell of proximal tubule
6,enterocyte of epithelium of large intestine,kidney collecting duct epithelial cell,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell
7,EP,kidney collecting duct epithelial cell,Epithelial cells,Hepatocytes,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell

In [13]:
labels["cell_type"] = ''
labels

,celltypist_label,celltypist_ref_label,SingleR_main,SingleR_fine,SingleR_user_ref,scANVI_predicted,majority_vote,cell_type
X_scVI_leiden,,,,,,,,
0,Macrophage,macrophage,Monocytes,Macrophages,macrophage,macrophage,macrophage,
1,capillary 2,endothelial cell,Endothelial cells,Endothelial cells,endothelial cell,endothelial cell,endothelial cell,
2,Stromal cell (DN),endothelial cell,Fibroblasts,Cardiomyocytes,endothelial cell,endothelial cell,endothelial cell,
3,enterocyte of epithelium of large intestine,kidney collecting duct epithelial cell,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,
4,Enterocyte.dist,epithelial cell of proximal tubule,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,epithelial cell of proximal tubule,epithelial cell of proximal tubule,
5,Enterocyte.dist,epithelial cell of proximal tubule,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,epithelial cell of proximal tubule,epithelial cell of proximal tubule,
6,enterocyte of epithelium of large intestine,kidney collecting duct epithelial cell,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,
7,EP,kidney collecting duct epithelial cell,Epithelial cells,Hepatocytes,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,

In [14]:
scores = scores.round(4)
scores

               celltypist_score  celltypist_ref_score  scANVI_transfer_score
X_scVI_leiden
0                        0.5735                0.6322                 0.5080
1                        0.3751                0.9896                 0.9662
2                        0.7237                0.6877                 0.7301
3                        0.2390                0.9824                 0.9213
4                        0.2908                0.9906                 0.9702
5                        0.2105                0.9782                 0.9543
6                        0.2982                0.9970                 0.9362
7                        0.1793                0.5942                 0.7394

In [15]:
mapping_res

,celltypist_label,celltypist_ref_label,SingleR_main,SingleR_fine,SingleR_user_ref,scANVI_predicted,celltypist_score,celltypist_ref_score,scANVI_transfer_score
X_scVI_leiden,,,,,,,,,
0,Macrophage,macrophage,Monocytes,Macrophages,macrophage,macrophage,0.573521,0.632177,0.507997
1,capillary 2,endothelial cell,Endothelial cells,Endothelial cells,endothelial cell,endothelial cell,0.375120,0.989611,0.966207
2,Stromal cell (DN),endothelial cell,Fibroblasts,Cardiomyocytes,endothelial cell,endothelial cell,0.723670,0.687725,0.730093
3,enterocyte of epithelium of large intestine,kidney collecting duct epithelial cell,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,0.239047,0.982418,0.921272
4,Enterocyte.dist,epithelial cell of proximal tubule,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,epithelial cell of proximal tubule,0.290825,0.990636,0.970240
5,Enterocyte.dist,epithelial cell of proximal tubule,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,epithelial cell of proximal tubule,0.210512,0.978177,0.954272
6,enterocyte of epithelium of large intestine,kidney collecting duct epithelial cell,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,0.298205,0.997049,0.936162
7,EP,kidney collecting duct epithelial cell,Epithelial cells,Hepatocytes,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,0.179310,0.594204,0.739395

In [16]:
mapping_res['cluster'] = mapping_res.index
mapping_res

,celltypist_label,celltypist_ref_label,SingleR_main,SingleR_fine,SingleR_user_ref,scANVI_predicted,celltypist_score,celltypist_ref_score,scANVI_transfer_score,cluster
X_scVI_leiden,,,,,,,,,,
0,Macrophage,macrophage,Monocytes,Macrophages,macrophage,macrophage,0.573521,0.632177,0.507997,0
1,capillary 2,endothelial cell,Endothelial cells,Endothelial cells,endothelial cell,endothelial cell,0.375120,0.989611,0.966207,1
2,Stromal cell (DN),endothelial cell,Fibroblasts,Cardiomyocytes,endothelial cell,endothelial cell,0.723670,0.687725,0.730093,2
3,enterocyte of epithelium of large intestine,kidney collecting duct epithelial cell,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,0.239047,0.982418,0.921272,3
4,Enterocyte.dist,epithelial cell of proximal tubule,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,epithelial cell of proximal tubule,0.290825,0.990636,0.970240,4
5,Enterocyte.dist,epithelial cell of proximal tubule,Hepatocytes,Hepatocytes,epithelial cell of proximal tubule,epithelial cell of proximal tubule,0.210512,0.978177,0.954272,5
6,enterocyte of epithelium of large intestine,kidney collecting duct epithelial cell,Epithelial cells,Ependymal,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,0.298205,0.997049,0.936162,6
7,EP,kidney collecting duct epithelial cell,Epithelial cells,Hepatocytes,kidney collecting duct epithelial cell,kidney collecting duct epithelial cell,0.179310,0.594204,0.739395,7

In [17]:
dict_d = mapping_res.to_dict('list', index=True)

In [18]:
dict_d

{'celltypist_label': ['Macrophage',
  'capillary 2',
  'Stromal cell (DN)',
  'enterocyte of epithelium of large intestine',
  'Enterocyte.dist',
  'Enterocyte.dist',
  'enterocyte of epithelium of large intestine',
  'EP'],
 'celltypist_ref_label': ['macrophage',
  'endothelial cell',
  'endothelial cell',
  'kidney collecting duct epithelial cell',
  'epithelial cell of proximal tubule',
  'epithelial cell of proximal tubule',
  'kidney collecting duct epithelial cell',
  'kidney collecting duct epithelial cell'],
 'SingleR_main': ['Monocytes',
  'Endothelial cells',
  'Fibroblasts',
  'Epithelial cells',
  'Hepatocytes',
  'Hepatocytes',
  'Epithelial cells',
  'Epithelial cells'],
 'SingleR_fine': ['Macrophages',
  'Endothelial cells',
  'Cardiomyocytes',
  'Ependymal',
  'Hepatocytes',
  'Hepatocytes',
  'Ependymal',
  'Hepatocytes'],
 'SingleR_user_ref': ['macrophage',
  'endothelial cell',
  'endothelial cell',
  'kidney collecting duct epithelial cell',
  'epithelial cell of proximal tubule',
  'epithelial cell of proximal tubule',
  'kidney collecting duct epithelial cell',
  'kidney collecting duct epithelial cell'],
 'scANVI_predicted': ['macrophage',
  'endothelial cell',
  'endothelial cell',
  'kidney collecting duct epithelial cell',
  'epithelial cell of proximal tubule',
  'epithelial cell of proximal tubule',
  'kidney collecting duct epithelial cell',
  'kidney collecting duct epithelial cell'],
 'celltypist_score': [0.5735207931693991,
  0.3751198156015275,
  0.7236695900226209,
  0.23904675835603523,
  0.290824752055398,
  0.21051211161295952,
  0.29820472101828405,
  0.17931003714027183],
 'celltypist_ref_score': [0.6321773278594067,
  0.989610677133763,
  0.6877247754401633,
  0.9824177130440717,
  0.9906355966891872,
  0.9781767111285953,
  0.9970487260926868,
  0.5942039475657453],
 'scANVI_transfer_score': [0.5079965591430664,
  0.9662070870399475,
  0.7300931811332703,
  0.9212722778320312,
  0.9702402353286743,
  0.9542720913887024,
  0.9361615180969238,
  0.7393954992294312],
 'cluster': ['0', '1', '2', '3', '4', '5', '6', '7']}

In [55]:
import json

def create_annotation_panel(obs, cluster_id='leiden', ground_truth=None, label_columns=['celltypist_label', 'celltypist_ref_label', 'SingleR_main', 'SingleR_fine', 'SingleR_user_ref', 'scANVI_predicted'], score_columns=['celltypist_score', 'celltypist_ref_score', 'scANVI_transfer_score']):
    unique_cell_labels = []
    obs_cols = []

    print("label columns: " + str(label_columns))
    print("score columns: " + str(score_columns))

    # Validate label and score columns
    for label_column in label_columns.copy():
        if label_column not in obs.columns:
            label_columns.remove(label_column)
    for score_column in score_columns.copy():
        if score_column not in obs.columns:
            score_columns.remove(score_column)

    # Add ground truth and cluster id at the front if they exist
    if ground_truth is not None and ground_truth in obs.columns:
        label_columns = [ground_truth] + label_columns
    else:
        # Retrieve unique cell type labels
        try:
            with open('/usr/src/app/storage/uniqueCellLabels.json', 'r', encoding='utf-8') as file:
                unique_cell_labels = json.load(file)
        except FileNotFoundError:
            print("The specified JSON file was not found.")
        except json.JSONDecodeError:
            print("Error decoding JSON. Ensure the file contains a valid list.")
        # Add cell type annotations to obsSets
        if len(unique_cell_labels) > 0:
            for label in unique_cell_labels:
                if label in obs.columns:
                    obs_cols.append(label)
            if len(obs_cols) > 0:
                label_columns = obs_cols + label_columns
    
    if "cell_label" in obs.columns and "cell_label" not in label_columns:
        label_columns = ["cell_label"] + label_columns

    if cluster_id in obs.columns:
        label_columns = [cluster_id] + label_columns
        score_columns = [cluster_id] + score_columns
    else:
        return None

    print("Valid label columns: " + str(label_columns))
    print("Valid score columns: " + str(score_columns))

    if len(label_columns) == 0:
        return None

    if len(label_columns) > 1:
        labels_df = obs[label_columns].groupby(cluster_id).agg(lambda x: x.mode())
        unique_labels = labels_df.stack().unique().tolist()
        labels_df.insert(loc=0, column='majority_vote', value=labels_df.mode(axis=1)[0])
        # labels_df['majority_vote'] = labels_df.mode(axis=1)[0]
        if "cell_label" not in obs.columns:
            # labels_df["cell_label"] = labels_df['majority_vote']
            labels_df.insert(loc=0, column='cell_label', value=labels_df['majority_vote'])
    else:
        labels_df = pd.DataFrame(obs[cluster_id].unique(), columns=['Cluster'])
        unique_labels = None
        labels_df["cell_label"] = ''

    if len(score_columns) > 1:
        scores_df = obs[score_columns].groupby(cluster_id).agg(lambda x: x.mean())
        scores_df = scores_df.round(4)
        print(scores_df)

        mapping_res = labels_df.merge(right = scores_df, left_index=True, right_index=True)
        mapping_res.scANVI_transfer_score.round(4)
        mapping_res.insert(0, 'Cluster', mapping_res.index)
        mapping_res_dict = mapping_res.to_dict('list', index=True)
    else:
        mapping_res_dict = labels_df.to_dict('list', index=True)

    return {"table": mapping_res_dict, "unique_labels": unique_labels}

In [56]:
res = create_annotation_panel(adata.obs, cluster_id='X_scVI_leiden')

label columns: ['celltypist_label', 'celltypist_ref_label', 'SingleR_main', 'SingleR_fine', 'SingleR_user_ref', 'scANVI_predicted']
score columns: ['celltypist_score', 'celltypist_ref_score', 'scANVI_transfer_score']
Valid label columns: ['X_scVI_leiden', 'cell_ontology_class', 'celltypist_label', 'celltypist_ref_label', 'SingleR_main', 'SingleR_fine', 'SingleR_user_ref', 'scANVI_predicted']
Valid score columns: ['X_scVI_leiden', 'celltypist_score', 'celltypist_ref_score', 'scANVI_transfer_score']
               celltypist_score  celltypist_ref_score  scANVI_transfer_score
X_scVI_leiden
0                        0.5735                0.6322                 0.5080
1                        0.3751                0.9896                 0.9662
2                        0.7237                0.6877                 0.7301
3                        0.2390                0.9824                 0.9213
4                        0.2908                0.9906                 0.9702
5                        0.2105                0.9782                 0.9543
6                        0.2982                0.9970                 0.9362
7                        0.1793                0.5942                 0.7394

/tmp/ipykernel_91/2849808307.py:54: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  labels_df = obs[label_columns].groupby(cluster_id).agg(lambda x: x.mode())
/tmp/ipykernel_91/2849808307.py:67: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  scores_df = obs[score_columns].groupby(cluster_id).agg(lambda x: x.mean())

In [57]:
res

{'table': {'Cluster': ['0', '1', '2', '3', '4', '5', '6', '7'],
  'cell_label': ['macrophage',
   'endothelial cell',
   'endothelial cell',
   'kidney collecting duct epithelial cell',
   'epithelial cell of proximal tubule',
   'epithelial cell of proximal tubule',
   'kidney collecting duct epithelial cell',
   'kidney collecting duct epithelial cell'],
  'majority_vote': ['macrophage',
   'endothelial cell',
   'endothelial cell',
   'kidney collecting duct epithelial cell',
   'epithelial cell of proximal tubule',
   'epithelial cell of proximal tubule',
   'kidney collecting duct epithelial cell',
   'kidney collecting duct epithelial cell'],
  'cell_ontology_class': ['leukocyte',
   'kidney capillary endothelial cell',
   'mesangial cell',
   'kidney collecting duct epithelial cell',
   'kidney proximal straight tubule epithelial cell',
   'kidney proximal straight tubule epithelial cell',
   'kidney loop of Henle ascending limb epithelial cell',
   'kidney collecting duct epithelial cell'],
  'celltypist_label': ['Macrophage',
   'capillary 2',
   'Stromal cell (DN)',
   'enterocyte of epithelium of large intestine',
   'Enterocyte.dist',
   'Enterocyte.dist',
   'enterocyte of epithelium of large intestine',
   'EP'],
  'celltypist_ref_label': ['macrophage',
   'endothelial cell',
   'endothelial cell',
   'kidney collecting duct epithelial cell',
   'epithelial cell of proximal tubule',
   'epithelial cell of proximal tubule',
   'kidney collecting duct epithelial cell',
   'kidney collecting duct epithelial cell'],
  'SingleR_main': ['Monocytes',
   'Endothelial cells',
   'Fibroblasts',
   'Epithelial cells',
   'Hepatocytes',
   'Hepatocytes',
   'Epithelial cells',
   'Epithelial cells'],
  'SingleR_fine': ['Macrophages',
   'Endothelial cells',
   'Cardiomyocytes',
   'Ependymal',
   'Hepatocytes',
   'Hepatocytes',
   'Ependymal',
   'Hepatocytes'],
  'SingleR_user_ref': ['macrophage',
   'endothelial cell',
   'endothelial cell',
   'kidney collecting duct epithelial cell',
   'epithelial cell of proximal tubule',
   'epithelial cell of proximal tubule',
   'kidney collecting duct epithelial cell',
   'kidney collecting duct epithelial cell'],
  'scANVI_predicted': ['macrophage',
   'endothelial cell',
   'endothelial cell',
   'kidney collecting duct epithelial cell',
   'epithelial cell of proximal tubule',
   'epithelial cell of proximal tubule',
   'kidney collecting duct epithelial cell',
   'kidney collecting duct epithelial cell'],
  'celltypist_score': [0.5735,
   0.3751,
   0.7237,
   0.239,
   0.2908,
   0.2105,
   0.2982,
   0.1793],
  'celltypist_ref_score': [0.6322,
   0.9896,
   0.6877,
   0.9824,
   0.9906,
   0.9782,
   0.997,
   0.5942],
  'scANVI_transfer_score': [0.5080000162124634,
   0.9661999940872192,
   0.7300999760627747,
   0.9212999939918518,
   0.9702000021934509,
   0.9542999863624573,
   0.9362000226974487,
   0.7394000291824341]},
 'unique_labels': ['leukocyte',
  'Macrophage',
  'macrophage',
  'Monocytes',
  'Macrophages',
  'kidney capillary endothelial cell',
  'capillary 2',
  'endothelial cell',
  'Endothelial cells',
  'mesangial cell',
  'Stromal cell (DN)',
  'Fibroblasts',
  'Cardiomyocytes',
  'kidney collecting duct epithelial cell',
  'enterocyte of epithelium of large intestine',
  'Epithelial cells',
  'Ependymal',
  'kidney proximal straight tubule epithelial cell',
  'Enterocyte.dist',
  'epithelial cell of proximal tubule',
  'Hepatocytes',
  'kidney loop of Henle ascending limb epithelial cell',
  'EP']}

In [35]:
# mapping_res.insert(0, 'Cluster', mapping_res.index)
# mapping_res

ValueError: cannot insert Cluster, already exists

In [29]:
res

AttributeError: 'dict' object has no attribute 'round'

In [23]:
label_columns=['celltypist_label', 'celltypist_ref_label', 'SingleR_main', 'SingleR_fine', 'SingleR_user_ref', 'scANVI_predicted']
label_columns.remove('celltypist_ref_label')
label_columns

['celltypist_label',
 'SingleR_main',
 'SingleR_fine',
 'SingleR_user_ref',
 'scANVI_predicted']

In [2]:
adata_path='/usr/src/app/storage/Benchmarks/facsKidney_1755709836242/QC/quality_control/6a35c4b51c09e25a1863f87b8646f87f/facs_Kidney_scanpy.h5ad'
adata = sc.read_h5ad(adata_path)
adata

AnnData object with n_obs × n_vars = 183 × 1968
    obs: 'orig.ident', 'n_counts', 'n_genes', 'nReads', 'plate.barcode', 'mouse.id', 'tissue', 'subtissue', 'FACS.selection', 'mouse.sex', 'percent.ercc', 'cell_ontology_class', 'percent.ribo', 'res.2.5', 'previous_cell_ontology_class', 'cluster.ids', 'cell_ontology_id', 'pct_counts_mt', 'pct_counts_rb', 'pct_counts_hb', 'percent.plat', 'RNA_snn_res.0.5', 'seurat_clusters', 'doublet_score', 'doublet_class', 'leiden', 'louvain', 'split_idx', '_scvi_batch', '_scvi_labels', 'leiden_X_scVI', 'louvain_X_scVI', 'n_genes_by_counts', 'log1p_n_genes_by_counts', 'total_counts', 'log1p_total_counts', 'pct_counts_in_top_20_genes', 'total_counts_mt', 'log1p_total_counts_mt', 'total_counts_ribo', 'log1p_total_counts_ribo', 'pct_counts_ribo', 'total_counts_hb', 'log1p_total_counts_hb', 'outlier', 'predicted_doublet', 'clf_doublet', 'clf_score'
    var: 'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'highly_variable', 'n_cells', 'mt', 'ribo', 'hb', 'n_cells_by_counts', 'mean_counts', 'log1p_mean_counts', 'pct_dropout_by_counts', 'total_counts', 'log1p_total_counts', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: '_scvi_manager_uuid', '_scvi_uuid', 'hvg', 'leiden', 'leiden_X_scVI', 'log1p', 'louvain', 'louvain_X_scVI', 'neighbors', 'pca', 'scrublet'
    obsm: 'X_mde', 'X_pca', 'X_scVI', 'X_tsne', 'X_tsne_3D', 'X_umap', 'X_umap_3D'
    varm: 'PCs'
    layers: 'X_normalized', 'logCP10K', 'raw_counts', 'scale.data', 'scvi_normalized'
    obsp: 'connectivities', 'distances'

In [3]:
adata.obs

,orig.ident,n_counts,n_genes,nReads,plate.barcode,mouse.id,tissue,subtissue,FACS.selection,mouse.sex,...,log1p_total_counts_mt,total_counts_ribo,log1p_total_counts_ribo,pct_counts_ribo,total_counts_hb,log1p_total_counts_hb,outlier,predicted_doublet,clf_doublet,clf_score
A10.B002775.3_39_F.1.1,Kidney,240236.0,259,1059637.0,B002775,3_39_F,Kidney,,Viable,F,...,0.0,0.0,0.0,0.0,0.0,0.0,False,False,0.0,1.488354
A10.MAA000752.3_10_M.1.1,Kidney,80776.0,231,409127.0,MAA000752,3_10_M,Kidney,,Viable,M,...,0.0,0.0,0.0,0.0,0.0,0.0,False,False,0.0,0.888148
A13.B001717.3_38_F.1.1,Kidney,146791.0,302,725921.0,B001717,3_38_F,Kidney,,Viable,F,...,0.0,0.0,0.0,0.0,0.0,0.0,False,False,0.0,1.306242
A14.B001717.3_38_F.1.1,Kidney,208008.0,357,424369.0,B001717,3_38_F,Kidney,,Viable,F,...,0.0,0.0,0.0,0.0,0.0,0.0,False,False,0.0,1.994357
A14.MAA000801.3_11_M.1.1,Kidney,23483.0,239,252568.0,MAA000801,3_11_M,Kidney,,Viable,M,...,0.0,0.0,0.0,0.0,0.0,0.0,False,False,0.0,1.056080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P19.B002775.3_39_F.1.1,Kidney,79369.0,219,387285.0,B002775,3_39_F,Kidney,,Viable,F,...,0.0,0.0,0.0,0.0,0.0,0.0,False,False,0.0,0.810189
P21.B002775.3_39_F.1.1,Kidney,49570.0,288,241330.0,B002775,3_39_F,Kidney,,Viable,F,...,0.0,0.0,0.0,0.0,0.0,0.0,False,False,0.0,1.359024
P4.B001717.3_38_F.1.1,Kidney,304048.0,224,861266.0,B001717,3_38_F,Kidney,,Viable,F,...,0.0,0.0,0.0,0.0,0.0,0.0,False,False,0.0,1.227456
P4.MAA000801.3_11_M.1.1,Kidney,380523.0,373,1263701.0,MAA000801,3_11_M,Kidney,,Viable,M,...,0.0,0.0,0.0,0.0,0.0,0.0,False,False,0.0,2.262972
P6.MAA000801.3_11_M.1.1,Kidney,166246.0,275,663581.0,MAA000801,3_11_M,Kidney,,Viable,M,...,0.0,0.0,0.0,0.0,0.0,0.0,False,False,0.0,1.179369

In [4]:
def create_outlier_panel(obs, cluster_id='leiden', outlier_columns = ["outlier", "mt_outlier", "clf_doublet", "predicted_doublets", "clf_doublet", "discard"], score_columns=['doublet_score', 'clf_score']):
    # Validate outlier columns and score columns
    for outlier_column in outlier_columns.copy():
        if outlier_column not in obs.columns:
            outlier_columns.remove(outlier_column)
    for score_column in score_columns.copy():
        if score_column not in obs.columns:
            score_columns.remove(score_column)

    if len(outlier_columns) == 0:
        return None

    if cluster_id in obs.columns:
        outlier_columns = [cluster_id] + outlier_columns
        score_columns = [cluster_id] + score_columns
    else:
        return None

    if len(outlier_columns) > 1:
        outliers_columns_df = obs[outlier_columns].groupby(cluster_id).agg(lambda x: x.mode())
        unique_labels = outliers_columns_df.stack().unique().tolist()
        outliers_columns_df.insert(loc=1, column='majority_vote', value=outliers_columns_df.mode(axis=1)[0])
        # labels_df['majority_vote'] = labels_df.mode(axis=1)[0]
        if "discard" not in obs.columns:
            outliers_columns_df.insert(loc=0, column='discard', value=outliers_columns_df['majority_vote'])

    if len(score_columns) > 1:
        scores_df = obs[score_columns].groupby(cluster_id).agg(lambda x: x.mean())
        scores_df = scores_df.round(4)

        mapping_res = outliers_columns_df.merge(right = scores_df, left_index=True, right_index=True)
        mapping_res.insert(0, 'Cluster', mapping_res.index)
        mapping_res_dict = mapping_res.to_dict('list', index=True)
    else:
        outliers_columns_df.insert(0, 'Cluster', outliers_columns_df.index)
        mapping_res_dict = outliers_columns_df.to_dict('list', index=True)

    return { "cluster_id": cluster_id, "table": mapping_res_dict }

In [5]:
res = create_outlier_panel(adata.obs, cluster_id='leiden')
res

/tmp/ipykernel_759/3207992716.py:20: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  outliers_columns_df = obs[outlier_columns].groupby(cluster_id).agg(lambda x: x.mode())
/tmp/ipykernel_759/3207992716.py:28: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  scores_df = obs[score_columns].groupby(cluster_id).agg(lambda x: x.mean())
/tmp/ipykernel_759/3207992716.py:33: UserWarning: DataFrame columns are not unique, some columns will be omitted.
  mapping_res_dict = mapping_res.to_dict('list', index=True)

{'cluster_id': 'leiden',
 'table': {'Cluster': ['0', '1', '2', '3'],
  'discard': [False, False, False, False],
  'outlier': [False, False, False, False],
  'majority_vote': [False, False, False, False],
  'clf_doublet': [0.0, 0.0, 0.0, 0.0],
  'doublet_score': [0.0731, 0.0781, 0.0756, 0.0792],
  'clf_score': [1.1131, 1.8065, 0.9451, 0.801]}}