In [1]:
source("../tools/formating/formating.R")

Loading required package: SingleCellExperiment

Loading required package: SummarizedExperiment

Loading required package: MatrixGenerics

Loading required package: matrixStats


Attaching package: ‘MatrixGenerics’


The following objects are masked from ‘package:matrixStats’:

    colAlls, colAnyNAs, colAnys, colAvgsPerRowSet, colCollapse,
    colCounts, colCummaxs, colCummins, colCumprods, colCumsums,
    colDiffs, colIQRDiffs, colIQRs, colLogSumExps, colMadDiffs,
    colMads, colMaxs, colMeans2, colMedians, colMins, colOrderStats,
    colProds, colQuantiles, colRanges, colRanks, colSdDiffs, colSds,
    colSums2, colTabulates, colVarDiffs, colVars, colWeightedMads,
    colWeightedMeans, colWeightedMedians, colWeightedSds,
    colWeightedVars, rowAlls, rowAnyNAs, rowAnys, rowAvgsPerColSet,
    rowCollapse, rowCounts, rowCummaxs, rowCummins, rowCumprods,
    rowCumsums, rowDiffs, rowIQRDiffs, rowIQRs, rowLogSumExps,
    rowMadDiffs, rowMads, rowMaxs, rowMeans2, rowMedians, rowMins,
    rowOrderStats, rowProds, rowQuantiles, rowRanges, rowRanks,
    rowSdDiffs, rowSds, rowSums2, rowTabulates, rowVarDiffs, rowVars,
    rowWeightedMads, rowWeightedMeans, rowWeightedMedians,
    rowWeightedSds, rowWeightedVars


Loading required package: GenomicRanges

Loading required package: stats4

Loading required package: BiocGenerics


Attaching package: ‘BiocGenerics’


The following objects are masked from ‘package:stats’:

    IQR, mad, sd, var, xtabs


The following objects are masked from ‘package:base’:

    anyDuplicated, aperm, append, as.data.frame, basename, cbind,
    colnames, dirname, do.call, duplicated, eval, evalq, Filter, Find,
    get, grep, grepl, intersect, is.unsorted, lapply, Map, mapply,
    match, mget, order, paste, pmax, pmax.int, pmin, pmin.int,
    Position, rank, rbind, Reduce, rownames, sapply, setdiff, sort,
    table, tapply, union, unique, unsplit, which.max, which.min


Loading required package: S4Vectors


Attaching package: ‘S4Vectors’


The following objects are masked from ‘package:base’:

    expand.grid, I, unname


Loading required package: IRanges

Loading required package: GenomeInfoDb

Loading required package: Biobase

Welcome to Bioconductor

    Vignettes contain introductory material; view with
    'browseVignettes()'. To cite Bioconductor, see
    'citation("Biobase")', and for packages 'citation("pkgname")'.



Attaching package: ‘Biobase’


The following object is masked from ‘package:MatrixGenerics’:

    rowMedians


The following objects are masked from ‘package:matrixStats’:

    anyMissing, rowMedians


Loading required package: scuttle

Loading required package: ggplot2

The legacy packages maptools, rgdal, and rgeos, underpinning the sp package,
which was just loaded, will retire in October 2023.
Please refer to R-spatial evolution reports for details, especially
https://r-spatial.org/r/2023/05/15/evolution4.html.
It may be desirable to make the sf package available;
package maintainers should consider adding sf to Suggests:.
The sp package is now running under evolution status 2
     (status 2 uses the sf package in place of rgdal)

Attaching SeuratObject


Attaching package: ‘Seurat’


The following object is masked from ‘package:SummarizedExperiment’:

    Assays


Registered S3 method overwritten by 'SeuratDisk':
  method            from
  as.sparse.H5Group Seurat

In [2]:
path <- "/ps/ai-ready/data/Clustering/Tabula_Muris/droplet_Bladder_seurat_tiss.Robj"

In [3]:
srat <- LoadSeurat(path)
srat

Updating from v2.X to v3.X

Validating object structure

Updating object slots

Ensuring keys are in the proper structure

Ensuring feature names don't have underscores or pipes

Object representation is consistent with the most current Seurat version

An object of class Seurat
23341 features across 2500 samples within 1 assay
Active assay: RNA (23341 features, 0 variable features)

In [4]:
default_assay <- DefaultAssay(srat)
default_assay

[1] "RNA"

In [5]:
srat[['RNA']]@counts

  [[ suppressing 32 column names ‘10X_P4_3_AAAGTAGAGATGCCAG’, ‘10X_P4_3_AACCGCGTCCAACCAA’, ‘10X_P4_3_AACTCCCGTCGGGTCT’ ... ]]

  [[ suppressing 32 column names ‘10X_P4_3_AAAGTAGAGATGCCAG’, ‘10X_P4_3_AACCGCGTCCAACCAA’, ‘10X_P4_3_AACTCCCGTCGGGTCT’ ... ]]

  [[ suppressing 32 column names ‘10X_P4_3_AAAGTAGAGATGCCAG’, ‘10X_P4_3_AACCGCGTCCAACCAA’, ‘10X_P4_3_AACTCCCGTCGGGTCT’ ... ]]

23341 x 2500 sparse Matrix of class "dgCMatrix"

Xkr4           .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Rp1            .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Sox17          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Mrpl15         1   .  .   .   .   2   .  .  .   . .  .  .  .  .  .  1   .   1   1  1  .  .
Lypla1         .   2  1   2   .   3   1  .  .   1 .  .  .  1  .  .  .   .   .   1  .  .  .
Tcea1          .   3  1   .   1   1   1  .  1   . .  1  .  1  .  .  1   .   .   2  1  1  .
Rgs20          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Atp6v1h        .   .  2   1   1   .   1  .  1   . .  .  .  .  .  .  .   .   .   1  .  1  .
Oprk1          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Npbwr1         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Rb1cc1         1   2  1   .   .   .   1  .  .   1 .  .  1  .  .  1  2   .   .   .  .  2  .
Fam150a        .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
St18           .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Pcmtd1         .   .  .   .   1   .   .  .  1   2 .  .  2  .  .  1  1   1   .   2  .  .  .
Sntg1          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Rrs1           .   2  .   .   1   .   2  .  1   . .  .  .  .  .  .  .   .   .   .  .  .  .
Adhfe1         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
2610203C22Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
3110035E14Rik  .   1  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Mybl1          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Vcpip1         .   .  .   .   .   .   .  .  1   . .  .  .  .  1  .  .   .   1   1  1  .  .
1700034P13Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Sgk3           1   .  .   .   .   .   1  .  .   1 .  .  .  .  .  .  .   .   .   1  .  .  .
6030422M02Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Snhg6          1   1  1   .   .   .   3  .  1   . .  .  1  2  .  .  1   .   1   1  1  .  .
Snord87        .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Ppp1r42        .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Cops5          1   1  .   3   .   1   1  .  .   . .  .  .  .  1  .  .   .   2   1  .  1  .
Cspp1          .   .  .   .   .   .   .  .  .   1 .  .  .  .  .  1  .   .   .   .  .  .  .
Arfgef1        .   1  .   1   .   .   2  .  .   . .  .  .  .  1  .  .   3   1   2  .  .  1
Cpa6           .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   1   1   .  .  .  1
Mir467e        .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Prex2          .   .  3   .   .   .   .  .  .   . .  1  .  .  1  .  .   1   .   .  .  .  .
A830018L16Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
4932411L15     .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Sulf1          .   1  .   .   .   .   1  .  .   . .  .  .  .  .  .  1   .   .   1  .  .  .
Slco5a1        .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Prdm14         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Ncoa2          .   .  .   .   .   .   1  .  .   . .  .  .  .  .  .  .   .   .   2  1  .  .
Tram1          .   2  .   2   3   2   .  .  .   . .  .  .  4  1  1  .   .   5   2  1  .  5
Lactb2         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Xkr9           .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Gm5523         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  1  .
Eya1           .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Msc            .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Trpa1          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Kcnb2          .   .  .   .   2   .   .  .  .   . .  .  .  .  .  .  .   1   .   .  .  .  .
Terf1          .   1  .   .   .   .   1  .  .   1 .  .  2  1  .  1  .   1   .   .  .  1  .
Gm106          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
4930444P10Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Rpl7          21  24 26  69  29  43  72  9  9  61 3  9 14 15  7 11 22  10  57  78  6 16 11
Rdh10          .   .  .   5   .   .   2  1  .   . .  .  .  .  .  .  .   3   6   7  .  1  2
Stau2          .   .  .   .   1   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Ube2w          1   .  .   .   .   1   2  .  .   . .  .  .  .  .  .  .   1   .   .  .  .  .
Tceb1          1  13  3   2   7   6   5  .  1   3 .  3  .  1  .  .  .   5  17   .  1  3  2
D030040B21Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Tmem70         .   .  2   .   .   .   .  .  .   1 .  .  1  .  .  .  .   .   .   .  .  .  1
Ly96           .   .  1   1   1   .   1  .  1   . .  .  1  2  .  .  .   1   1   1  .  1  2
Jph1           .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Gdap1          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Pi15           .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Crispld1       .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Crisp4         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Defb44-ps      .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Defb18         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Defb41         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Gm15386        .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Tfap2d         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Tfap2b         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Pkhd1          .   .  .   1   .   .   .  .  1   . 1  .  .  .  .  .  .   .   .   .  .  .  .
4930486I03Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Mir206         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Mir133b        .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Il17a          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Il17f          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Mcm3           .   .  .   .   .   2   .  .  .   . .  .  .  .  .  .  .   2   1   1  .  .  .
6720483E21Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Paqr8          .   .  .   2   .   .   2  .  1   . .  .  .  .  .  .  .   .   .   .  .  .  .
Efhc1          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Tram2          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Tmem14a        .   .  1   .   .   .   1  1  .   . .  .  .  .  .  .  .   .   1   .  .  .  .
Gsta3          .   .  .   .   .   .   7  .  1   3 .  .  .  .  .  .  5   .   .   6  .  .  .
Gm4956         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Khdc1a         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Khdc1c         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Khdc1b         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Kcnq5          .   .  .   .   .   .   .  .  .   . .  .  .  .  1  .  .   .   .   .  .  .  .
Rims1          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
4933415F23Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Mir30a         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Mir30c-2       .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Ogfrl1         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
B3gat2         .   .  .   .   .   .   .  .  .   . .  1  1  .  .  .  .   .   .   .  .  .  1
Smap1          .   1  1   .   2   1   1  1  .   . .  .  .  1  1  .  .   .   3   .  .  1  .
1110058L19Rik  .   2  .   .   2   .   1  .  .   1 .  .  1  .  .  1  .   .   3   1  .  .  .
Fam135a        .   .  .   3   1   1   1  .  .   . .  .  .  .  2  .  .   .   .   .  .  1  1
Col9a1         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Col19a1        .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Lmbrd1         1   .  1   .   .   1   1  .  .   1 .  1  .  2  .  .  .   .   .   2  .  .  .
Bai3           .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Gm20172        .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
4931408C20Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Gm597          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Phf3           .   .  .   1   .   1   .  .  .   . .  .  .  .  .  .  1   1   1   .  .  .  .
Ptp4a1         .   .  2   1   1   .   1  .  1   1 1  .  1  .  .  1  .   1   4   1  .  .  .
Gm13363        .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
4931428L18Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Lgsn           .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
4930521A18Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Gm4850         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Khdrbs2        .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Gm9839         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Gm5415         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Prim2          .   .  .   .   .   .   .  .  .   . .  1  .  .  .  .  .   .   .   .  .  .  .
1700001G17Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Rab23          .   .  1   .   .   .   .  .  .   . .  1  1  2  .  .  .   .   1   .  .  .  .
Bag2           .   .  .   .   .   1   .  .  .   1 .  .  .  .  .  .  .   .   .   .  .  .  .
Zfp451         .   .  .   .   1   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Gm15455        .   .  .   .   .   .   .  .  .   . .  .  .  .  1  .  .   .   .   .  .  .  .
Bend6          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Dst            .   1  .   3   1   .   3  .  .   3 1  1  .  .  .  3  .   3   4   2  .  .  .
Mir5103        .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Ccdc115        .   .  .   .   .   1   1  1  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Imp4           .   .  .   1   .   .   .  .  .   1 .  .  .  1  .  .  .   .   .   2  .  .  .
Ptpn18         .   .  .   .   .   9   .  .  .   . .  .  .  .  .  1  .   .   .   .  .  .  .
Prss39         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Cfc1           .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Prss40         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Fam123c        .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
AA619741       .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Arhgef4        .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  1   .   .   .  .  .  .
Fam168b        .   .  .   1   1   1   2  1  1   . .  .  2  1  .  2  .   1   3   3  1  1  .
Plekhb2        1   .  .   .   .   .   4  .  .   . .  .  .  .  .  .  1   1   1   4  .  .  .
Hs6st1         1   .  .   .   .   .   .  .  .   . .  .  .  .  .  1  .   .   .   .  .  .  1
Uggt1          .   .  .   .   .   .   1  1  .   . 1  .  .  1  .  .  .   .   1   1  1  .  .
Neurl3         .   2  .   .   .   .   .  .  1   . .  2  .  .  1  .  .   1   1   .  .  .  .
Arid5a         .   .  4   .   3   .   .  .  .   . .  .  .  1  1  1  .   .   4   .  2  1  2
4632411B12Rik  .   .  .   .   .   2   1  .  .   . .  .  .  .  .  .  .   .   2   .  .  1  .
Lman2l         .   .  .   .   .   1   2  .  1   . .  .  1  .  .  .  .   .   1   1  .  .  .
Cnnm4          .   .  .   1   .   .   1  .  .   . .  .  1  2  .  .  .   .   .   .  .  .  .
Cnnm3          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   1   .   .  .  .  .
Ankrd23        .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Ankrd39        .   .  .   .   .   .   .  .  .   . .  .  .  .  .  1  .   .   1   1  .  .  .
Sema4c         .   .  .   .   1   .   .  .  .   . 1  .  1  .  .  .  .   .   .   .  .  .  .
Fam178b        .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Cox5b          1   5  6   6   8  12   6  5  .   4 1  3  3  6  2  .  6   1   6   9  1  2  1
Actr1b         .   2  .   .   .   .   .  .  .   . .  .  1  .  .  .  .   .   .   .  .  .  .
4933424G06Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Zap70          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Tmem131        .   .  .   .   .   .   1  .  .   . .  .  .  .  .  .  1   .   1   1  .  .  .
Cnga3          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Inpp4a         1   .  .   .   .   .   .  .  1   1 .  .  1  1  1  .  .   .   2   .  .  .  .
6330578E17Rik  1   .  .   .   .   1   1  .  .   . .  .  .  .  .  .  .   1   .   .  .  .  .
Unc50          .   .  .   .   .   .   3  .  1   1 .  .  2  .  .  1  .   1   2   .  .  .  .
Mgat4a         .   .  .   .   .   .   4  .  1   1 .  .  .  2  .  .  .   .   .   .  .  .  .
4930594C11Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
2010300C02Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Tsga10         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Lipt1          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Mitd1          .   .  .   .   .   .   .  1  .   . .  .  1  .  .  .  .   .   .   1  .  .  .
Mrpl30         1   3  2   1   2   1   4  1  1   3 .  2  3  1  1  .  .   .   1   2  .  1  .
Lyg2           .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Lyg1           .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Txndc9         1   2  .   .   .   1   2  1  .   3 .  .  1  1  1  1  1   .   .   1  .  .  1
Eif5b          1   3  5   2   .   .   1  1  .   1 .  1  1  1  .  1  2   4   5   3  .  2  2
Rev1           .   2  .   .   .   1   .  .  .   . .  .  .  .  .  1  .   .   .   .  .  .  .
Aff3           .   1  .   .   .   .   .  .  .   . .  .  .  .  .  1  .   .   .   .  .  .  .
Lonrf2         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Chst10         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Nms            .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Pdcl3          1   3  2   4   1   1   6  .  2   2 .  .  .  1  .  .  .   .   3   5  .  .  2
Npas2          .   .  .   .   .   .   1  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Rpl31         34  31 27  75  29  37  94  4 13  62 2 12 11 18  8 12 43   5  36 106  3 10 10
Tbc1d8         .   .  .   1   .   .   1  .  .   2 .  .  .  1  .  .  2   1   .   .  .  .  .
D1Bwg0212e     .   1  .   .   .   .   .  .  .   1 .  .  1  .  .  .  .   .   .   .  .  .  .
Snord89        .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Rnf149         .   .  .   .   .   1   3  .  1   2 1  .  .  1  .  .  1   1   1   .  .  2  .
Creg2          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Rfx8           .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Gm3646         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
1700066B17Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Map4k4         .   .  .   1   .   1   3  .  1   2 .  .  .  .  .  1  .   .   1   1  .  .  .
Gm16894        .   .  .   .   .   .   .  .  .   . .  .  .  .  1  .  .   .   .   .  .  .  .
Il1r2          .   .  .   .   .   .   1  .  .   . .  .  .  .  .  .  .   1   .   .  .  .  .
Il1r1          .   .  2   .   .   .   .  .  .   . .  .  .  .  .  1  .   1   2   .  .  .  .
Il1rl2         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Il1rl1         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Il18r1         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Il18rap        .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Slc9a4         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Slc9a2         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Mfsd9          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Tmem182        .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
4930448I06Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
2610017I09Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Pou3f3         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
2900092D14Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Mrps9          .   .  .   1   .   1   .  .  .   . .  .  .  .  1  .  .   .   .   1  .  .  .
Gpr45          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Tgfbrap1       .   .  .   .   .   .   .  .  .   . .  .  .  1  .  .  .   .   .   .  .  .  .
AI597479       1   .  .   .   .   1   .  .  .   1 .  .  .  .  .  .  .   1   .   .  .  .  .
Fhl2           .   1  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   1   .   .  .  .  .
Nck2           .   .  .   .   .   .   1  .  1   . .  .  .  .  .  .  .   .   .   2  .  .  .
1500015O10Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Uxs1           .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   1   .   .  .  .  .
Tpp2           .   .  .   .   .   .   .  .  .   . .  .  1  .  .  .  .   .   2   .  .  .  .
A530098C11Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
1700029F09Rik  .   .  .   1   1   1   1  .  .   . .  .  .  .  .  .  3   1   1   .  .  .  .
Kdelc1         .   .  .   .   .   .   .  .  .   . .  1  .  .  .  .  .   1   2   .  .  .  .
Bivm           .   .  .   .   .   1   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Ercc5          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   1   .  .  .  .
4832428D23Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Gulp1          .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   1   .   .  .  .  .
4930521E06Rik  .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Col3a1        61 115 75   5 124   3   6 36  2   8 2 77 61 61 84 73  2 153 160   5 16 39 57
Col5a2         3   8  5   .   8   .   2  2  .   1 1  1  2  5  6  7  .   9  18   .  3  1  3
Wdr75          1   .  .   .   .   .   .  1  .   . .  .  .  .  .  .  .   .   .   .  .  .  .
Slc40a1        .   .  .   .   .   .   .  .  1   . .  .  .  .  .  .  .   .   .   .  .  .  .
Gm3852         .   .  .   .   .   .   .  .  .   . .  .  .  .  .  .  .   .   .   .  .  .  .

In [6]:
dim(srat[['RNA']]@counts)
dim(srat)
dim(srat@meta.data)

[1] 23341  2500

[1] 23341  2500

[1] 2500   17

In [7]:
if(!paste0("nCount_", default_assay) %in% names(x = srat[[]])) srat[[paste0("nCount_", default_assay)]] <- colSums(x = srat[[default_assay]], slot = "counts")  # nCount of the default assay
if(!paste0("nFeature_", default_assay) %in% names(x = srat[[]])) srat[[paste0("nFeature_", default_assay)]] <- colSums(x = GetAssayData(object = srat[[default_assay]], slot = "counts") > 0)  # nFeature of the default assay

In [28]:
head(srat@meta.data)

                          orig.ident nCount_RNA nFeature_RNA channel  tissue
10X_P4_3_AAAGTAGAGATGCCAG 10X        10291      2853         10X_P4_3 Bladder
10X_P4_3_AACCGCGTCCAACCAA 10X        17520      4194         10X_P4_3 Bladder
10X_P4_3_AACTCCCGTCGGGTCT 10X        12944      3347         10X_P4_3 Bladder
10X_P4_3_AACTCTTAGTTGCAGG 10X        19594      3851         10X_P4_3 Bladder
10X_P4_3_AACTCTTTCATAACCG 10X        14594      3809         10X_P4_3 Bladder
10X_P4_3_AAGACCTAGATCCGAG 10X        19190      3608         10X_P4_3 Bladder
                          subtissue mouse.sex mouse.id percent.ercc
10X_P4_3_AAAGTAGAGATGCCAG           M         3-M-8    0
10X_P4_3_AACCGCGTCCAACCAA           M         3-M-8    0
10X_P4_3_AACTCCCGTCGGGTCT           M         3-M-8    0
10X_P4_3_AACTCTTAGTTGCAGG           M         3-M-8    0
10X_P4_3_AACTCTTTCATAACCG           M         3-M-8    0
10X_P4_3_AAGACCTAGATCCGAG           M         3-M-8    0
                          percent.ribo ⋯ previous_free_annotation
10X_P4_3_AAAGTAGAGATGCCAG 0.2196094    ⋯ NA
10X_P4_3_AACCGCGTCCAACCAA 0.1767123    ⋯ NA
10X_P4_3_AACTCCCGTCGGGTCT 0.1924444    ⋯ NA
10X_P4_3_AACTCTTAGTTGCAGG 0.3563846    ⋯ NA
10X_P4_3_AACTCTTTCATAACCG 0.1571194    ⋯ NA
10X_P4_3_AAGACCTAGATCCGAG 0.2377801    ⋯ NA
                          previous_cell_ontology_class cluster.ids
10X_P4_3_AAAGTAGAGATGCCAG NA                           0
10X_P4_3_AACCGCGTCCAACCAA NA                           2
10X_P4_3_AACTCCCGTCGGGTCT NA                           5
10X_P4_3_AACTCTTAGTTGCAGG NA                           3
10X_P4_3_AACTCTTTCATAACCG NA                           2
10X_P4_3_AAGACCTAGATCCGAG NA                           6
                          cell_ontology_id percent.mt percent.rb percent.hb
10X_P4_3_AAAGTAGAGATGCCAG CL:1001319       0          0          0
10X_P4_3_AACCGCGTCCAACCAA CL:1001319       0          0          0
10X_P4_3_AACTCCCGTCGGGTCT CL:1001319       0          0          0
10X_P4_3_AACTCTTAGTTGCAGG CL:1001428       0          0          0
10X_P4_3_AACTCTTTCATAACCG CL:1001319       0          0          0
10X_P4_3_AAGACCTAGATCCGAG CL:0000738       0          0          0
                          percent.plat Doublet_score Is_doublet
10X_P4_3_AAAGTAGAGATGCCAG 0            NA            FALSE
10X_P4_3_AACCGCGTCCAACCAA 0            NA            FALSE
10X_P4_3_AACTCCCGTCGGGTCT 0            NA            FALSE
10X_P4_3_AACTCTTAGTTGCAGG 0            NA            FALSE
10X_P4_3_AACTCTTTCATAACCG 0            NA            FALSE
10X_P4_3_AAGACCTAGATCCGAG 0            NA            FALSE

In [ ]:
output_path <- '/ps/ai-ready/data/Clustering/Tabula_Muris/droplet_Bladder_seurat_tiss.h5Seurat'
SaveH5Seurat(srat, filename = output_path, overwrite = TRUE, verbose = TRUE)

In [ ]:
srat1 <- LoadH5Seurat(output_path)
srat1

In [ ]:
srat1@meta.data

In [ ]:
adata_path <- Convert('/ps/ai-ready/data/Clustering/Tabula_Muris/droplet_Bladder_seurat_tiss.h5Seurat', dest = "h5ad" , overwrite = TRUE)
adata_path

In [9]:
# Calculate the percentage of mitocondrial per cell and add to the metadata.
if(! "percent.mt" %in% names(x = srat[[]])) srat[["percent.mt"]] <- PercentageFeatureSet(srat, pattern = "^MT-")
# Calculate the proportion gene expression that comes from ribosomal proteins.
if(! "percent.rb" %in% names(x = srat[[]])) srat[["percent.rb"]] <- PercentageFeatureSet(srat, pattern = "^RP[SL]")

# Percentage hemoglobin genes - includes all genes starting with HB except HBP.
if(! "percent.hb" %in% names(x = srat[[]])) srat[["percent.hb"]] <- PercentageFeatureSet(srat, pattern = "^HB[^(P)]")
if(! "percent.plat" %in% names(x = srat[[]])) srat[["percent.plat"]] <- PercentageFeatureSet(srat, pattern = "PECAM1|PF4")
head(srat@meta.data)

                          orig.ident nCount_RNA nFeature_RNA channel  tissue
10X_P4_3_AAAGTAGAGATGCCAG 10X        10291      2853         10X_P4_3 Bladder
10X_P4_3_AACCGCGTCCAACCAA 10X        17520      4194         10X_P4_3 Bladder
10X_P4_3_AACTCCCGTCGGGTCT 10X        12944      3347         10X_P4_3 Bladder
10X_P4_3_AACTCTTAGTTGCAGG 10X        19594      3851         10X_P4_3 Bladder
10X_P4_3_AACTCTTTCATAACCG 10X        14594      3809         10X_P4_3 Bladder
10X_P4_3_AAGACCTAGATCCGAG 10X        19190      3608         10X_P4_3 Bladder
                          subtissue mouse.sex mouse.id percent.ercc
10X_P4_3_AAAGTAGAGATGCCAG           M         3-M-8    0
10X_P4_3_AACCGCGTCCAACCAA           M         3-M-8    0
10X_P4_3_AACTCCCGTCGGGTCT           M         3-M-8    0
10X_P4_3_AACTCTTAGTTGCAGG           M         3-M-8    0
10X_P4_3_AACTCTTTCATAACCG           M         3-M-8    0
10X_P4_3_AAGACCTAGATCCGAG           M         3-M-8    0
                          percent.ribo ⋯ cell_ontology_class     res.0.4
10X_P4_3_AAAGTAGAGATGCCAG 0.2196094    ⋯ bladder cell            0
10X_P4_3_AACCGCGTCCAACCAA 0.1767123    ⋯ bladder cell            2
10X_P4_3_AACTCCCGTCGGGTCT 0.1924444    ⋯ bladder cell            5
10X_P4_3_AACTCTTAGTTGCAGG 0.3563846    ⋯ bladder urothelial cell 3
10X_P4_3_AACTCTTTCATAACCG 0.1571194    ⋯ bladder cell            2
10X_P4_3_AAGACCTAGATCCGAG 0.2377801    ⋯ leukocyte               6
                          previous_free_annotation previous_cell_ontology_class
10X_P4_3_AAAGTAGAGATGCCAG NA                       NA
10X_P4_3_AACCGCGTCCAACCAA NA                       NA
10X_P4_3_AACTCCCGTCGGGTCT NA                       NA
10X_P4_3_AACTCTTAGTTGCAGG NA                       NA
10X_P4_3_AACTCTTTCATAACCG NA                       NA
10X_P4_3_AAGACCTAGATCCGAG NA                       NA
                          cluster.ids cell_ontology_id percent.mt percent.rb
10X_P4_3_AAAGTAGAGATGCCAG 0           CL:1001319       0          0
10X_P4_3_AACCGCGTCCAACCAA 2           CL:1001319       0          0
10X_P4_3_AACTCCCGTCGGGTCT 5           CL:1001319       0          0
10X_P4_3_AACTCTTAGTTGCAGG 3           CL:1001428       0          0
10X_P4_3_AACTCTTTCATAACCG 2           CL:1001319       0          0
10X_P4_3_AAGACCTAGATCCGAG 6           CL:0000738       0          0
                          percent.hb percent.plat
10X_P4_3_AAAGTAGAGATGCCAG 0          0
10X_P4_3_AACCGCGTCCAACCAA 0          0
10X_P4_3_AACTCCCGTCGGGTCT 0          0
10X_P4_3_AACTCTTAGTTGCAGG 0          0
10X_P4_3_AACTCTTTCATAACCG 0          0
10X_P4_3_AAGACCTAGATCCGAG 0          0

In [10]:
# Add the doublet annotation
doublets <- read.table(here::here('api/tools/qc/scrublet_calls.tsv'), header = F, row.names = 1)
colnames(doublets) <- c("Doublet_score", "Is_doublet")
srat <- AddMetaData(srat, doublets)
srat[['Is_doublet']] <- !is.na(srat[['Is_doublet']])

In [11]:
head(srat@meta.data)

                          orig.ident nCount_RNA nFeature_RNA channel  tissue
10X_P4_3_AAAGTAGAGATGCCAG 10X        10291      2853         10X_P4_3 Bladder
10X_P4_3_AACCGCGTCCAACCAA 10X        17520      4194         10X_P4_3 Bladder
10X_P4_3_AACTCCCGTCGGGTCT 10X        12944      3347         10X_P4_3 Bladder
10X_P4_3_AACTCTTAGTTGCAGG 10X        19594      3851         10X_P4_3 Bladder
10X_P4_3_AACTCTTTCATAACCG 10X        14594      3809         10X_P4_3 Bladder
10X_P4_3_AAGACCTAGATCCGAG 10X        19190      3608         10X_P4_3 Bladder
                          subtissue mouse.sex mouse.id percent.ercc
10X_P4_3_AAAGTAGAGATGCCAG           M         3-M-8    0
10X_P4_3_AACCGCGTCCAACCAA           M         3-M-8    0
10X_P4_3_AACTCCCGTCGGGTCT           M         3-M-8    0
10X_P4_3_AACTCTTAGTTGCAGG           M         3-M-8    0
10X_P4_3_AACTCTTTCATAACCG           M         3-M-8    0
10X_P4_3_AAGACCTAGATCCGAG           M         3-M-8    0
                          percent.ribo ⋯ previous_free_annotation
10X_P4_3_AAAGTAGAGATGCCAG 0.2196094    ⋯ NA
10X_P4_3_AACCGCGTCCAACCAA 0.1767123    ⋯ NA
10X_P4_3_AACTCCCGTCGGGTCT 0.1924444    ⋯ NA
10X_P4_3_AACTCTTAGTTGCAGG 0.3563846    ⋯ NA
10X_P4_3_AACTCTTTCATAACCG 0.1571194    ⋯ NA
10X_P4_3_AAGACCTAGATCCGAG 0.2377801    ⋯ NA
                          previous_cell_ontology_class cluster.ids
10X_P4_3_AAAGTAGAGATGCCAG NA                           0
10X_P4_3_AACCGCGTCCAACCAA NA                           2
10X_P4_3_AACTCCCGTCGGGTCT NA                           5
10X_P4_3_AACTCTTAGTTGCAGG NA                           3
10X_P4_3_AACTCTTTCATAACCG NA                           2
10X_P4_3_AAGACCTAGATCCGAG NA                           6
                          cell_ontology_id percent.mt percent.rb percent.hb
10X_P4_3_AAAGTAGAGATGCCAG CL:1001319       0          0          0
10X_P4_3_AACCGCGTCCAACCAA CL:1001319       0          0          0
10X_P4_3_AACTCCCGTCGGGTCT CL:1001319       0          0          0
10X_P4_3_AACTCTTAGTTGCAGG CL:1001428       0          0          0
10X_P4_3_AACTCTTTCATAACCG CL:1001319       0          0          0
10X_P4_3_AAGACCTAGATCCGAG CL:0000738       0          0          0
                          percent.plat Doublet_score Is_doublet
10X_P4_3_AAAGTAGAGATGCCAG 0            NA            FALSE
10X_P4_3_AACCGCGTCCAACCAA 0            NA            FALSE
10X_P4_3_AACTCCCGTCGGGTCT 0            NA            FALSE
10X_P4_3_AACTCTTAGTTGCAGG 0            NA            FALSE
10X_P4_3_AACTCTTTCATAACCG 0            NA            FALSE
10X_P4_3_AAGACCTAGATCCGAG 0            NA            FALSE

In [12]:
srat@meta.data

                          orig.ident nCount_RNA nFeature_RNA channel  tissue
10X_P4_3_AAAGTAGAGATGCCAG 10X        10291      2853         10X_P4_3 Bladder
10X_P4_3_AACCGCGTCCAACCAA 10X        17520      4194         10X_P4_3 Bladder
10X_P4_3_AACTCCCGTCGGGTCT 10X        12944      3347         10X_P4_3 Bladder
10X_P4_3_AACTCTTAGTTGCAGG 10X        19594      3851         10X_P4_3 Bladder
10X_P4_3_AACTCTTTCATAACCG 10X        14594      3809         10X_P4_3 Bladder
10X_P4_3_AAGACCTAGATCCGAG 10X        19190      3608         10X_P4_3 Bladder
10X_P4_3_AAGACCTAGGTGGGTT 10X        24484      4347         10X_P4_3 Bladder
10X_P4_3_AAGGAGCGTGCAACTT 10X         5005      1960         10X_P4_3 Bladder
10X_P4_3_AAGTCTGAGATAGTCA 10X         6253      2236         10X_P4_3 Bladder
10X_P4_3_ACAGCTATCATACGGT 10X        15910      3374         10X_P4_3 Bladder
10X_P4_3_ACATACGCAGCTCCGA 10X         2881      1558         10X_P4_3 Bladder
10X_P4_3_ACCAGTACACGTCTCT 10X         6894      2348         10X_P4_3 Bladder
10X_P4_3_ACGAGCCAGATAGCAT 10X         9658      3141         10X_P4_3 Bladder
10X_P4_3_ACGGAGATCGGAATCT 10X        11623      3357         10X_P4_3 Bladder
10X_P4_3_ACGGGCTGTCTGATCA 10X         6878      2285         10X_P4_3 Bladder
10X_P4_3_ACTGAACCATCCGGGT 10X         7428      2319         10X_P4_3 Bladder
10X_P4_3_ACTTTCAAGATGGGTC 10X        10302      2875         10X_P4_3 Bladder
10X_P4_3_AGACGTTTCTTACCGC 10X        10187      3197         10X_P4_3 Bladder
10X_P4_3_AGAGCTTTCTGTTGAG 10X        25039      4812         10X_P4_3 Bladder
10X_P4_3_AGCGGTCTCTGAGTGT 10X        23497      4152         10X_P4_3 Bladder
10X_P4_3_AGCTTGAAGACTAAGT 10X         3102      1431         10X_P4_3 Bladder
10X_P4_3_AGGGAGTCAATCGGTT 10X         6981      2323         10X_P4_3 Bladder
10X_P4_3_AGGGATGAGTCGCCGT 10X         5259      1975         10X_P4_3 Bladder
10X_P4_3_AGGGTGACAGTCGTGC 10X        11231      3314         10X_P4_3 Bladder
10X_P4_3_AGGTCCGAGGACACCA 10X        26565      5040         10X_P4_3 Bladder
10X_P4_3_AGTCTTTAGCTAGTGG 10X         2277      1098         10X_P4_3 Bladder
10X_P4_3_AGTGAGGAGTGTACTC 10X         4800      1888         10X_P4_3 Bladder
10X_P4_3_AGTGAGGTCAGCATGT 10X        19882      3884         10X_P4_3 Bladder
10X_P4_3_AGTGTCACAGTATCTG 10X         6171      2299         10X_P4_3 Bladder
10X_P4_3_ATCACGACAACAACCT 10X        14113      3699         10X_P4_3 Bladder
⋮                         ⋮          ⋮          ⋮            ⋮        ⋮
10X_P7_7_TGTTCCGAGCTAACTC 10X        23228      4255         10X_P7_7 Bladder
10X_P7_7_TGTTCCGAGCTCCCAG 10X        42860      5745         10X_P7_7 Bladder
10X_P7_7_TTAACTCGTCTCTTTA 10X        35751      5422         10X_P7_7 Bladder
10X_P7_7_TTAACTCTCAGAGACG 10X        31618      4440         10X_P7_7 Bladder
10X_P7_7_TTAGGACAGACAAAGG 10X         9988      3201         10X_P7_7 Bladder
10X_P7_7_TTAGGACCAGGGTACA 10X        11756      2880         10X_P7_7 Bladder
10X_P7_7_TTAGGACGTCTCCCTA 10X         8516      2732         10X_P7_7 Bladder
10X_P7_7_TTATGCTAGCCATCGC 10X        14870      3657         10X_P7_7 Bladder
10X_P7_7_TTATGCTCAGATGAGC 10X        16126      3372         10X_P7_7 Bladder
10X_P7_7_TTATGCTCAGCGTTCG 10X         4938      1528         10X_P7_7 Bladder
10X_P7_7_TTATGCTTCCGAACGC 10X        11558      2319         10X_P7_7 Bladder
10X_P7_7_TTATGCTTCCGCGGTA 10X         6376      2580         10X_P7_7 Bladder
10X_P7_7_TTCCCAGTCATGTGGT 10X        34918      5002         10X_P7_7 Bladder
10X_P7_7_TTCGGTCAGTGCGTGA 10X        14304      3511         10X_P7_7 Bladder
10X_P7_7_TTCGGTCCAGCGTAAG 10X        22793      4562         10X_P7_7 Bladder
10X_P7_7_TTCGGTCTCCGGGTGT 10X         8380      2764         10X_P7_7 Bladder
10X_P7_7_TTCTCAAAGAGCCCAA 10X        37286      5356         10X_P7_7 Bladder
10X_P7_7_TTCTCAACAAACGTGG 10X        14565      3769         10X_P7_7 Bladder
10X_P7_7_TTGAACGAGATGTCGG 10X         9558      2972         10X_P7_7 Bladder
10X_P7_7_TTGCGTCCAAAGTGCG 10X        11456      3241         10X_P7_7 Bladder
10X_P7_7_TTGCGTCGTAGGACAC 10X        21269      3633         10X_P7_7 Bladder
10X_P7_7_TTGGAACAGTAGATGT 10X         8974      2831         10X_P7_7 Bladder
10X_P7_7_TTGGAACGTCTAGTCA 10X         6607      2546         10X_P7_7 Bladder
10X_P7_7_TTGGAACGTGTCGCTG 10X        50069      5641         10X_P7_7 Bladder
10X_P7_7_TTGTAGGCACTTGGAT 10X         9666      3087         10X_P7_7 Bladder
10X_P7_7_TTGTAGGTCATGTAGC 10X        22993      4296         10X_P7_7 Bladder
10X_P7_7_TTTACTGGTGTTGAGG 10X         8753      3005         10X_P7_7 Bladder
10X_P7_7_TTTCCTCCATACCATG 10X        14665      3778         10X_P7_7 Bladder
10X_P7_7_TTTGTCAGTTACCGAT 10X        30363      4786         10X_P7_7 Bladder
10X_P7_7_TTTGTCATCTGTGCAA 10X        16524      3979         10X_P7_7 Bladder
                          subtissue mouse.sex mouse.id percent.ercc
10X_P4_3_AAAGTAGAGATGCCAG           M         3-M-8    0
10X_P4_3_AACCGCGTCCAACCAA           M         3-M-8    0
10X_P4_3_AACTCCCGTCGGGTCT           M         3-M-8    0
10X_P4_3_AACTCTTAGTTGCAGG           M         3-M-8    0
10X_P4_3_AACTCTTTCATAACCG           M         3-M-8    0
10X_P4_3_AAGACCTAGATCCGAG           M         3-M-8    0
10X_P4_3_AAGACCTAGGTGGGTT           M         3-M-8    0
10X_P4_3_AAGGAGCGTGCAACTT           M         3-M-8    0
10X_P4_3_AAGTCTGAGATAGTCA           M         3-M-8    0
10X_P4_3_ACAGCTATCATACGGT           M         3-M-8    0
10X_P4_3_ACATACGCAGCTCCGA           M         3-M-8    0
10X_P4_3_ACCAGTACACGTCTCT           M         3-M-8    0
10X_P4_3_ACGAGCCAGATAGCAT           M         3-M-8    0
10X_P4_3_ACGGAGATCGGAATCT           M         3-M-8    0
10X_P4_3_ACGGGCTGTCTGATCA           M         3-M-8    0
10X_P4_3_ACTGAACCATCCGGGT           M         3-M-8    0
10X_P4_3_ACTTTCAAGATGGGTC           M         3-M-8    0
10X_P4_3_AGACGTTTCTTACCGC           M         3-M-8    0
10X_P4_3_AGAGCTTTCTGTTGAG           M         3-M-8    0
10X_P4_3_AGCGGTCTCTGAGTGT           M         3-M-8    0
10X_P4_3_AGCTTGAAGACTAAGT           M         3-M-8    0
10X_P4_3_AGGGAGTCAATCGGTT           M         3-M-8    0
10X_P4_3_AGGGATGAGTCGCCGT           M         3-M-8    0
10X_P4_3_AGGGTGACAGTCGTGC           M         3-M-8    0
10X_P4_3_AGGTCCGAGGACACCA           M         3-M-8    0
10X_P4_3_AGTCTTTAGCTAGTGG           M         3-M-8    0
10X_P4_3_AGTGAGGAGTGTACTC           M         3-M-8    0
10X_P4_3_AGTGAGGTCAGCATGT           M         3-M-8    0
10X_P4_3_AGTGTCACAGTATCTG           M         3-M-8    0
10X_P4_3_ATCACGACAACAACCT           M         3-M-8    0
⋮                         ⋮         ⋮         ⋮        ⋮
10X_P7_7_TGTTCCGAGCTAACTC           F         3-F-56   0
10X_P7_7_TGTTCCGAGCTCCCAG           F         3-F-56   0
10X_P7_7_TTAACTCGTCTCTTTA           F         3-F-56   0
10X_P7_7_TTAACTCTCAGAGACG           F         3-F-56   0
10X_P7_7_TTAGGACAGACAAAGG           F         3-F-56   0
10X_P7_7_TTAGGACCAGGGTACA           F         3-F-56   0
10X_P7_7_TTAGGACGTCTCCCTA           F         3-F-56   0
10X_P7_7_TTATGCTAGCCATCGC           F         3-F-56   0
10X_P7_7_TTATGCTCAGATGAGC           F         3-F-56   0
10X_P7_7_TTATGCTCAGCGTTCG           F         3-F-56   0
10X_P7_7_TTATGCTTCCGAACGC           F         3-F-56   0
10X_P7_7_TTATGCTTCCGCGGTA           F         3-F-56   0
10X_P7_7_TTCCCAGTCATGTGGT           F         3-F-56   0
10X_P7_7_TTCGGTCAGTGCGTGA           F         3-F-56   0
10X_P7_7_TTCGGTCCAGCGTAAG           F         3-F-56   0
10X_P7_7_TTCGGTCTCCGGGTGT           F         3-F-56   0
10X_P7_7_TTCTCAAAGAGCCCAA           F         3-F-56   0
10X_P7_7_TTCTCAACAAACGTGG           F         3-F-56   0
10X_P7_7_TTGAACGAGATGTCGG           F         3-F-56   0
10X_P7_7_TTGCGTCCAAAGTGCG           F         3-F-56   0
10X_P7_7_TTGCGTCGTAGGACAC           F         3-F-56   0
10X_P7_7_TTGGAACAGTAGATGT           F         3-F-56   0
10X_P7_7_TTGGAACGTCTAGTCA           F         3-F-56   0
10X_P7_7_TTGGAACGTGTCGCTG           F         3-F-56   0
10X_P7_7_TTGTAGGCACTTGGAT           F         3-F-56   0
10X_P7_7_TTGTAGGTCATGTAGC           F         3-F-56   0
10X_P7_7_TTTACTGGTGTTGAGG           F         3-F-56   0
10X_P7_7_TTTCCTCCATACCATG           F         3-F-56   0
10X_P7_7_TTTGTCAGTTACCGAT           F         3-F-56   0
10X_P7_7_TTTGTCATCTGTGCAA           F         3-F-56   0
                          percent.ribo ⋯ previous_free_annotation
10X_P4_3_AAAGTAGAGATGCCAG 0.21960937   ⋯ NA
10X_P4_3_AACCGCGTCCAACCAA 0.17671233   ⋯ NA
10X_P4_3_AACTCCCGTCGGGTCT 0.19244438   ⋯ NA
10X_P4_3_AACTCTTAGTTGCAGG 0.35638461   ⋯ NA
10X_P4_3_AACTCTTTCATAACCG 0.15711936   ⋯ NA
10X_P4_3_AAGACCTAGATCCGAG 0.23778009   ⋯ NA
10X_P4_3_AAGACCTAGGTGGGTT 0.32809182   ⋯ NA
10X_P4_3_AAGGAGCGTGCAACTT 0.19020979   ⋯ NA
10X_P4_3_AAGTCTGAGATAGTCA 0.22597153   ⋯ NA
10X_P4_3_ACAGCTATCATACGGT 0.33777498   ⋯ NA
10X_P4_3_ACATACGCAGCTCCGA 0.13259285   ⋯ NA
10X_P4_3_ACCAGTACACGTCTCT 0.20075428   ⋯ NA
10X_P4_3_ACGAGCCAGATAGCAT 0.16328432   ⋯ NA
10X_P4_3_ACGGAGATCGGAATCT 0.15701626   ⋯ NA
10X_P4_3_ACGGGCTGTCTGATCA 0.17214306   ⋯ NA
10X_P4_3_ACTGAACCATCCGGGT 0.17514809   ⋯ NA
10X_P4_3_ACTTTCAAGATGGGTC 0.31819064   ⋯ NA
10X_P4_3_AGACGTTTCTTACCGC 0.09207814   ⋯ NA
10X_P4_3_AGAGCTTTCTGTTGAG 0.18882543   ⋯ NA
10X_P4_3_AGCGGTCTCTGAGTGT 0.36498276   ⋯ NA
10X_P4_3_AGCTTGAAGACTAAGT 0.12250161   ⋯ NA
10X_P4_3_AGGGAGTCAATCGGTT 0.20369575   ⋯ NA
10X_P4_3_AGGGATGAGTCGCCGT 0.16600114   ⋯ NA
10X_P4_3_AGGGTGACAGTCGTGC 0.16222954   ⋯ NA
10X_P4_3_AGGTCCGAGGACACCA 0.27174854   ⋯ NA
10X_P4_3_AGTCTTTAGCTAGTGG 0.16161616   ⋯ NA
10X_P4_3_AGTGAGGAGTGTACTC 0.13708333   ⋯ NA
10X_P4_3_AGTGAGGTCAGCATGT 0.31520974   ⋯ NA
10X_P4_3_AGTGTCACAGTATCTG 0.11181332   ⋯ NA
10X_P4_3_ATCACGACAACAACCT 0.14065046   ⋯ NA
⋮                         ⋮            ⋱ ⋮
10X_P7_7_TGTTCCGAGCTAACTC 0.34092475   ⋯ NA
10X_P7_7_TGTTCCGAGCTCCCAG 0.37134858   ⋯ NA
10X_P7_7_TTAACTCGTCTCTTTA 0.24913988   ⋯ NA
10X_P7_7_TTAACTCTCAGAGACG 0.34100829   ⋯ NA
10X_P7_7_TTAGGACAGACAAAGG 0.14717661   ⋯ NA
10X_P7_7_TTAGGACCAGGGTACA 0.31405240   ⋯ NA
10X_P7_7_TTAGGACGTCTCCCTA 0.14560827   ⋯ NA
10X_P7_7_TTATGCTAGCCATCGC 0.32313383   ⋯ NA
10X_P7_7_TTATGCTCAGATGAGC 0.26851048   ⋯ NA
10X_P7_7_TTATGCTCAGCGTTCG 0.04597003   ⋯ NA
10X_P7_7_TTATGCTTCCGAACGC 0.11792698   ⋯ NA
10X_P7_7_TTATGCTTCCGCGGTA 0.12531368   ⋯ NA
10X_P7_7_TTCCCAGTCATGTGGT 0.29950169   ⋯ NA
10X_P7_7_TTCGGTCAGTGCGTGA 0.16072427   ⋯ NA
10X_P7_7_TTCGGTCCAGCGTAAG 0.24985741   ⋯ NA
10X_P7_7_TTCGGTCTCCGGGTGT 0.14439141   ⋯ NA
10X_P7_7_TTCTCAAAGAGCCCAA 0.36834201   ⋯ NA
10X_P7_7_TTCTCAACAAACGTGG 0.11342259   ⋯ NA
10X_P7_7_TTGAACGAGATGTCGG 0.16970077   ⋯ NA
10X_P7_7_TTGCGTCCAAAGTGCG 0.16096369   ⋯ NA
10X_P7_7_TTGCGTCGTAGGACAC 0.34331656   ⋯ NA
10X_P7_7_TTGGAACAGTAGATGT 0.13527970   ⋯ NA
10X_P7_7_TTGGAACGTCTAGTCA 0.13319207   ⋯ NA
10X_P7_7_TTGGAACGTGTCGCTG 0.40040744   ⋯ NA
10X_P7_7_TTGTAGGCACTTGGAT 0.10862818   ⋯ NA
10X_P7_7_TTGTAGGTCATGTAGC 0.28678293   ⋯ NA
10X_P7_7_TTTACTGGTGTTGAGG 0.12087284   ⋯ NA
10X_P7_7_TTTCCTCCATACCATG 0.11817252   ⋯ NA
10X_P7_7_TTTGTCAGTTACCGAT 0.30701841   ⋯ NA
10X_P7_7_TTTGTCATCTGTGCAA 0.29950375   ⋯ NA
                          previous_cell_ontology_class cluster.ids
10X_P4_3_AAAGTAGAGATGCCAG NA                           0
10X_P4_3_AACCGCGTCCAACCAA NA                           2
10X_P4_3_AACTCCCGTCGGGTCT NA                           5
10X_P4_3_AACTCTTAGTTGCAGG NA                           3
10X_P4_3_AACTCTTTCATAACCG NA                           2
10X_P4_3_AAGACCTAGATCCGAG NA                           6
10X_P4_3_AAGACCTAGGTGGGTT NA                           1
10X_P4_3_AAGGAGCGTGCAACTT NA                           0
10X_P4_3_AAGTCTGAGATAGTCA NA                           4
10X_P4_3_ACAGCTATCATACGGT NA                           1
10X_P4_3_ACATACGCAGCTCCGA NA                           4
10X_P4_3_ACCAGTACACGTCTCT NA                           0
10X_P4_3_ACGAGCCAGATAGCAT NA                           0
10X_P4_3_ACGGAGATCGGAATCT NA                           2
10X_P4_3_ACGGGCTGTCTGATCA NA                           0
10X_P4_3_ACTGAACCATCCGGGT NA                           0
10X_P4_3_ACTTTCAAGATGGGTC NA                           1
10X_P4_3_AGACGTTTCTTACCGC NA                           5
10X_P4_3_AGAGCTTTCTGTTGAG NA                           2
10X_P4_3_AGCGGTCTCTGAGTGT NA                           1
10X_P4_3_AGCTTGAAGACTAAGT NA                           0
10X_P4_3_AGGGAGTCAATCGGTT NA                           0
10X_P4_3_AGGGATGAGTCGCCGT NA                           0
10X_P4_3_AGGGTGACAGTCGTGC NA                           0
10X_P4_3_AGGTCCGAGGACACCA NA                           1
10X_P4_3_AGTCTTTAGCTAGTGG NA                           0
10X_P4_3_AGTGAGGAGTGTACTC NA                           0
10X_P4_3_AGTGAGGTCAGCATGT NA                           1
10X_P4_3_AGTGTCACAGTATCTG NA                           5
10X_P4_3_ATCACGACAACAACCT NA                           2
⋮                         ⋮                            ⋮
10X_P7_7_TGTTCCGAGCTAACTC NA                           1
10X_P7_7_TGTTCCGAGCTCCCAG NA                           1
10X_P7_7_TTAACTCGTCTCTTTA NA                           1
10X_P7_7_TTAACTCTCAGAGACG NA                           4
10X_P7_7_TTAGGACAGACAAAGG NA                           5
10X_P7_7_TTAGGACCAGGGTACA NA                           1
10X_P7_7_TTAGGACGTCTCCCTA NA                           5
10X_P7_7_TTATGCTAGCCATCGC NA                           1
10X_P7_7_TTATGCTCAGATGAGC NA                           4
10X_P7_7_TTATGCTCAGCGTTCG NA                           6
10X_P7_7_TTATGCTTCCGAACGC NA                           6
10X_P7_7_TTATGCTTCCGCGGTA NA                           0
10X_P7_7_TTCCCAGTCATGTGGT NA                           1
10X_P7_7_TTCGGTCAGTGCGTGA NA                           5
10X_P7_7_TTCGGTCCAGCGTAAG NA                           1
10X_P7_7_TTCGGTCTCCGGGTGT NA                           5
10X_P7_7_TTCTCAAAGAGCCCAA NA                           1
10X_P7_7_TTCTCAACAAACGTGG NA                           5
10X_P7_7_TTGAACGAGATGTCGG NA                           5
10X_P7_7_TTGCGTCCAAAGTGCG NA                           5
10X_P7_7_TTGCGTCGTAGGACAC NA                           1
10X_P7_7_TTGGAACAGTAGATGT NA                           5
10X_P7_7_TTGGAACGTCTAGTCA NA                           0
10X_P7_7_TTGGAACGTGTCGCTG NA                           4
10X_P7_7_TTGTAGGCACTTGGAT NA                           7
10X_P7_7_TTGTAGGTCATGTAGC NA                           1
10X_P7_7_TTTACTGGTGTTGAGG NA                           5
10X_P7_7_TTTCCTCCATACCATG NA                           5
10X_P7_7_TTTGTCAGTTACCGAT NA                           1
10X_P7_7_TTTGTCATCTGTGCAA NA                           1
                          cell_ontology_id percent.mt percent.rb percent.hb
10X_P4_3_AAAGTAGAGATGCCAG CL:1001319       0          0          0
10X_P4_3_AACCGCGTCCAACCAA CL:1001319       0          0          0
10X_P4_3_AACTCCCGTCGGGTCT CL:1001319       0          0          0
10X_P4_3_AACTCTTAGTTGCAGG CL:1001428       0          0          0
10X_P4_3_AACTCTTTCATAACCG CL:1001319       0          0          0
10X_P4_3_AAGACCTAGATCCGAG CL:0000738       0          0          0
10X_P4_3_AAGACCTAGGTGGGTT CL:1001428       0          0          0
10X_P4_3_AAGGAGCGTGCAACTT CL:1001319       0          0          0
10X_P4_3_AAGTCTGAGATAGTCA CL:1001428       0          0          0
10X_P4_3_ACAGCTATCATACGGT CL:1001428       0          0          0
10X_P4_3_ACATACGCAGCTCCGA CL:1001428       0          0          0
10X_P4_3_ACCAGTACACGTCTCT CL:1001319       0          0          0
10X_P4_3_ACGAGCCAGATAGCAT CL:1001319       0          0          0
10X_P4_3_ACGGAGATCGGAATCT CL:1001319       0          0          0
10X_P4_3_ACGGGCTGTCTGATCA CL:1001319       0          0          0
10X_P4_3_ACTGAACCATCCGGGT CL:1001319       0          0          0
10X_P4_3_ACTTTCAAGATGGGTC CL:1001428       0          0          0
10X_P4_3_AGACGTTTCTTACCGC CL:1001319       0          0          0
10X_P4_3_AGAGCTTTCTGTTGAG CL:1001319       0          0          0
10X_P4_3_AGCGGTCTCTGAGTGT CL:1001428       0          0          0
10X_P4_3_AGCTTGAAGACTAAGT CL:1001319       0          0          0
10X_P4_3_AGGGAGTCAATCGGTT CL:1001319       0          0          0
10X_P4_3_AGGGATGAGTCGCCGT CL:1001319       0          0          0
10X_P4_3_AGGGTGACAGTCGTGC CL:1001319       0          0          0
10X_P4_3_AGGTCCGAGGACACCA CL:1001428       0          0          0
10X_P4_3_AGTCTTTAGCTAGTGG CL:1001319       0          0          0
10X_P4_3_AGTGAGGAGTGTACTC CL:1001319       0          0          0
10X_P4_3_AGTGAGGTCAGCATGT CL:1001428       0          0          0
10X_P4_3_AGTGTCACAGTATCTG CL:1001319       0          0          0
10X_P4_3_ATCACGACAACAACCT CL:1001319       0          0          0
⋮                         ⋮                ⋮          ⋮          ⋮
10X_P7_7_TGTTCCGAGCTAACTC CL:1001428       0          0          0
10X_P7_7_TGTTCCGAGCTCCCAG CL:1001428       0          0          0
10X_P7_7_TTAACTCGTCTCTTTA CL:1001428       0          0          0
10X_P7_7_TTAACTCTCAGAGACG CL:1001428       0          0          0
10X_P7_7_TTAGGACAGACAAAGG CL:1001319       0          0          0
10X_P7_7_TTAGGACCAGGGTACA CL:1001428       0          0          0
10X_P7_7_TTAGGACGTCTCCCTA CL:1001319       0          0          0
10X_P7_7_TTATGCTAGCCATCGC CL:1001428       0          0          0
10X_P7_7_TTATGCTCAGATGAGC CL:1001428       0          0          0
10X_P7_7_TTATGCTCAGCGTTCG CL:0000738       0          0          0
10X_P7_7_TTATGCTTCCGAACGC CL:0000738       0          0          0
10X_P7_7_TTATGCTTCCGCGGTA CL:1001319       0          0          0
10X_P7_7_TTCCCAGTCATGTGGT CL:1001428       0          0          0
10X_P7_7_TTCGGTCAGTGCGTGA CL:1001319       0          0          0
10X_P7_7_TTCGGTCCAGCGTAAG CL:1001428       0          0          0
10X_P7_7_TTCGGTCTCCGGGTGT CL:1001319       0          0          0
10X_P7_7_TTCTCAAAGAGCCCAA CL:1001428       0          0          0
10X_P7_7_TTCTCAACAAACGTGG CL:1001319       0          0          0
10X_P7_7_TTGAACGAGATGTCGG CL:1001319       0          0          0
10X_P7_7_TTGCGTCCAAAGTGCG CL:1001319       0          0          0
10X_P7_7_TTGCGTCGTAGGACAC CL:1001428       0          0          0
10X_P7_7_TTGGAACAGTAGATGT CL:1001319       0          0          0
10X_P7_7_TTGGAACGTCTAGTCA CL:1001319       0          0          0
10X_P7_7_TTGGAACGTGTCGCTG CL:1001428       0          0          0
10X_P7_7_TTGTAGGCACTTGGAT CL:0000115       0          0          0
10X_P7_7_TTGTAGGTCATGTAGC CL:1001428       0          0          0
10X_P7_7_TTTACTGGTGTTGAGG CL:1001319       0          0          0
10X_P7_7_TTTCCTCCATACCATG CL:1001319       0          0          0
10X_P7_7_TTTGTCAGTTACCGAT CL:1001428       0          0          0
10X_P7_7_TTTGTCATCTGTGCAA CL:1001428       0          0          0
                          percent.plat Doublet_score Is_doublet
10X_P4_3_AAAGTAGAGATGCCAG 0            NA            FALSE
10X_P4_3_AACCGCGTCCAACCAA 0            NA            FALSE
10X_P4_3_AACTCCCGTCGGGTCT 0            NA            FALSE
10X_P4_3_AACTCTTAGTTGCAGG 0            NA            FALSE
10X_P4_3_AACTCTTTCATAACCG 0            NA            FALSE
10X_P4_3_AAGACCTAGATCCGAG 0            NA            FALSE
10X_P4_3_AAGACCTAGGTGGGTT 0            NA            FALSE
10X_P4_3_AAGGAGCGTGCAACTT 0            NA            FALSE
10X_P4_3_AAGTCTGAGATAGTCA 0            NA            FALSE
10X_P4_3_ACAGCTATCATACGGT 0            NA            FALSE
10X_P4_3_ACATACGCAGCTCCGA 0            NA            FALSE
10X_P4_3_ACCAGTACACGTCTCT 0            NA            FALSE
10X_P4_3_ACGAGCCAGATAGCAT 0            NA            FALSE
10X_P4_3_ACGGAGATCGGAATCT 0            NA            FALSE
10X_P4_3_ACGGGCTGTCTGATCA 0            NA            FALSE
10X_P4_3_ACTGAACCATCCGGGT 0            NA            FALSE
10X_P4_3_ACTTTCAAGATGGGTC 0            NA            FALSE
10X_P4_3_AGACGTTTCTTACCGC 0            NA            FALSE

In [14]:
nFeature_min=200
nFeature_max=0
percent_mt_max=5
percent_rb_min=0
srat <- subset(srat, subset = paste0("nFeature_", default_assay) > nFeature_min & percent.mt < percent_mt_max)
if(nFeature_max != 0) srat <- subset(srat, subset = paste0("nFeature_", default_assay) < nFeature_max)
if(percent_rb_min != 0)  srat <- subset(srat, subset = percent.rb > percent_rb_min)

In [46]:
#' Regularise dataframe
#'
#' This function checks if certain columns of a dataframe is of a single value
#' and drop them if required
#'
#' @param df Input data frame, usually cell metadata table (data.frame-like
#'   object)
#' @param drop_single_values Drop columns with only a single value (logical)
#'
#' @return Dataframe
.regularise_df <- function(df, drop_single_values=FALSE, drop_na_values=TRUE) {
  if (ncol(df) == 0) df[["name"]] <- rownames(df)
  if (drop_single_values) {
    k_singular <- sapply(df, function(x) length(unique(x)) == 1)
    if (sum(k_singular) > 0) {
      warning(
        paste("Dropping single category variables:"),
        paste(colnames(df)[k_singular], collapse = ", ")
      )
    }
    df <- df[, !k_singular, drop = F]
    if (ncol(df) == 0) df[["name"]] <- rownames(df)
  }
 if (drop_na_values) {
    k_na <- sapply(df, function(x) length(is.na(x)) == 1)
    if (sum(k_na) > 0) {
      warning(
        paste("Dropping NA category variables:"),
        paste(colnames(df)[k_na], collapse = ", ")
      )
    }
    df <- df[, !k_na, drop = F]
    if (ncol(df) == 0) df[["name"]] <- rownames(df)
  }
  return(df)
}

In [17]:
output_path_rds <- '/ps/ai-ready/data/Clustering/Tabula_Muris/droplet_Bladder_seurat_tiss.rds'
saveRDS(srat, output_path_rds)
srat1 <- LoadSeurat(output_path_rds)
srat1

In [49]:
k_na <- sapply(srat_qc@meta.data, function(x) length(is.na(x)) == 1)
k_na

                  orig.ident                   nCount_RNA
                       FALSE                        FALSE
                nFeature_RNA                      channel
                       FALSE                        FALSE
                      tissue                    subtissue
                       FALSE                        FALSE
                   mouse.sex                     mouse.id
                       FALSE                        FALSE
                percent.ercc                 percent.ribo
                       FALSE                        FALSE
             free_annotation          cell_ontology_class
                       FALSE                        FALSE
                     res.0.4     previous_free_annotation
                       FALSE                        FALSE
previous_cell_ontology_class                  cluster.ids
                       FALSE                        FALSE
            cell_ontology_id                   percent.mt
                       FALSE                        FALSE
                  percent.rb                   percent.hb
                       FALSE                        FALSE
                percent.plat                Doublet_score
                       FALSE                        FALSE
                  Is_doublet
                       FALSE

In [51]:
k_singular <- sapply(srat_qc@meta.data, function(x) length(unique(x)) == 1)
k_singular

                  orig.ident                   nCount_RNA
                        TRUE                        FALSE
                nFeature_RNA                      channel
                       FALSE                        FALSE
                      tissue                    subtissue
                        TRUE                         TRUE
                   mouse.sex                     mouse.id
                       FALSE                        FALSE
                percent.ercc                 percent.ribo
                        TRUE                        FALSE
             free_annotation          cell_ontology_class
                       FALSE                        FALSE
                     res.0.4     previous_free_annotation
                       FALSE                         TRUE
previous_cell_ontology_class                  cluster.ids
                        TRUE                        FALSE
            cell_ontology_id                   percent.mt
                       FALSE                         TRUE
                  percent.rb                   percent.hb
                        TRUE                         TRUE
                percent.plat                Doublet_score
                        TRUE                         TRUE
                  Is_doublet
                        TRUE

In [44]:
srat_qc@meta.data

                          orig.ident nCount_RNA nFeature_RNA channel  tissue
10X_P4_3_AAAGTAGAGATGCCAG 10X        10291      2853         10X_P4_3 Bladder
10X_P4_3_AACCGCGTCCAACCAA 10X        17520      4194         10X_P4_3 Bladder
10X_P4_3_AACTCCCGTCGGGTCT 10X        12944      3347         10X_P4_3 Bladder
10X_P4_3_AACTCTTAGTTGCAGG 10X        19594      3851         10X_P4_3 Bladder
10X_P4_3_AACTCTTTCATAACCG 10X        14594      3809         10X_P4_3 Bladder
10X_P4_3_AAGACCTAGATCCGAG 10X        19190      3608         10X_P4_3 Bladder
10X_P4_3_AAGACCTAGGTGGGTT 10X        24484      4347         10X_P4_3 Bladder
10X_P4_3_AAGGAGCGTGCAACTT 10X         5005      1960         10X_P4_3 Bladder
10X_P4_3_AAGTCTGAGATAGTCA 10X         6253      2236         10X_P4_3 Bladder
10X_P4_3_ACAGCTATCATACGGT 10X        15910      3374         10X_P4_3 Bladder
10X_P4_3_ACATACGCAGCTCCGA 10X         2881      1558         10X_P4_3 Bladder
10X_P4_3_ACCAGTACACGTCTCT 10X         6894      2348         10X_P4_3 Bladder
10X_P4_3_ACGAGCCAGATAGCAT 10X         9658      3141         10X_P4_3 Bladder
10X_P4_3_ACGGAGATCGGAATCT 10X        11623      3357         10X_P4_3 Bladder
10X_P4_3_ACGGGCTGTCTGATCA 10X         6878      2285         10X_P4_3 Bladder
10X_P4_3_ACTGAACCATCCGGGT 10X         7428      2319         10X_P4_3 Bladder
10X_P4_3_ACTTTCAAGATGGGTC 10X        10302      2875         10X_P4_3 Bladder
10X_P4_3_AGACGTTTCTTACCGC 10X        10187      3197         10X_P4_3 Bladder
10X_P4_3_AGAGCTTTCTGTTGAG 10X        25039      4812         10X_P4_3 Bladder
10X_P4_3_AGCGGTCTCTGAGTGT 10X        23497      4152         10X_P4_3 Bladder
10X_P4_3_AGCTTGAAGACTAAGT 10X         3102      1431         10X_P4_3 Bladder
10X_P4_3_AGGGAGTCAATCGGTT 10X         6981      2323         10X_P4_3 Bladder
10X_P4_3_AGGGATGAGTCGCCGT 10X         5259      1975         10X_P4_3 Bladder
10X_P4_3_AGGGTGACAGTCGTGC 10X        11231      3314         10X_P4_3 Bladder
10X_P4_3_AGGTCCGAGGACACCA 10X        26565      5040         10X_P4_3 Bladder
10X_P4_3_AGTCTTTAGCTAGTGG 10X         2277      1098         10X_P4_3 Bladder
10X_P4_3_AGTGAGGAGTGTACTC 10X         4800      1888         10X_P4_3 Bladder
10X_P4_3_AGTGAGGTCAGCATGT 10X        19882      3884         10X_P4_3 Bladder
10X_P4_3_AGTGTCACAGTATCTG 10X         6171      2299         10X_P4_3 Bladder
10X_P4_3_ATCACGACAACAACCT 10X        14113      3699         10X_P4_3 Bladder
⋮                         ⋮          ⋮          ⋮            ⋮        ⋮
10X_P7_7_TGTTCCGAGCTAACTC 10X        23228      4255         10X_P7_7 Bladder
10X_P7_7_TGTTCCGAGCTCCCAG 10X        42860      5745         10X_P7_7 Bladder
10X_P7_7_TTAACTCGTCTCTTTA 10X        35751      5422         10X_P7_7 Bladder
10X_P7_7_TTAACTCTCAGAGACG 10X        31618      4440         10X_P7_7 Bladder
10X_P7_7_TTAGGACAGACAAAGG 10X         9988      3201         10X_P7_7 Bladder
10X_P7_7_TTAGGACCAGGGTACA 10X        11756      2880         10X_P7_7 Bladder
10X_P7_7_TTAGGACGTCTCCCTA 10X         8516      2732         10X_P7_7 Bladder
10X_P7_7_TTATGCTAGCCATCGC 10X        14870      3657         10X_P7_7 Bladder
10X_P7_7_TTATGCTCAGATGAGC 10X        16126      3372         10X_P7_7 Bladder
10X_P7_7_TTATGCTCAGCGTTCG 10X         4938      1528         10X_P7_7 Bladder
10X_P7_7_TTATGCTTCCGAACGC 10X        11558      2319         10X_P7_7 Bladder
10X_P7_7_TTATGCTTCCGCGGTA 10X         6376      2580         10X_P7_7 Bladder
10X_P7_7_TTCCCAGTCATGTGGT 10X        34918      5002         10X_P7_7 Bladder
10X_P7_7_TTCGGTCAGTGCGTGA 10X        14304      3511         10X_P7_7 Bladder
10X_P7_7_TTCGGTCCAGCGTAAG 10X        22793      4562         10X_P7_7 Bladder
10X_P7_7_TTCGGTCTCCGGGTGT 10X         8380      2764         10X_P7_7 Bladder
10X_P7_7_TTCTCAAAGAGCCCAA 10X        37286      5356         10X_P7_7 Bladder
10X_P7_7_TTCTCAACAAACGTGG 10X        14565      3769         10X_P7_7 Bladder
10X_P7_7_TTGAACGAGATGTCGG 10X         9558      2972         10X_P7_7 Bladder
10X_P7_7_TTGCGTCCAAAGTGCG 10X        11456      3241         10X_P7_7 Bladder
10X_P7_7_TTGCGTCGTAGGACAC 10X        21269      3633         10X_P7_7 Bladder
10X_P7_7_TTGGAACAGTAGATGT 10X         8974      2831         10X_P7_7 Bladder
10X_P7_7_TTGGAACGTCTAGTCA 10X         6607      2546         10X_P7_7 Bladder
10X_P7_7_TTGGAACGTGTCGCTG 10X        50069      5641         10X_P7_7 Bladder
10X_P7_7_TTGTAGGCACTTGGAT 10X         9666      3087         10X_P7_7 Bladder
10X_P7_7_TTGTAGGTCATGTAGC 10X        22993      4296         10X_P7_7 Bladder
10X_P7_7_TTTACTGGTGTTGAGG 10X         8753      3005         10X_P7_7 Bladder
10X_P7_7_TTTCCTCCATACCATG 10X        14665      3778         10X_P7_7 Bladder
10X_P7_7_TTTGTCAGTTACCGAT 10X        30363      4786         10X_P7_7 Bladder
10X_P7_7_TTTGTCATCTGTGCAA 10X        16524      3979         10X_P7_7 Bladder
                          subtissue mouse.sex mouse.id percent.ercc
10X_P4_3_AAAGTAGAGATGCCAG           M         3-M-8    0
10X_P4_3_AACCGCGTCCAACCAA           M         3-M-8    0
10X_P4_3_AACTCCCGTCGGGTCT           M         3-M-8    0
10X_P4_3_AACTCTTAGTTGCAGG           M         3-M-8    0
10X_P4_3_AACTCTTTCATAACCG           M         3-M-8    0
10X_P4_3_AAGACCTAGATCCGAG           M         3-M-8    0
10X_P4_3_AAGACCTAGGTGGGTT           M         3-M-8    0
10X_P4_3_AAGGAGCGTGCAACTT           M         3-M-8    0
10X_P4_3_AAGTCTGAGATAGTCA           M         3-M-8    0
10X_P4_3_ACAGCTATCATACGGT           M         3-M-8    0
10X_P4_3_ACATACGCAGCTCCGA           M         3-M-8    0
10X_P4_3_ACCAGTACACGTCTCT           M         3-M-8    0
10X_P4_3_ACGAGCCAGATAGCAT           M         3-M-8    0
10X_P4_3_ACGGAGATCGGAATCT           M         3-M-8    0
10X_P4_3_ACGGGCTGTCTGATCA           M         3-M-8    0
10X_P4_3_ACTGAACCATCCGGGT           M         3-M-8    0
10X_P4_3_ACTTTCAAGATGGGTC           M         3-M-8    0
10X_P4_3_AGACGTTTCTTACCGC           M         3-M-8    0
10X_P4_3_AGAGCTTTCTGTTGAG           M         3-M-8    0
10X_P4_3_AGCGGTCTCTGAGTGT           M         3-M-8    0
10X_P4_3_AGCTTGAAGACTAAGT           M         3-M-8    0
10X_P4_3_AGGGAGTCAATCGGTT           M         3-M-8    0
10X_P4_3_AGGGATGAGTCGCCGT           M         3-M-8    0
10X_P4_3_AGGGTGACAGTCGTGC           M         3-M-8    0
10X_P4_3_AGGTCCGAGGACACCA           M         3-M-8    0
10X_P4_3_AGTCTTTAGCTAGTGG           M         3-M-8    0
10X_P4_3_AGTGAGGAGTGTACTC           M         3-M-8    0
10X_P4_3_AGTGAGGTCAGCATGT           M         3-M-8    0
10X_P4_3_AGTGTCACAGTATCTG           M         3-M-8    0
10X_P4_3_ATCACGACAACAACCT           M         3-M-8    0
⋮                         ⋮         ⋮         ⋮        ⋮
10X_P7_7_TGTTCCGAGCTAACTC           F         3-F-56   0
10X_P7_7_TGTTCCGAGCTCCCAG           F         3-F-56   0
10X_P7_7_TTAACTCGTCTCTTTA           F         3-F-56   0
10X_P7_7_TTAACTCTCAGAGACG           F         3-F-56   0
10X_P7_7_TTAGGACAGACAAAGG           F         3-F-56   0
10X_P7_7_TTAGGACCAGGGTACA           F         3-F-56   0
10X_P7_7_TTAGGACGTCTCCCTA           F         3-F-56   0
10X_P7_7_TTATGCTAGCCATCGC           F         3-F-56   0
10X_P7_7_TTATGCTCAGATGAGC           F         3-F-56   0
10X_P7_7_TTATGCTCAGCGTTCG           F         3-F-56   0
10X_P7_7_TTATGCTTCCGAACGC           F         3-F-56   0
10X_P7_7_TTATGCTTCCGCGGTA           F         3-F-56   0
10X_P7_7_TTCCCAGTCATGTGGT           F         3-F-56   0
10X_P7_7_TTCGGTCAGTGCGTGA           F         3-F-56   0
10X_P7_7_TTCGGTCCAGCGTAAG           F         3-F-56   0
10X_P7_7_TTCGGTCTCCGGGTGT           F         3-F-56   0
10X_P7_7_TTCTCAAAGAGCCCAA           F         3-F-56   0
10X_P7_7_TTCTCAACAAACGTGG           F         3-F-56   0
10X_P7_7_TTGAACGAGATGTCGG           F         3-F-56   0
10X_P7_7_TTGCGTCCAAAGTGCG           F         3-F-56   0
10X_P7_7_TTGCGTCGTAGGACAC           F         3-F-56   0
10X_P7_7_TTGGAACAGTAGATGT           F         3-F-56   0
10X_P7_7_TTGGAACGTCTAGTCA           F         3-F-56   0
10X_P7_7_TTGGAACGTGTCGCTG           F         3-F-56   0
10X_P7_7_TTGTAGGCACTTGGAT           F         3-F-56   0
10X_P7_7_TTGTAGGTCATGTAGC           F         3-F-56   0
10X_P7_7_TTTACTGGTGTTGAGG           F         3-F-56   0
10X_P7_7_TTTCCTCCATACCATG           F         3-F-56   0
10X_P7_7_TTTGTCAGTTACCGAT           F         3-F-56   0
10X_P7_7_TTTGTCATCTGTGCAA           F         3-F-56   0
                          percent.ribo ⋯ previous_free_annotation
10X_P4_3_AAAGTAGAGATGCCAG 0.21960937   ⋯ NA
10X_P4_3_AACCGCGTCCAACCAA 0.17671233   ⋯ NA
10X_P4_3_AACTCCCGTCGGGTCT 0.19244438   ⋯ NA
10X_P4_3_AACTCTTAGTTGCAGG 0.35638461   ⋯ NA
10X_P4_3_AACTCTTTCATAACCG 0.15711936   ⋯ NA
10X_P4_3_AAGACCTAGATCCGAG 0.23778009   ⋯ NA
10X_P4_3_AAGACCTAGGTGGGTT 0.32809182   ⋯ NA
10X_P4_3_AAGGAGCGTGCAACTT 0.19020979   ⋯ NA
10X_P4_3_AAGTCTGAGATAGTCA 0.22597153   ⋯ NA
10X_P4_3_ACAGCTATCATACGGT 0.33777498   ⋯ NA
10X_P4_3_ACATACGCAGCTCCGA 0.13259285   ⋯ NA
10X_P4_3_ACCAGTACACGTCTCT 0.20075428   ⋯ NA
10X_P4_3_ACGAGCCAGATAGCAT 0.16328432   ⋯ NA
10X_P4_3_ACGGAGATCGGAATCT 0.15701626   ⋯ NA
10X_P4_3_ACGGGCTGTCTGATCA 0.17214306   ⋯ NA
10X_P4_3_ACTGAACCATCCGGGT 0.17514809   ⋯ NA
10X_P4_3_ACTTTCAAGATGGGTC 0.31819064   ⋯ NA
10X_P4_3_AGACGTTTCTTACCGC 0.09207814   ⋯ NA
10X_P4_3_AGAGCTTTCTGTTGAG 0.18882543   ⋯ NA
10X_P4_3_AGCGGTCTCTGAGTGT 0.36498276   ⋯ NA
10X_P4_3_AGCTTGAAGACTAAGT 0.12250161   ⋯ NA
10X_P4_3_AGGGAGTCAATCGGTT 0.20369575   ⋯ NA
10X_P4_3_AGGGATGAGTCGCCGT 0.16600114   ⋯ NA
10X_P4_3_AGGGTGACAGTCGTGC 0.16222954   ⋯ NA
10X_P4_3_AGGTCCGAGGACACCA 0.27174854   ⋯ NA
10X_P4_3_AGTCTTTAGCTAGTGG 0.16161616   ⋯ NA
10X_P4_3_AGTGAGGAGTGTACTC 0.13708333   ⋯ NA
10X_P4_3_AGTGAGGTCAGCATGT 0.31520974   ⋯ NA
10X_P4_3_AGTGTCACAGTATCTG 0.11181332   ⋯ NA
10X_P4_3_ATCACGACAACAACCT 0.14065046   ⋯ NA
⋮                         ⋮            ⋱ ⋮
10X_P7_7_TGTTCCGAGCTAACTC 0.34092475   ⋯ NA
10X_P7_7_TGTTCCGAGCTCCCAG 0.37134858   ⋯ NA
10X_P7_7_TTAACTCGTCTCTTTA 0.24913988   ⋯ NA
10X_P7_7_TTAACTCTCAGAGACG 0.34100829   ⋯ NA
10X_P7_7_TTAGGACAGACAAAGG 0.14717661   ⋯ NA
10X_P7_7_TTAGGACCAGGGTACA 0.31405240   ⋯ NA
10X_P7_7_TTAGGACGTCTCCCTA 0.14560827   ⋯ NA
10X_P7_7_TTATGCTAGCCATCGC 0.32313383   ⋯ NA
10X_P7_7_TTATGCTCAGATGAGC 0.26851048   ⋯ NA
10X_P7_7_TTATGCTCAGCGTTCG 0.04597003   ⋯ NA
10X_P7_7_TTATGCTTCCGAACGC 0.11792698   ⋯ NA
10X_P7_7_TTATGCTTCCGCGGTA 0.12531368   ⋯ NA
10X_P7_7_TTCCCAGTCATGTGGT 0.29950169   ⋯ NA
10X_P7_7_TTCGGTCAGTGCGTGA 0.16072427   ⋯ NA
10X_P7_7_TTCGGTCCAGCGTAAG 0.24985741   ⋯ NA
10X_P7_7_TTCGGTCTCCGGGTGT 0.14439141   ⋯ NA
10X_P7_7_TTCTCAAAGAGCCCAA 0.36834201   ⋯ NA
10X_P7_7_TTCTCAACAAACGTGG 0.11342259   ⋯ NA
10X_P7_7_TTGAACGAGATGTCGG 0.16970077   ⋯ NA
10X_P7_7_TTGCGTCCAAAGTGCG 0.16096369   ⋯ NA
10X_P7_7_TTGCGTCGTAGGACAC 0.34331656   ⋯ NA
10X_P7_7_TTGGAACAGTAGATGT 0.13527970   ⋯ NA
10X_P7_7_TTGGAACGTCTAGTCA 0.13319207   ⋯ NA
10X_P7_7_TTGGAACGTGTCGCTG 0.40040744   ⋯ NA
10X_P7_7_TTGTAGGCACTTGGAT 0.10862818   ⋯ NA
10X_P7_7_TTGTAGGTCATGTAGC 0.28678293   ⋯ NA
10X_P7_7_TTTACTGGTGTTGAGG 0.12087284   ⋯ NA
10X_P7_7_TTTCCTCCATACCATG 0.11817252   ⋯ NA
10X_P7_7_TTTGTCAGTTACCGAT 0.30701841   ⋯ NA
10X_P7_7_TTTGTCATCTGTGCAA 0.29950375   ⋯ NA
                          previous_cell_ontology_class cluster.ids
10X_P4_3_AAAGTAGAGATGCCAG NA                           0
10X_P4_3_AACCGCGTCCAACCAA NA                           2
10X_P4_3_AACTCCCGTCGGGTCT NA                           5
10X_P4_3_AACTCTTAGTTGCAGG NA                           3
10X_P4_3_AACTCTTTCATAACCG NA                           2
10X_P4_3_AAGACCTAGATCCGAG NA                           6
10X_P4_3_AAGACCTAGGTGGGTT NA                           1
10X_P4_3_AAGGAGCGTGCAACTT NA                           0
10X_P4_3_AAGTCTGAGATAGTCA NA                           4
10X_P4_3_ACAGCTATCATACGGT NA                           1
10X_P4_3_ACATACGCAGCTCCGA NA                           4
10X_P4_3_ACCAGTACACGTCTCT NA                           0
10X_P4_3_ACGAGCCAGATAGCAT NA                           0
10X_P4_3_ACGGAGATCGGAATCT NA                           2
10X_P4_3_ACGGGCTGTCTGATCA NA                           0
10X_P4_3_ACTGAACCATCCGGGT NA                           0
10X_P4_3_ACTTTCAAGATGGGTC NA                           1
10X_P4_3_AGACGTTTCTTACCGC NA                           5
10X_P4_3_AGAGCTTTCTGTTGAG NA                           2
10X_P4_3_AGCGGTCTCTGAGTGT NA                           1
10X_P4_3_AGCTTGAAGACTAAGT NA                           0
10X_P4_3_AGGGAGTCAATCGGTT NA                           0
10X_P4_3_AGGGATGAGTCGCCGT NA                           0
10X_P4_3_AGGGTGACAGTCGTGC NA                           0
10X_P4_3_AGGTCCGAGGACACCA NA                           1
10X_P4_3_AGTCTTTAGCTAGTGG NA                           0
10X_P4_3_AGTGAGGAGTGTACTC NA                           0
10X_P4_3_AGTGAGGTCAGCATGT NA                           1
10X_P4_3_AGTGTCACAGTATCTG NA                           5
10X_P4_3_ATCACGACAACAACCT NA                           2
⋮                         ⋮                            ⋮
10X_P7_7_TGTTCCGAGCTAACTC NA                           1
10X_P7_7_TGTTCCGAGCTCCCAG NA                           1
10X_P7_7_TTAACTCGTCTCTTTA NA                           1
10X_P7_7_TTAACTCTCAGAGACG NA                           4
10X_P7_7_TTAGGACAGACAAAGG NA                           5
10X_P7_7_TTAGGACCAGGGTACA NA                           1
10X_P7_7_TTAGGACGTCTCCCTA NA                           5
10X_P7_7_TTATGCTAGCCATCGC NA                           1
10X_P7_7_TTATGCTCAGATGAGC NA                           4
10X_P7_7_TTATGCTCAGCGTTCG NA                           6
10X_P7_7_TTATGCTTCCGAACGC NA                           6
10X_P7_7_TTATGCTTCCGCGGTA NA                           0
10X_P7_7_TTCCCAGTCATGTGGT NA                           1
10X_P7_7_TTCGGTCAGTGCGTGA NA                           5
10X_P7_7_TTCGGTCCAGCGTAAG NA                           1
10X_P7_7_TTCGGTCTCCGGGTGT NA                           5
10X_P7_7_TTCTCAAAGAGCCCAA NA                           1
10X_P7_7_TTCTCAACAAACGTGG NA                           5
10X_P7_7_TTGAACGAGATGTCGG NA                           5
10X_P7_7_TTGCGTCCAAAGTGCG NA                           5
10X_P7_7_TTGCGTCGTAGGACAC NA                           1
10X_P7_7_TTGGAACAGTAGATGT NA                           5
10X_P7_7_TTGGAACGTCTAGTCA NA                           0
10X_P7_7_TTGGAACGTGTCGCTG NA                           4
10X_P7_7_TTGTAGGCACTTGGAT NA                           7
10X_P7_7_TTGTAGGTCATGTAGC NA                           1
10X_P7_7_TTTACTGGTGTTGAGG NA                           5
10X_P7_7_TTTCCTCCATACCATG NA                           5
10X_P7_7_TTTGTCAGTTACCGAT NA                           1
10X_P7_7_TTTGTCATCTGTGCAA NA                           1
                          cell_ontology_id percent.mt percent.rb percent.hb
10X_P4_3_AAAGTAGAGATGCCAG CL:1001319       0          0          0
10X_P4_3_AACCGCGTCCAACCAA CL:1001319       0          0          0
10X_P4_3_AACTCCCGTCGGGTCT CL:1001319       0          0          0
10X_P4_3_AACTCTTAGTTGCAGG CL:1001428       0          0          0
10X_P4_3_AACTCTTTCATAACCG CL:1001319       0          0          0
10X_P4_3_AAGACCTAGATCCGAG CL:0000738       0          0          0
10X_P4_3_AAGACCTAGGTGGGTT CL:1001428       0          0          0
10X_P4_3_AAGGAGCGTGCAACTT CL:1001319       0          0          0
10X_P4_3_AAGTCTGAGATAGTCA CL:1001428       0          0          0
10X_P4_3_ACAGCTATCATACGGT CL:1001428       0          0          0
10X_P4_3_ACATACGCAGCTCCGA CL:1001428       0          0          0
10X_P4_3_ACCAGTACACGTCTCT CL:1001319       0          0          0
10X_P4_3_ACGAGCCAGATAGCAT CL:1001319       0          0          0
10X_P4_3_ACGGAGATCGGAATCT CL:1001319       0          0          0
10X_P4_3_ACGGGCTGTCTGATCA CL:1001319       0          0          0
10X_P4_3_ACTGAACCATCCGGGT CL:1001319       0          0          0
10X_P4_3_ACTTTCAAGATGGGTC CL:1001428       0          0          0
10X_P4_3_AGACGTTTCTTACCGC CL:1001319       0          0          0
10X_P4_3_AGAGCTTTCTGTTGAG CL:1001319       0          0          0
10X_P4_3_AGCGGTCTCTGAGTGT CL:1001428       0          0          0
10X_P4_3_AGCTTGAAGACTAAGT CL:1001319       0          0          0
10X_P4_3_AGGGAGTCAATCGGTT CL:1001319       0          0          0
10X_P4_3_AGGGATGAGTCGCCGT CL:1001319       0          0          0
10X_P4_3_AGGGTGACAGTCGTGC CL:1001319       0          0          0
10X_P4_3_AGGTCCGAGGACACCA CL:1001428       0          0          0
10X_P4_3_AGTCTTTAGCTAGTGG CL:1001319       0          0          0
10X_P4_3_AGTGAGGAGTGTACTC CL:1001319       0          0          0
10X_P4_3_AGTGAGGTCAGCATGT CL:1001428       0          0          0
10X_P4_3_AGTGTCACAGTATCTG CL:1001319       0          0          0
10X_P4_3_ATCACGACAACAACCT CL:1001319       0          0          0
⋮                         ⋮                ⋮          ⋮          ⋮
10X_P7_7_TGTTCCGAGCTAACTC CL:1001428       0          0          0
10X_P7_7_TGTTCCGAGCTCCCAG CL:1001428       0          0          0
10X_P7_7_TTAACTCGTCTCTTTA CL:1001428       0          0          0
10X_P7_7_TTAACTCTCAGAGACG CL:1001428       0          0          0
10X_P7_7_TTAGGACAGACAAAGG CL:1001319       0          0          0
10X_P7_7_TTAGGACCAGGGTACA CL:1001428       0          0          0
10X_P7_7_TTAGGACGTCTCCCTA CL:1001319       0          0          0
10X_P7_7_TTATGCTAGCCATCGC CL:1001428       0          0          0
10X_P7_7_TTATGCTCAGATGAGC CL:1001428       0          0          0
10X_P7_7_TTATGCTCAGCGTTCG CL:0000738       0          0          0
10X_P7_7_TTATGCTTCCGAACGC CL:0000738       0          0          0
10X_P7_7_TTATGCTTCCGCGGTA CL:1001319       0          0          0
10X_P7_7_TTCCCAGTCATGTGGT CL:1001428       0          0          0
10X_P7_7_TTCGGTCAGTGCGTGA CL:1001319       0          0          0
10X_P7_7_TTCGGTCCAGCGTAAG CL:1001428       0          0          0
10X_P7_7_TTCGGTCTCCGGGTGT CL:1001319       0          0          0
10X_P7_7_TTCTCAAAGAGCCCAA CL:1001428       0          0          0
10X_P7_7_TTCTCAACAAACGTGG CL:1001319       0          0          0
10X_P7_7_TTGAACGAGATGTCGG CL:1001319       0          0          0
10X_P7_7_TTGCGTCCAAAGTGCG CL:1001319       0          0          0
10X_P7_7_TTGCGTCGTAGGACAC CL:1001428       0          0          0
10X_P7_7_TTGGAACAGTAGATGT CL:1001319       0          0          0
10X_P7_7_TTGGAACGTCTAGTCA CL:1001319       0          0          0
10X_P7_7_TTGGAACGTGTCGCTG CL:1001428       0          0          0
10X_P7_7_TTGTAGGCACTTGGAT CL:0000115       0          0          0
10X_P7_7_TTGTAGGTCATGTAGC CL:1001428       0          0          0
10X_P7_7_TTTACTGGTGTTGAGG CL:1001319       0          0          0
10X_P7_7_TTTCCTCCATACCATG CL:1001319       0          0          0
10X_P7_7_TTTGTCAGTTACCGAT CL:1001428       0          0          0
10X_P7_7_TTTGTCATCTGTGCAA CL:1001428       0          0          0
                          percent.plat Doublet_score Is_doublet
10X_P4_3_AAAGTAGAGATGCCAG 0            NA            FALSE
10X_P4_3_AACCGCGTCCAACCAA 0            NA            FALSE
10X_P4_3_AACTCCCGTCGGGTCT 0            NA            FALSE
10X_P4_3_AACTCTTAGTTGCAGG 0            NA            FALSE
10X_P4_3_AACTCTTTCATAACCG 0            NA            FALSE
10X_P4_3_AAGACCTAGATCCGAG 0            NA            FALSE
10X_P4_3_AAGACCTAGGTGGGTT 0            NA            FALSE
10X_P4_3_AAGGAGCGTGCAACTT 0            NA            FALSE
10X_P4_3_AAGTCTGAGATAGTCA 0            NA            FALSE
10X_P4_3_ACAGCTATCATACGGT 0            NA            FALSE
10X_P4_3_ACATACGCAGCTCCGA 0            NA            FALSE
10X_P4_3_ACCAGTACACGTCTCT 0            NA            FALSE
10X_P4_3_ACGAGCCAGATAGCAT 0            NA            FALSE
10X_P4_3_ACGGAGATCGGAATCT 0            NA            FALSE
10X_P4_3_ACGGGCTGTCTGATCA 0            NA            FALSE
10X_P4_3_ACTGAACCATCCGGGT 0            NA            FALSE
10X_P4_3_ACTTTCAAGATGGGTC 0            NA            FALSE
10X_P4_3_AGACGTTTCTTACCGC 0            NA            FALSE

In [47]:
srat_qc@meta.data <- .regularise_df(srat_qc@meta.data, drop_single_values=FALSE, drop_na_values=TRUE)
srat_qc@meta.data

                          orig.ident nCount_RNA nFeature_RNA channel  tissue
10X_P4_3_AAAGTAGAGATGCCAG 10X        10291      2853         10X_P4_3 Bladder
10X_P4_3_AACCGCGTCCAACCAA 10X        17520      4194         10X_P4_3 Bladder
10X_P4_3_AACTCCCGTCGGGTCT 10X        12944      3347         10X_P4_3 Bladder
10X_P4_3_AACTCTTAGTTGCAGG 10X        19594      3851         10X_P4_3 Bladder
10X_P4_3_AACTCTTTCATAACCG 10X        14594      3809         10X_P4_3 Bladder
10X_P4_3_AAGACCTAGATCCGAG 10X        19190      3608         10X_P4_3 Bladder
10X_P4_3_AAGACCTAGGTGGGTT 10X        24484      4347         10X_P4_3 Bladder
10X_P4_3_AAGGAGCGTGCAACTT 10X         5005      1960         10X_P4_3 Bladder
10X_P4_3_AAGTCTGAGATAGTCA 10X         6253      2236         10X_P4_3 Bladder
10X_P4_3_ACAGCTATCATACGGT 10X        15910      3374         10X_P4_3 Bladder
10X_P4_3_ACATACGCAGCTCCGA 10X         2881      1558         10X_P4_3 Bladder
10X_P4_3_ACCAGTACACGTCTCT 10X         6894      2348         10X_P4_3 Bladder
10X_P4_3_ACGAGCCAGATAGCAT 10X         9658      3141         10X_P4_3 Bladder
10X_P4_3_ACGGAGATCGGAATCT 10X        11623      3357         10X_P4_3 Bladder
10X_P4_3_ACGGGCTGTCTGATCA 10X         6878      2285         10X_P4_3 Bladder
10X_P4_3_ACTGAACCATCCGGGT 10X         7428      2319         10X_P4_3 Bladder
10X_P4_3_ACTTTCAAGATGGGTC 10X        10302      2875         10X_P4_3 Bladder
10X_P4_3_AGACGTTTCTTACCGC 10X        10187      3197         10X_P4_3 Bladder
10X_P4_3_AGAGCTTTCTGTTGAG 10X        25039      4812         10X_P4_3 Bladder
10X_P4_3_AGCGGTCTCTGAGTGT 10X        23497      4152         10X_P4_3 Bladder
10X_P4_3_AGCTTGAAGACTAAGT 10X         3102      1431         10X_P4_3 Bladder
10X_P4_3_AGGGAGTCAATCGGTT 10X         6981      2323         10X_P4_3 Bladder
10X_P4_3_AGGGATGAGTCGCCGT 10X         5259      1975         10X_P4_3 Bladder
10X_P4_3_AGGGTGACAGTCGTGC 10X        11231      3314         10X_P4_3 Bladder
10X_P4_3_AGGTCCGAGGACACCA 10X        26565      5040         10X_P4_3 Bladder
10X_P4_3_AGTCTTTAGCTAGTGG 10X         2277      1098         10X_P4_3 Bladder
10X_P4_3_AGTGAGGAGTGTACTC 10X         4800      1888         10X_P4_3 Bladder
10X_P4_3_AGTGAGGTCAGCATGT 10X        19882      3884         10X_P4_3 Bladder
10X_P4_3_AGTGTCACAGTATCTG 10X         6171      2299         10X_P4_3 Bladder
10X_P4_3_ATCACGACAACAACCT 10X        14113      3699         10X_P4_3 Bladder
⋮                         ⋮          ⋮          ⋮            ⋮        ⋮
10X_P7_7_TGTTCCGAGCTAACTC 10X        23228      4255         10X_P7_7 Bladder
10X_P7_7_TGTTCCGAGCTCCCAG 10X        42860      5745         10X_P7_7 Bladder
10X_P7_7_TTAACTCGTCTCTTTA 10X        35751      5422         10X_P7_7 Bladder
10X_P7_7_TTAACTCTCAGAGACG 10X        31618      4440         10X_P7_7 Bladder
10X_P7_7_TTAGGACAGACAAAGG 10X         9988      3201         10X_P7_7 Bladder
10X_P7_7_TTAGGACCAGGGTACA 10X        11756      2880         10X_P7_7 Bladder
10X_P7_7_TTAGGACGTCTCCCTA 10X         8516      2732         10X_P7_7 Bladder
10X_P7_7_TTATGCTAGCCATCGC 10X        14870      3657         10X_P7_7 Bladder
10X_P7_7_TTATGCTCAGATGAGC 10X        16126      3372         10X_P7_7 Bladder
10X_P7_7_TTATGCTCAGCGTTCG 10X         4938      1528         10X_P7_7 Bladder
10X_P7_7_TTATGCTTCCGAACGC 10X        11558      2319         10X_P7_7 Bladder
10X_P7_7_TTATGCTTCCGCGGTA 10X         6376      2580         10X_P7_7 Bladder
10X_P7_7_TTCCCAGTCATGTGGT 10X        34918      5002         10X_P7_7 Bladder
10X_P7_7_TTCGGTCAGTGCGTGA 10X        14304      3511         10X_P7_7 Bladder
10X_P7_7_TTCGGTCCAGCGTAAG 10X        22793      4562         10X_P7_7 Bladder
10X_P7_7_TTCGGTCTCCGGGTGT 10X         8380      2764         10X_P7_7 Bladder
10X_P7_7_TTCTCAAAGAGCCCAA 10X        37286      5356         10X_P7_7 Bladder
10X_P7_7_TTCTCAACAAACGTGG 10X        14565      3769         10X_P7_7 Bladder
10X_P7_7_TTGAACGAGATGTCGG 10X         9558      2972         10X_P7_7 Bladder
10X_P7_7_TTGCGTCCAAAGTGCG 10X        11456      3241         10X_P7_7 Bladder
10X_P7_7_TTGCGTCGTAGGACAC 10X        21269      3633         10X_P7_7 Bladder
10X_P7_7_TTGGAACAGTAGATGT 10X         8974      2831         10X_P7_7 Bladder
10X_P7_7_TTGGAACGTCTAGTCA 10X         6607      2546         10X_P7_7 Bladder
10X_P7_7_TTGGAACGTGTCGCTG 10X        50069      5641         10X_P7_7 Bladder
10X_P7_7_TTGTAGGCACTTGGAT 10X         9666      3087         10X_P7_7 Bladder
10X_P7_7_TTGTAGGTCATGTAGC 10X        22993      4296         10X_P7_7 Bladder
10X_P7_7_TTTACTGGTGTTGAGG 10X         8753      3005         10X_P7_7 Bladder
10X_P7_7_TTTCCTCCATACCATG 10X        14665      3778         10X_P7_7 Bladder
10X_P7_7_TTTGTCAGTTACCGAT 10X        30363      4786         10X_P7_7 Bladder
10X_P7_7_TTTGTCATCTGTGCAA 10X        16524      3979         10X_P7_7 Bladder
                          subtissue mouse.sex mouse.id percent.ercc
10X_P4_3_AAAGTAGAGATGCCAG           M         3-M-8    0
10X_P4_3_AACCGCGTCCAACCAA           M         3-M-8    0
10X_P4_3_AACTCCCGTCGGGTCT           M         3-M-8    0
10X_P4_3_AACTCTTAGTTGCAGG           M         3-M-8    0
10X_P4_3_AACTCTTTCATAACCG           M         3-M-8    0
10X_P4_3_AAGACCTAGATCCGAG           M         3-M-8    0
10X_P4_3_AAGACCTAGGTGGGTT           M         3-M-8    0
10X_P4_3_AAGGAGCGTGCAACTT           M         3-M-8    0
10X_P4_3_AAGTCTGAGATAGTCA           M         3-M-8    0
10X_P4_3_ACAGCTATCATACGGT           M         3-M-8    0
10X_P4_3_ACATACGCAGCTCCGA           M         3-M-8    0
10X_P4_3_ACCAGTACACGTCTCT           M         3-M-8    0
10X_P4_3_ACGAGCCAGATAGCAT           M         3-M-8    0
10X_P4_3_ACGGAGATCGGAATCT           M         3-M-8    0
10X_P4_3_ACGGGCTGTCTGATCA           M         3-M-8    0
10X_P4_3_ACTGAACCATCCGGGT           M         3-M-8    0
10X_P4_3_ACTTTCAAGATGGGTC           M         3-M-8    0
10X_P4_3_AGACGTTTCTTACCGC           M         3-M-8    0
10X_P4_3_AGAGCTTTCTGTTGAG           M         3-M-8    0
10X_P4_3_AGCGGTCTCTGAGTGT           M         3-M-8    0
10X_P4_3_AGCTTGAAGACTAAGT           M         3-M-8    0
10X_P4_3_AGGGAGTCAATCGGTT           M         3-M-8    0
10X_P4_3_AGGGATGAGTCGCCGT           M         3-M-8    0
10X_P4_3_AGGGTGACAGTCGTGC           M         3-M-8    0
10X_P4_3_AGGTCCGAGGACACCA           M         3-M-8    0
10X_P4_3_AGTCTTTAGCTAGTGG           M         3-M-8    0
10X_P4_3_AGTGAGGAGTGTACTC           M         3-M-8    0
10X_P4_3_AGTGAGGTCAGCATGT           M         3-M-8    0
10X_P4_3_AGTGTCACAGTATCTG           M         3-M-8    0
10X_P4_3_ATCACGACAACAACCT           M         3-M-8    0
⋮                         ⋮         ⋮         ⋮        ⋮
10X_P7_7_TGTTCCGAGCTAACTC           F         3-F-56   0
10X_P7_7_TGTTCCGAGCTCCCAG           F         3-F-56   0
10X_P7_7_TTAACTCGTCTCTTTA           F         3-F-56   0
10X_P7_7_TTAACTCTCAGAGACG           F         3-F-56   0
10X_P7_7_TTAGGACAGACAAAGG           F         3-F-56   0
10X_P7_7_TTAGGACCAGGGTACA           F         3-F-56   0
10X_P7_7_TTAGGACGTCTCCCTA           F         3-F-56   0
10X_P7_7_TTATGCTAGCCATCGC           F         3-F-56   0
10X_P7_7_TTATGCTCAGATGAGC           F         3-F-56   0
10X_P7_7_TTATGCTCAGCGTTCG           F         3-F-56   0
10X_P7_7_TTATGCTTCCGAACGC           F         3-F-56   0
10X_P7_7_TTATGCTTCCGCGGTA           F         3-F-56   0
10X_P7_7_TTCCCAGTCATGTGGT           F         3-F-56   0
10X_P7_7_TTCGGTCAGTGCGTGA           F         3-F-56   0
10X_P7_7_TTCGGTCCAGCGTAAG           F         3-F-56   0
10X_P7_7_TTCGGTCTCCGGGTGT           F         3-F-56   0
10X_P7_7_TTCTCAAAGAGCCCAA           F         3-F-56   0
10X_P7_7_TTCTCAACAAACGTGG           F         3-F-56   0
10X_P7_7_TTGAACGAGATGTCGG           F         3-F-56   0
10X_P7_7_TTGCGTCCAAAGTGCG           F         3-F-56   0
10X_P7_7_TTGCGTCGTAGGACAC           F         3-F-56   0
10X_P7_7_TTGGAACAGTAGATGT           F         3-F-56   0
10X_P7_7_TTGGAACGTCTAGTCA           F         3-F-56   0
10X_P7_7_TTGGAACGTGTCGCTG           F         3-F-56   0
10X_P7_7_TTGTAGGCACTTGGAT           F         3-F-56   0
10X_P7_7_TTGTAGGTCATGTAGC           F         3-F-56   0
10X_P7_7_TTTACTGGTGTTGAGG           F         3-F-56   0
10X_P7_7_TTTCCTCCATACCATG           F         3-F-56   0
10X_P7_7_TTTGTCAGTTACCGAT           F         3-F-56   0
10X_P7_7_TTTGTCATCTGTGCAA           F         3-F-56   0
                          percent.ribo ⋯ previous_free_annotation
10X_P4_3_AAAGTAGAGATGCCAG 0.21960937   ⋯ NA
10X_P4_3_AACCGCGTCCAACCAA 0.17671233   ⋯ NA
10X_P4_3_AACTCCCGTCGGGTCT 0.19244438   ⋯ NA
10X_P4_3_AACTCTTAGTTGCAGG 0.35638461   ⋯ NA
10X_P4_3_AACTCTTTCATAACCG 0.15711936   ⋯ NA
10X_P4_3_AAGACCTAGATCCGAG 0.23778009   ⋯ NA
10X_P4_3_AAGACCTAGGTGGGTT 0.32809182   ⋯ NA
10X_P4_3_AAGGAGCGTGCAACTT 0.19020979   ⋯ NA
10X_P4_3_AAGTCTGAGATAGTCA 0.22597153   ⋯ NA
10X_P4_3_ACAGCTATCATACGGT 0.33777498   ⋯ NA
10X_P4_3_ACATACGCAGCTCCGA 0.13259285   ⋯ NA
10X_P4_3_ACCAGTACACGTCTCT 0.20075428   ⋯ NA
10X_P4_3_ACGAGCCAGATAGCAT 0.16328432   ⋯ NA
10X_P4_3_ACGGAGATCGGAATCT 0.15701626   ⋯ NA
10X_P4_3_ACGGGCTGTCTGATCA 0.17214306   ⋯ NA
10X_P4_3_ACTGAACCATCCGGGT 0.17514809   ⋯ NA
10X_P4_3_ACTTTCAAGATGGGTC 0.31819064   ⋯ NA
10X_P4_3_AGACGTTTCTTACCGC 0.09207814   ⋯ NA
10X_P4_3_AGAGCTTTCTGTTGAG 0.18882543   ⋯ NA
10X_P4_3_AGCGGTCTCTGAGTGT 0.36498276   ⋯ NA
10X_P4_3_AGCTTGAAGACTAAGT 0.12250161   ⋯ NA
10X_P4_3_AGGGAGTCAATCGGTT 0.20369575   ⋯ NA
10X_P4_3_AGGGATGAGTCGCCGT 0.16600114   ⋯ NA
10X_P4_3_AGGGTGACAGTCGTGC 0.16222954   ⋯ NA
10X_P4_3_AGGTCCGAGGACACCA 0.27174854   ⋯ NA
10X_P4_3_AGTCTTTAGCTAGTGG 0.16161616   ⋯ NA
10X_P4_3_AGTGAGGAGTGTACTC 0.13708333   ⋯ NA
10X_P4_3_AGTGAGGTCAGCATGT 0.31520974   ⋯ NA
10X_P4_3_AGTGTCACAGTATCTG 0.11181332   ⋯ NA
10X_P4_3_ATCACGACAACAACCT 0.14065046   ⋯ NA
⋮                         ⋮            ⋱ ⋮
10X_P7_7_TGTTCCGAGCTAACTC 0.34092475   ⋯ NA
10X_P7_7_TGTTCCGAGCTCCCAG 0.37134858   ⋯ NA
10X_P7_7_TTAACTCGTCTCTTTA 0.24913988   ⋯ NA
10X_P7_7_TTAACTCTCAGAGACG 0.34100829   ⋯ NA
10X_P7_7_TTAGGACAGACAAAGG 0.14717661   ⋯ NA
10X_P7_7_TTAGGACCAGGGTACA 0.31405240   ⋯ NA
10X_P7_7_TTAGGACGTCTCCCTA 0.14560827   ⋯ NA
10X_P7_7_TTATGCTAGCCATCGC 0.32313383   ⋯ NA
10X_P7_7_TTATGCTCAGATGAGC 0.26851048   ⋯ NA
10X_P7_7_TTATGCTCAGCGTTCG 0.04597003   ⋯ NA
10X_P7_7_TTATGCTTCCGAACGC 0.11792698   ⋯ NA
10X_P7_7_TTATGCTTCCGCGGTA 0.12531368   ⋯ NA
10X_P7_7_TTCCCAGTCATGTGGT 0.29950169   ⋯ NA
10X_P7_7_TTCGGTCAGTGCGTGA 0.16072427   ⋯ NA
10X_P7_7_TTCGGTCCAGCGTAAG 0.24985741   ⋯ NA
10X_P7_7_TTCGGTCTCCGGGTGT 0.14439141   ⋯ NA
10X_P7_7_TTCTCAAAGAGCCCAA 0.36834201   ⋯ NA
10X_P7_7_TTCTCAACAAACGTGG 0.11342259   ⋯ NA
10X_P7_7_TTGAACGAGATGTCGG 0.16970077   ⋯ NA
10X_P7_7_TTGCGTCCAAAGTGCG 0.16096369   ⋯ NA
10X_P7_7_TTGCGTCGTAGGACAC 0.34331656   ⋯ NA
10X_P7_7_TTGGAACAGTAGATGT 0.13527970   ⋯ NA
10X_P7_7_TTGGAACGTCTAGTCA 0.13319207   ⋯ NA
10X_P7_7_TTGGAACGTGTCGCTG 0.40040744   ⋯ NA
10X_P7_7_TTGTAGGCACTTGGAT 0.10862818   ⋯ NA
10X_P7_7_TTGTAGGTCATGTAGC 0.28678293   ⋯ NA
10X_P7_7_TTTACTGGTGTTGAGG 0.12087284   ⋯ NA
10X_P7_7_TTTCCTCCATACCATG 0.11817252   ⋯ NA
10X_P7_7_TTTGTCAGTTACCGAT 0.30701841   ⋯ NA
10X_P7_7_TTTGTCATCTGTGCAA 0.29950375   ⋯ NA
                          previous_cell_ontology_class cluster.ids
10X_P4_3_AAAGTAGAGATGCCAG NA                           0
10X_P4_3_AACCGCGTCCAACCAA NA                           2
10X_P4_3_AACTCCCGTCGGGTCT NA                           5
10X_P4_3_AACTCTTAGTTGCAGG NA                           3
10X_P4_3_AACTCTTTCATAACCG NA                           2
10X_P4_3_AAGACCTAGATCCGAG NA                           6
10X_P4_3_AAGACCTAGGTGGGTT NA                           1
10X_P4_3_AAGGAGCGTGCAACTT NA                           0
10X_P4_3_AAGTCTGAGATAGTCA NA                           4
10X_P4_3_ACAGCTATCATACGGT NA                           1
10X_P4_3_ACATACGCAGCTCCGA NA                           4
10X_P4_3_ACCAGTACACGTCTCT NA                           0
10X_P4_3_ACGAGCCAGATAGCAT NA                           0
10X_P4_3_ACGGAGATCGGAATCT NA                           2
10X_P4_3_ACGGGCTGTCTGATCA NA                           0
10X_P4_3_ACTGAACCATCCGGGT NA                           0
10X_P4_3_ACTTTCAAGATGGGTC NA                           1
10X_P4_3_AGACGTTTCTTACCGC NA                           5
10X_P4_3_AGAGCTTTCTGTTGAG NA                           2
10X_P4_3_AGCGGTCTCTGAGTGT NA                           1
10X_P4_3_AGCTTGAAGACTAAGT NA                           0
10X_P4_3_AGGGAGTCAATCGGTT NA                           0
10X_P4_3_AGGGATGAGTCGCCGT NA                           0
10X_P4_3_AGGGTGACAGTCGTGC NA                           0
10X_P4_3_AGGTCCGAGGACACCA NA                           1
10X_P4_3_AGTCTTTAGCTAGTGG NA                           0
10X_P4_3_AGTGAGGAGTGTACTC NA                           0
10X_P4_3_AGTGAGGTCAGCATGT NA                           1
10X_P4_3_AGTGTCACAGTATCTG NA                           5
10X_P4_3_ATCACGACAACAACCT NA                           2
⋮                         ⋮                            ⋮
10X_P7_7_TGTTCCGAGCTAACTC NA                           1
10X_P7_7_TGTTCCGAGCTCCCAG NA                           1
10X_P7_7_TTAACTCGTCTCTTTA NA                           1
10X_P7_7_TTAACTCTCAGAGACG NA                           4
10X_P7_7_TTAGGACAGACAAAGG NA                           5
10X_P7_7_TTAGGACCAGGGTACA NA                           1
10X_P7_7_TTAGGACGTCTCCCTA NA                           5
10X_P7_7_TTATGCTAGCCATCGC NA                           1
10X_P7_7_TTATGCTCAGATGAGC NA                           4
10X_P7_7_TTATGCTCAGCGTTCG NA                           6
10X_P7_7_TTATGCTTCCGAACGC NA                           6
10X_P7_7_TTATGCTTCCGCGGTA NA                           0
10X_P7_7_TTCCCAGTCATGTGGT NA                           1
10X_P7_7_TTCGGTCAGTGCGTGA NA                           5
10X_P7_7_TTCGGTCCAGCGTAAG NA                           1
10X_P7_7_TTCGGTCTCCGGGTGT NA                           5
10X_P7_7_TTCTCAAAGAGCCCAA NA                           1
10X_P7_7_TTCTCAACAAACGTGG NA                           5
10X_P7_7_TTGAACGAGATGTCGG NA                           5
10X_P7_7_TTGCGTCCAAAGTGCG NA                           5
10X_P7_7_TTGCGTCGTAGGACAC NA                           1
10X_P7_7_TTGGAACAGTAGATGT NA                           5
10X_P7_7_TTGGAACGTCTAGTCA NA                           0
10X_P7_7_TTGGAACGTGTCGCTG NA                           4
10X_P7_7_TTGTAGGCACTTGGAT NA                           7
10X_P7_7_TTGTAGGTCATGTAGC NA                           1
10X_P7_7_TTTACTGGTGTTGAGG NA                           5
10X_P7_7_TTTCCTCCATACCATG NA                           5
10X_P7_7_TTTGTCAGTTACCGAT NA                           1
10X_P7_7_TTTGTCATCTGTGCAA NA                           1
                          cell_ontology_id percent.mt percent.rb percent.hb
10X_P4_3_AAAGTAGAGATGCCAG CL:1001319       0          0          0
10X_P4_3_AACCGCGTCCAACCAA CL:1001319       0          0          0
10X_P4_3_AACTCCCGTCGGGTCT CL:1001319       0          0          0
10X_P4_3_AACTCTTAGTTGCAGG CL:1001428       0          0          0
10X_P4_3_AACTCTTTCATAACCG CL:1001319       0          0          0
10X_P4_3_AAGACCTAGATCCGAG CL:0000738       0          0          0
10X_P4_3_AAGACCTAGGTGGGTT CL:1001428       0          0          0
10X_P4_3_AAGGAGCGTGCAACTT CL:1001319       0          0          0
10X_P4_3_AAGTCTGAGATAGTCA CL:1001428       0          0          0
10X_P4_3_ACAGCTATCATACGGT CL:1001428       0          0          0
10X_P4_3_ACATACGCAGCTCCGA CL:1001428       0          0          0
10X_P4_3_ACCAGTACACGTCTCT CL:1001319       0          0          0
10X_P4_3_ACGAGCCAGATAGCAT CL:1001319       0          0          0
10X_P4_3_ACGGAGATCGGAATCT CL:1001319       0          0          0
10X_P4_3_ACGGGCTGTCTGATCA CL:1001319       0          0          0
10X_P4_3_ACTGAACCATCCGGGT CL:1001319       0          0          0
10X_P4_3_ACTTTCAAGATGGGTC CL:1001428       0          0          0
10X_P4_3_AGACGTTTCTTACCGC CL:1001319       0          0          0
10X_P4_3_AGAGCTTTCTGTTGAG CL:1001319       0          0          0
10X_P4_3_AGCGGTCTCTGAGTGT CL:1001428       0          0          0
10X_P4_3_AGCTTGAAGACTAAGT CL:1001319       0          0          0
10X_P4_3_AGGGAGTCAATCGGTT CL:1001319       0          0          0
10X_P4_3_AGGGATGAGTCGCCGT CL:1001319       0          0          0
10X_P4_3_AGGGTGACAGTCGTGC CL:1001319       0          0          0
10X_P4_3_AGGTCCGAGGACACCA CL:1001428       0          0          0
10X_P4_3_AGTCTTTAGCTAGTGG CL:1001319       0          0          0
10X_P4_3_AGTGAGGAGTGTACTC CL:1001319       0          0          0
10X_P4_3_AGTGAGGTCAGCATGT CL:1001428       0          0          0
10X_P4_3_AGTGTCACAGTATCTG CL:1001319       0          0          0
10X_P4_3_ATCACGACAACAACCT CL:1001319       0          0          0
⋮                         ⋮                ⋮          ⋮          ⋮
10X_P7_7_TGTTCCGAGCTAACTC CL:1001428       0          0          0
10X_P7_7_TGTTCCGAGCTCCCAG CL:1001428       0          0          0
10X_P7_7_TTAACTCGTCTCTTTA CL:1001428       0          0          0
10X_P7_7_TTAACTCTCAGAGACG CL:1001428       0          0          0
10X_P7_7_TTAGGACAGACAAAGG CL:1001319       0          0          0
10X_P7_7_TTAGGACCAGGGTACA CL:1001428       0          0          0
10X_P7_7_TTAGGACGTCTCCCTA CL:1001319       0          0          0
10X_P7_7_TTATGCTAGCCATCGC CL:1001428       0          0          0
10X_P7_7_TTATGCTCAGATGAGC CL:1001428       0          0          0
10X_P7_7_TTATGCTCAGCGTTCG CL:0000738       0          0          0
10X_P7_7_TTATGCTTCCGAACGC CL:0000738       0          0          0
10X_P7_7_TTATGCTTCCGCGGTA CL:1001319       0          0          0
10X_P7_7_TTCCCAGTCATGTGGT CL:1001428       0          0          0
10X_P7_7_TTCGGTCAGTGCGTGA CL:1001319       0          0          0
10X_P7_7_TTCGGTCCAGCGTAAG CL:1001428       0          0          0
10X_P7_7_TTCGGTCTCCGGGTGT CL:1001319       0          0          0
10X_P7_7_TTCTCAAAGAGCCCAA CL:1001428       0          0          0
10X_P7_7_TTCTCAACAAACGTGG CL:1001319       0          0          0
10X_P7_7_TTGAACGAGATGTCGG CL:1001319       0          0          0
10X_P7_7_TTGCGTCCAAAGTGCG CL:1001319       0          0          0
10X_P7_7_TTGCGTCGTAGGACAC CL:1001428       0          0          0
10X_P7_7_TTGGAACAGTAGATGT CL:1001319       0          0          0
10X_P7_7_TTGGAACGTCTAGTCA CL:1001319       0          0          0
10X_P7_7_TTGGAACGTGTCGCTG CL:1001428       0          0          0
10X_P7_7_TTGTAGGCACTTGGAT CL:0000115       0          0          0
10X_P7_7_TTGTAGGTCATGTAGC CL:1001428       0          0          0
10X_P7_7_TTTACTGGTGTTGAGG CL:1001319       0          0          0
10X_P7_7_TTTCCTCCATACCATG CL:1001319       0          0          0
10X_P7_7_TTTGTCAGTTACCGAT CL:1001428       0          0          0
10X_P7_7_TTTGTCATCTGTGCAA CL:1001428       0          0          0
                          percent.plat Doublet_score Is_doublet
10X_P4_3_AAAGTAGAGATGCCAG 0            NA            FALSE
10X_P4_3_AACCGCGTCCAACCAA 0            NA            FALSE
10X_P4_3_AACTCCCGTCGGGTCT 0            NA            FALSE
10X_P4_3_AACTCTTAGTTGCAGG 0            NA            FALSE
10X_P4_3_AACTCTTTCATAACCG 0            NA            FALSE
10X_P4_3_AAGACCTAGATCCGAG 0            NA            FALSE
10X_P4_3_AAGACCTAGGTGGGTT 0            NA            FALSE
10X_P4_3_AAGGAGCGTGCAACTT 0            NA            FALSE
10X_P4_3_AAGTCTGAGATAGTCA 0            NA            FALSE
10X_P4_3_ACAGCTATCATACGGT 0            NA            FALSE
10X_P4_3_ACATACGCAGCTCCGA 0            NA            FALSE
10X_P4_3_ACCAGTACACGTCTCT 0            NA            FALSE
10X_P4_3_ACGAGCCAGATAGCAT 0            NA            FALSE
10X_P4_3_ACGGAGATCGGAATCT 0            NA            FALSE
10X_P4_3_ACGGGCTGTCTGATCA 0            NA            FALSE
10X_P4_3_ACTGAACCATCCGGGT 0            NA            FALSE
10X_P4_3_ACTTTCAAGATGGGTC 0            NA            FALSE
10X_P4_3_AGACGTTTCTTACCGC 0            NA            FALSE

In [39]:
srat_qc@meta.data <- .regularise_df(srat_qc@meta.data, drop_single_values = FALSE)
srat_qc@meta.data

                          orig.ident nCount_RNA nFeature_RNA channel  tissue
10X_P4_3_AAAGTAGAGATGCCAG 10X        10291      2853         10X_P4_3 Bladder
10X_P4_3_AACCGCGTCCAACCAA 10X        17520      4194         10X_P4_3 Bladder
10X_P4_3_AACTCCCGTCGGGTCT 10X        12944      3347         10X_P4_3 Bladder
10X_P4_3_AACTCTTAGTTGCAGG 10X        19594      3851         10X_P4_3 Bladder
10X_P4_3_AACTCTTTCATAACCG 10X        14594      3809         10X_P4_3 Bladder
10X_P4_3_AAGACCTAGATCCGAG 10X        19190      3608         10X_P4_3 Bladder
10X_P4_3_AAGACCTAGGTGGGTT 10X        24484      4347         10X_P4_3 Bladder
10X_P4_3_AAGGAGCGTGCAACTT 10X         5005      1960         10X_P4_3 Bladder
10X_P4_3_AAGTCTGAGATAGTCA 10X         6253      2236         10X_P4_3 Bladder
10X_P4_3_ACAGCTATCATACGGT 10X        15910      3374         10X_P4_3 Bladder
10X_P4_3_ACATACGCAGCTCCGA 10X         2881      1558         10X_P4_3 Bladder
10X_P4_3_ACCAGTACACGTCTCT 10X         6894      2348         10X_P4_3 Bladder
10X_P4_3_ACGAGCCAGATAGCAT 10X         9658      3141         10X_P4_3 Bladder
10X_P4_3_ACGGAGATCGGAATCT 10X        11623      3357         10X_P4_3 Bladder
10X_P4_3_ACGGGCTGTCTGATCA 10X         6878      2285         10X_P4_3 Bladder
10X_P4_3_ACTGAACCATCCGGGT 10X         7428      2319         10X_P4_3 Bladder
10X_P4_3_ACTTTCAAGATGGGTC 10X        10302      2875         10X_P4_3 Bladder
10X_P4_3_AGACGTTTCTTACCGC 10X        10187      3197         10X_P4_3 Bladder
10X_P4_3_AGAGCTTTCTGTTGAG 10X        25039      4812         10X_P4_3 Bladder
10X_P4_3_AGCGGTCTCTGAGTGT 10X        23497      4152         10X_P4_3 Bladder
10X_P4_3_AGCTTGAAGACTAAGT 10X         3102      1431         10X_P4_3 Bladder
10X_P4_3_AGGGAGTCAATCGGTT 10X         6981      2323         10X_P4_3 Bladder
10X_P4_3_AGGGATGAGTCGCCGT 10X         5259      1975         10X_P4_3 Bladder
10X_P4_3_AGGGTGACAGTCGTGC 10X        11231      3314         10X_P4_3 Bladder
10X_P4_3_AGGTCCGAGGACACCA 10X        26565      5040         10X_P4_3 Bladder
10X_P4_3_AGTCTTTAGCTAGTGG 10X         2277      1098         10X_P4_3 Bladder
10X_P4_3_AGTGAGGAGTGTACTC 10X         4800      1888         10X_P4_3 Bladder
10X_P4_3_AGTGAGGTCAGCATGT 10X        19882      3884         10X_P4_3 Bladder
10X_P4_3_AGTGTCACAGTATCTG 10X         6171      2299         10X_P4_3 Bladder
10X_P4_3_ATCACGACAACAACCT 10X        14113      3699         10X_P4_3 Bladder
⋮                         ⋮          ⋮          ⋮            ⋮        ⋮
10X_P7_7_TGTTCCGAGCTAACTC 10X        23228      4255         10X_P7_7 Bladder
10X_P7_7_TGTTCCGAGCTCCCAG 10X        42860      5745         10X_P7_7 Bladder
10X_P7_7_TTAACTCGTCTCTTTA 10X        35751      5422         10X_P7_7 Bladder
10X_P7_7_TTAACTCTCAGAGACG 10X        31618      4440         10X_P7_7 Bladder
10X_P7_7_TTAGGACAGACAAAGG 10X         9988      3201         10X_P7_7 Bladder
10X_P7_7_TTAGGACCAGGGTACA 10X        11756      2880         10X_P7_7 Bladder
10X_P7_7_TTAGGACGTCTCCCTA 10X         8516      2732         10X_P7_7 Bladder
10X_P7_7_TTATGCTAGCCATCGC 10X        14870      3657         10X_P7_7 Bladder
10X_P7_7_TTATGCTCAGATGAGC 10X        16126      3372         10X_P7_7 Bladder
10X_P7_7_TTATGCTCAGCGTTCG 10X         4938      1528         10X_P7_7 Bladder
10X_P7_7_TTATGCTTCCGAACGC 10X        11558      2319         10X_P7_7 Bladder
10X_P7_7_TTATGCTTCCGCGGTA 10X         6376      2580         10X_P7_7 Bladder
10X_P7_7_TTCCCAGTCATGTGGT 10X        34918      5002         10X_P7_7 Bladder
10X_P7_7_TTCGGTCAGTGCGTGA 10X        14304      3511         10X_P7_7 Bladder
10X_P7_7_TTCGGTCCAGCGTAAG 10X        22793      4562         10X_P7_7 Bladder
10X_P7_7_TTCGGTCTCCGGGTGT 10X         8380      2764         10X_P7_7 Bladder
10X_P7_7_TTCTCAAAGAGCCCAA 10X        37286      5356         10X_P7_7 Bladder
10X_P7_7_TTCTCAACAAACGTGG 10X        14565      3769         10X_P7_7 Bladder
10X_P7_7_TTGAACGAGATGTCGG 10X         9558      2972         10X_P7_7 Bladder
10X_P7_7_TTGCGTCCAAAGTGCG 10X        11456      3241         10X_P7_7 Bladder
10X_P7_7_TTGCGTCGTAGGACAC 10X        21269      3633         10X_P7_7 Bladder
10X_P7_7_TTGGAACAGTAGATGT 10X         8974      2831         10X_P7_7 Bladder
10X_P7_7_TTGGAACGTCTAGTCA 10X         6607      2546         10X_P7_7 Bladder
10X_P7_7_TTGGAACGTGTCGCTG 10X        50069      5641         10X_P7_7 Bladder
10X_P7_7_TTGTAGGCACTTGGAT 10X         9666      3087         10X_P7_7 Bladder
10X_P7_7_TTGTAGGTCATGTAGC 10X        22993      4296         10X_P7_7 Bladder
10X_P7_7_TTTACTGGTGTTGAGG 10X         8753      3005         10X_P7_7 Bladder
10X_P7_7_TTTCCTCCATACCATG 10X        14665      3778         10X_P7_7 Bladder
10X_P7_7_TTTGTCAGTTACCGAT 10X        30363      4786         10X_P7_7 Bladder
10X_P7_7_TTTGTCATCTGTGCAA 10X        16524      3979         10X_P7_7 Bladder
                          subtissue mouse.sex mouse.id percent.ercc
10X_P4_3_AAAGTAGAGATGCCAG           M         3-M-8    0
10X_P4_3_AACCGCGTCCAACCAA           M         3-M-8    0
10X_P4_3_AACTCCCGTCGGGTCT           M         3-M-8    0
10X_P4_3_AACTCTTAGTTGCAGG           M         3-M-8    0
10X_P4_3_AACTCTTTCATAACCG           M         3-M-8    0
10X_P4_3_AAGACCTAGATCCGAG           M         3-M-8    0
10X_P4_3_AAGACCTAGGTGGGTT           M         3-M-8    0
10X_P4_3_AAGGAGCGTGCAACTT           M         3-M-8    0
10X_P4_3_AAGTCTGAGATAGTCA           M         3-M-8    0
10X_P4_3_ACAGCTATCATACGGT           M         3-M-8    0
10X_P4_3_ACATACGCAGCTCCGA           M         3-M-8    0
10X_P4_3_ACCAGTACACGTCTCT           M         3-M-8    0
10X_P4_3_ACGAGCCAGATAGCAT           M         3-M-8    0
10X_P4_3_ACGGAGATCGGAATCT           M         3-M-8    0
10X_P4_3_ACGGGCTGTCTGATCA           M         3-M-8    0
10X_P4_3_ACTGAACCATCCGGGT           M         3-M-8    0
10X_P4_3_ACTTTCAAGATGGGTC           M         3-M-8    0
10X_P4_3_AGACGTTTCTTACCGC           M         3-M-8    0
10X_P4_3_AGAGCTTTCTGTTGAG           M         3-M-8    0
10X_P4_3_AGCGGTCTCTGAGTGT           M         3-M-8    0
10X_P4_3_AGCTTGAAGACTAAGT           M         3-M-8    0
10X_P4_3_AGGGAGTCAATCGGTT           M         3-M-8    0
10X_P4_3_AGGGATGAGTCGCCGT           M         3-M-8    0
10X_P4_3_AGGGTGACAGTCGTGC           M         3-M-8    0
10X_P4_3_AGGTCCGAGGACACCA           M         3-M-8    0
10X_P4_3_AGTCTTTAGCTAGTGG           M         3-M-8    0
10X_P4_3_AGTGAGGAGTGTACTC           M         3-M-8    0
10X_P4_3_AGTGAGGTCAGCATGT           M         3-M-8    0
10X_P4_3_AGTGTCACAGTATCTG           M         3-M-8    0
10X_P4_3_ATCACGACAACAACCT           M         3-M-8    0
⋮                         ⋮         ⋮         ⋮        ⋮
10X_P7_7_TGTTCCGAGCTAACTC           F         3-F-56   0
10X_P7_7_TGTTCCGAGCTCCCAG           F         3-F-56   0
10X_P7_7_TTAACTCGTCTCTTTA           F         3-F-56   0
10X_P7_7_TTAACTCTCAGAGACG           F         3-F-56   0
10X_P7_7_TTAGGACAGACAAAGG           F         3-F-56   0
10X_P7_7_TTAGGACCAGGGTACA           F         3-F-56   0
10X_P7_7_TTAGGACGTCTCCCTA           F         3-F-56   0
10X_P7_7_TTATGCTAGCCATCGC           F         3-F-56   0
10X_P7_7_TTATGCTCAGATGAGC           F         3-F-56   0
10X_P7_7_TTATGCTCAGCGTTCG           F         3-F-56   0
10X_P7_7_TTATGCTTCCGAACGC           F         3-F-56   0
10X_P7_7_TTATGCTTCCGCGGTA           F         3-F-56   0
10X_P7_7_TTCCCAGTCATGTGGT           F         3-F-56   0
10X_P7_7_TTCGGTCAGTGCGTGA           F         3-F-56   0
10X_P7_7_TTCGGTCCAGCGTAAG           F         3-F-56   0
10X_P7_7_TTCGGTCTCCGGGTGT           F         3-F-56   0
10X_P7_7_TTCTCAAAGAGCCCAA           F         3-F-56   0
10X_P7_7_TTCTCAACAAACGTGG           F         3-F-56   0
10X_P7_7_TTGAACGAGATGTCGG           F         3-F-56   0
10X_P7_7_TTGCGTCCAAAGTGCG           F         3-F-56   0
10X_P7_7_TTGCGTCGTAGGACAC           F         3-F-56   0
10X_P7_7_TTGGAACAGTAGATGT           F         3-F-56   0
10X_P7_7_TTGGAACGTCTAGTCA           F         3-F-56   0
10X_P7_7_TTGGAACGTGTCGCTG           F         3-F-56   0
10X_P7_7_TTGTAGGCACTTGGAT           F         3-F-56   0
10X_P7_7_TTGTAGGTCATGTAGC           F         3-F-56   0
10X_P7_7_TTTACTGGTGTTGAGG           F         3-F-56   0
10X_P7_7_TTTCCTCCATACCATG           F         3-F-56   0
10X_P7_7_TTTGTCAGTTACCGAT           F         3-F-56   0
10X_P7_7_TTTGTCATCTGTGCAA           F         3-F-56   0
                          percent.ribo ⋯ previous_free_annotation
10X_P4_3_AAAGTAGAGATGCCAG 0.21960937   ⋯ NA
10X_P4_3_AACCGCGTCCAACCAA 0.17671233   ⋯ NA
10X_P4_3_AACTCCCGTCGGGTCT 0.19244438   ⋯ NA
10X_P4_3_AACTCTTAGTTGCAGG 0.35638461   ⋯ NA
10X_P4_3_AACTCTTTCATAACCG 0.15711936   ⋯ NA
10X_P4_3_AAGACCTAGATCCGAG 0.23778009   ⋯ NA
10X_P4_3_AAGACCTAGGTGGGTT 0.32809182   ⋯ NA
10X_P4_3_AAGGAGCGTGCAACTT 0.19020979   ⋯ NA
10X_P4_3_AAGTCTGAGATAGTCA 0.22597153   ⋯ NA
10X_P4_3_ACAGCTATCATACGGT 0.33777498   ⋯ NA
10X_P4_3_ACATACGCAGCTCCGA 0.13259285   ⋯ NA
10X_P4_3_ACCAGTACACGTCTCT 0.20075428   ⋯ NA
10X_P4_3_ACGAGCCAGATAGCAT 0.16328432   ⋯ NA
10X_P4_3_ACGGAGATCGGAATCT 0.15701626   ⋯ NA
10X_P4_3_ACGGGCTGTCTGATCA 0.17214306   ⋯ NA
10X_P4_3_ACTGAACCATCCGGGT 0.17514809   ⋯ NA
10X_P4_3_ACTTTCAAGATGGGTC 0.31819064   ⋯ NA
10X_P4_3_AGACGTTTCTTACCGC 0.09207814   ⋯ NA
10X_P4_3_AGAGCTTTCTGTTGAG 0.18882543   ⋯ NA
10X_P4_3_AGCGGTCTCTGAGTGT 0.36498276   ⋯ NA
10X_P4_3_AGCTTGAAGACTAAGT 0.12250161   ⋯ NA
10X_P4_3_AGGGAGTCAATCGGTT 0.20369575   ⋯ NA
10X_P4_3_AGGGATGAGTCGCCGT 0.16600114   ⋯ NA
10X_P4_3_AGGGTGACAGTCGTGC 0.16222954   ⋯ NA
10X_P4_3_AGGTCCGAGGACACCA 0.27174854   ⋯ NA
10X_P4_3_AGTCTTTAGCTAGTGG 0.16161616   ⋯ NA
10X_P4_3_AGTGAGGAGTGTACTC 0.13708333   ⋯ NA
10X_P4_3_AGTGAGGTCAGCATGT 0.31520974   ⋯ NA
10X_P4_3_AGTGTCACAGTATCTG 0.11181332   ⋯ NA
10X_P4_3_ATCACGACAACAACCT 0.14065046   ⋯ NA
⋮                         ⋮            ⋱ ⋮
10X_P7_7_TGTTCCGAGCTAACTC 0.34092475   ⋯ NA
10X_P7_7_TGTTCCGAGCTCCCAG 0.37134858   ⋯ NA
10X_P7_7_TTAACTCGTCTCTTTA 0.24913988   ⋯ NA
10X_P7_7_TTAACTCTCAGAGACG 0.34100829   ⋯ NA
10X_P7_7_TTAGGACAGACAAAGG 0.14717661   ⋯ NA
10X_P7_7_TTAGGACCAGGGTACA 0.31405240   ⋯ NA
10X_P7_7_TTAGGACGTCTCCCTA 0.14560827   ⋯ NA
10X_P7_7_TTATGCTAGCCATCGC 0.32313383   ⋯ NA
10X_P7_7_TTATGCTCAGATGAGC 0.26851048   ⋯ NA
10X_P7_7_TTATGCTCAGCGTTCG 0.04597003   ⋯ NA
10X_P7_7_TTATGCTTCCGAACGC 0.11792698   ⋯ NA
10X_P7_7_TTATGCTTCCGCGGTA 0.12531368   ⋯ NA
10X_P7_7_TTCCCAGTCATGTGGT 0.29950169   ⋯ NA
10X_P7_7_TTCGGTCAGTGCGTGA 0.16072427   ⋯ NA
10X_P7_7_TTCGGTCCAGCGTAAG 0.24985741   ⋯ NA
10X_P7_7_TTCGGTCTCCGGGTGT 0.14439141   ⋯ NA
10X_P7_7_TTCTCAAAGAGCCCAA 0.36834201   ⋯ NA
10X_P7_7_TTCTCAACAAACGTGG 0.11342259   ⋯ NA
10X_P7_7_TTGAACGAGATGTCGG 0.16970077   ⋯ NA
10X_P7_7_TTGCGTCCAAAGTGCG 0.16096369   ⋯ NA
10X_P7_7_TTGCGTCGTAGGACAC 0.34331656   ⋯ NA
10X_P7_7_TTGGAACAGTAGATGT 0.13527970   ⋯ NA
10X_P7_7_TTGGAACGTCTAGTCA 0.13319207   ⋯ NA
10X_P7_7_TTGGAACGTGTCGCTG 0.40040744   ⋯ NA
10X_P7_7_TTGTAGGCACTTGGAT 0.10862818   ⋯ NA
10X_P7_7_TTGTAGGTCATGTAGC 0.28678293   ⋯ NA
10X_P7_7_TTTACTGGTGTTGAGG 0.12087284   ⋯ NA
10X_P7_7_TTTCCTCCATACCATG 0.11817252   ⋯ NA
10X_P7_7_TTTGTCAGTTACCGAT 0.30701841   ⋯ NA
10X_P7_7_TTTGTCATCTGTGCAA 0.29950375   ⋯ NA
                          previous_cell_ontology_class cluster.ids
10X_P4_3_AAAGTAGAGATGCCAG NA                           0
10X_P4_3_AACCGCGTCCAACCAA NA                           2
10X_P4_3_AACTCCCGTCGGGTCT NA                           5
10X_P4_3_AACTCTTAGTTGCAGG NA                           3
10X_P4_3_AACTCTTTCATAACCG NA                           2
10X_P4_3_AAGACCTAGATCCGAG NA                           6
10X_P4_3_AAGACCTAGGTGGGTT NA                           1
10X_P4_3_AAGGAGCGTGCAACTT NA                           0
10X_P4_3_AAGTCTGAGATAGTCA NA                           4
10X_P4_3_ACAGCTATCATACGGT NA                           1
10X_P4_3_ACATACGCAGCTCCGA NA                           4
10X_P4_3_ACCAGTACACGTCTCT NA                           0
10X_P4_3_ACGAGCCAGATAGCAT NA                           0
10X_P4_3_ACGGAGATCGGAATCT NA                           2
10X_P4_3_ACGGGCTGTCTGATCA NA                           0
10X_P4_3_ACTGAACCATCCGGGT NA                           0
10X_P4_3_ACTTTCAAGATGGGTC NA                           1
10X_P4_3_AGACGTTTCTTACCGC NA                           5
10X_P4_3_AGAGCTTTCTGTTGAG NA                           2
10X_P4_3_AGCGGTCTCTGAGTGT NA                           1
10X_P4_3_AGCTTGAAGACTAAGT NA                           0
10X_P4_3_AGGGAGTCAATCGGTT NA                           0
10X_P4_3_AGGGATGAGTCGCCGT NA                           0
10X_P4_3_AGGGTGACAGTCGTGC NA                           0
10X_P4_3_AGGTCCGAGGACACCA NA                           1
10X_P4_3_AGTCTTTAGCTAGTGG NA                           0
10X_P4_3_AGTGAGGAGTGTACTC NA                           0
10X_P4_3_AGTGAGGTCAGCATGT NA                           1
10X_P4_3_AGTGTCACAGTATCTG NA                           5
10X_P4_3_ATCACGACAACAACCT NA                           2
⋮                         ⋮                            ⋮
10X_P7_7_TGTTCCGAGCTAACTC NA                           1
10X_P7_7_TGTTCCGAGCTCCCAG NA                           1
10X_P7_7_TTAACTCGTCTCTTTA NA                           1
10X_P7_7_TTAACTCTCAGAGACG NA                           4
10X_P7_7_TTAGGACAGACAAAGG NA                           5
10X_P7_7_TTAGGACCAGGGTACA NA                           1
10X_P7_7_TTAGGACGTCTCCCTA NA                           5
10X_P7_7_TTATGCTAGCCATCGC NA                           1
10X_P7_7_TTATGCTCAGATGAGC NA                           4
10X_P7_7_TTATGCTCAGCGTTCG NA                           6
10X_P7_7_TTATGCTTCCGAACGC NA                           6
10X_P7_7_TTATGCTTCCGCGGTA NA                           0
10X_P7_7_TTCCCAGTCATGTGGT NA                           1
10X_P7_7_TTCGGTCAGTGCGTGA NA                           5
10X_P7_7_TTCGGTCCAGCGTAAG NA                           1
10X_P7_7_TTCGGTCTCCGGGTGT NA                           5
10X_P7_7_TTCTCAAAGAGCCCAA NA                           1
10X_P7_7_TTCTCAACAAACGTGG NA                           5
10X_P7_7_TTGAACGAGATGTCGG NA                           5
10X_P7_7_TTGCGTCCAAAGTGCG NA                           5
10X_P7_7_TTGCGTCGTAGGACAC NA                           1
10X_P7_7_TTGGAACAGTAGATGT NA                           5
10X_P7_7_TTGGAACGTCTAGTCA NA                           0
10X_P7_7_TTGGAACGTGTCGCTG NA                           4
10X_P7_7_TTGTAGGCACTTGGAT NA                           7
10X_P7_7_TTGTAGGTCATGTAGC NA                           1
10X_P7_7_TTTACTGGTGTTGAGG NA                           5
10X_P7_7_TTTCCTCCATACCATG NA                           5
10X_P7_7_TTTGTCAGTTACCGAT NA                           1
10X_P7_7_TTTGTCATCTGTGCAA NA                           1
                          cell_ontology_id percent.mt percent.rb percent.hb
10X_P4_3_AAAGTAGAGATGCCAG CL:1001319       0          0          0
10X_P4_3_AACCGCGTCCAACCAA CL:1001319       0          0          0
10X_P4_3_AACTCCCGTCGGGTCT CL:1001319       0          0          0
10X_P4_3_AACTCTTAGTTGCAGG CL:1001428       0          0          0
10X_P4_3_AACTCTTTCATAACCG CL:1001319       0          0          0
10X_P4_3_AAGACCTAGATCCGAG CL:0000738       0          0          0
10X_P4_3_AAGACCTAGGTGGGTT CL:1001428       0          0          0
10X_P4_3_AAGGAGCGTGCAACTT CL:1001319       0          0          0
10X_P4_3_AAGTCTGAGATAGTCA CL:1001428       0          0          0
10X_P4_3_ACAGCTATCATACGGT CL:1001428       0          0          0
10X_P4_3_ACATACGCAGCTCCGA CL:1001428       0          0          0
10X_P4_3_ACCAGTACACGTCTCT CL:1001319       0          0          0
10X_P4_3_ACGAGCCAGATAGCAT CL:1001319       0          0          0
10X_P4_3_ACGGAGATCGGAATCT CL:1001319       0          0          0
10X_P4_3_ACGGGCTGTCTGATCA CL:1001319       0          0          0
10X_P4_3_ACTGAACCATCCGGGT CL:1001319       0          0          0
10X_P4_3_ACTTTCAAGATGGGTC CL:1001428       0          0          0
10X_P4_3_AGACGTTTCTTACCGC CL:1001319       0          0          0
10X_P4_3_AGAGCTTTCTGTTGAG CL:1001319       0          0          0
10X_P4_3_AGCGGTCTCTGAGTGT CL:1001428       0          0          0
10X_P4_3_AGCTTGAAGACTAAGT CL:1001319       0          0          0
10X_P4_3_AGGGAGTCAATCGGTT CL:1001319       0          0          0
10X_P4_3_AGGGATGAGTCGCCGT CL:1001319       0          0          0
10X_P4_3_AGGGTGACAGTCGTGC CL:1001319       0          0          0
10X_P4_3_AGGTCCGAGGACACCA CL:1001428       0          0          0
10X_P4_3_AGTCTTTAGCTAGTGG CL:1001319       0          0          0
10X_P4_3_AGTGAGGAGTGTACTC CL:1001319       0          0          0
10X_P4_3_AGTGAGGTCAGCATGT CL:1001428       0          0          0
10X_P4_3_AGTGTCACAGTATCTG CL:1001319       0          0          0
10X_P4_3_ATCACGACAACAACCT CL:1001319       0          0          0
⋮                         ⋮                ⋮          ⋮          ⋮
10X_P7_7_TGTTCCGAGCTAACTC CL:1001428       0          0          0
10X_P7_7_TGTTCCGAGCTCCCAG CL:1001428       0          0          0
10X_P7_7_TTAACTCGTCTCTTTA CL:1001428       0          0          0
10X_P7_7_TTAACTCTCAGAGACG CL:1001428       0          0          0
10X_P7_7_TTAGGACAGACAAAGG CL:1001319       0          0          0
10X_P7_7_TTAGGACCAGGGTACA CL:1001428       0          0          0
10X_P7_7_TTAGGACGTCTCCCTA CL:1001319       0          0          0
10X_P7_7_TTATGCTAGCCATCGC CL:1001428       0          0          0
10X_P7_7_TTATGCTCAGATGAGC CL:1001428       0          0          0
10X_P7_7_TTATGCTCAGCGTTCG CL:0000738       0          0          0
10X_P7_7_TTATGCTTCCGAACGC CL:0000738       0          0          0
10X_P7_7_TTATGCTTCCGCGGTA CL:1001319       0          0          0
10X_P7_7_TTCCCAGTCATGTGGT CL:1001428       0          0          0
10X_P7_7_TTCGGTCAGTGCGTGA CL:1001319       0          0          0
10X_P7_7_TTCGGTCCAGCGTAAG CL:1001428       0          0          0
10X_P7_7_TTCGGTCTCCGGGTGT CL:1001319       0          0          0
10X_P7_7_TTCTCAAAGAGCCCAA CL:1001428       0          0          0
10X_P7_7_TTCTCAACAAACGTGG CL:1001319       0          0          0
10X_P7_7_TTGAACGAGATGTCGG CL:1001319       0          0          0
10X_P7_7_TTGCGTCCAAAGTGCG CL:1001319       0          0          0
10X_P7_7_TTGCGTCGTAGGACAC CL:1001428       0          0          0
10X_P7_7_TTGGAACAGTAGATGT CL:1001319       0          0          0
10X_P7_7_TTGGAACGTCTAGTCA CL:1001319       0          0          0
10X_P7_7_TTGGAACGTGTCGCTG CL:1001428       0          0          0
10X_P7_7_TTGTAGGCACTTGGAT CL:0000115       0          0          0
10X_P7_7_TTGTAGGTCATGTAGC CL:1001428       0          0          0
10X_P7_7_TTTACTGGTGTTGAGG CL:1001319       0          0          0
10X_P7_7_TTTCCTCCATACCATG CL:1001319       0          0          0
10X_P7_7_TTTGTCAGTTACCGAT CL:1001428       0          0          0
10X_P7_7_TTTGTCATCTGTGCAA CL:1001428       0          0          0
                          percent.plat Doublet_score Is_doublet
10X_P4_3_AAAGTAGAGATGCCAG 0            NA            FALSE
10X_P4_3_AACCGCGTCCAACCAA 0            NA            FALSE
10X_P4_3_AACTCCCGTCGGGTCT 0            NA            FALSE
10X_P4_3_AACTCTTAGTTGCAGG 0            NA            FALSE
10X_P4_3_AACTCTTTCATAACCG 0            NA            FALSE
10X_P4_3_AAGACCTAGATCCGAG 0            NA            FALSE
10X_P4_3_AAGACCTAGGTGGGTT 0            NA            FALSE
10X_P4_3_AAGGAGCGTGCAACTT 0            NA            FALSE
10X_P4_3_AAGTCTGAGATAGTCA 0            NA            FALSE
10X_P4_3_ACAGCTATCATACGGT 0            NA            FALSE
10X_P4_3_ACATACGCAGCTCCGA 0            NA            FALSE
10X_P4_3_ACCAGTACACGTCTCT 0            NA            FALSE
10X_P4_3_ACGAGCCAGATAGCAT 0            NA            FALSE
10X_P4_3_ACGGAGATCGGAATCT 0            NA            FALSE
10X_P4_3_ACGGGCTGTCTGATCA 0            NA            FALSE
10X_P4_3_ACTGAACCATCCGGGT 0            NA            FALSE
10X_P4_3_ACTTTCAAGATGGGTC 0            NA            FALSE
10X_P4_3_AGACGTTTCTTACCGC 0            NA            FALSE

In [40]:
output_path <- '/ps/ai-ready/data/Clustering/Tabula_Muris/droplet_Bladder_seurat_tiss.h5Seurat'
SaveH5Seurat(srat_qc, filename = output_path, overwrite = TRUE, verbose = TRUE)
srat_3 <- LoadH5Seurat(output_path)
srat_3

Warning message:
“Overwriting previous file /ps/ai-ready/data/Clustering/Tabula_Muris/droplet_Bladder_seurat_tiss.h5Seurat”
Creating h5Seurat file for version 3.1.5.9900

Adding counts for RNA

Adding data for RNA

No variable features found for RNA

No feature-level metadata found for RNA

Validating h5Seurat file

Initializing RNA with data

Adding counts for RNA

Adding miscellaneous information for RNA

Adding command information

Adding cell-level metadata

ERROR: Error in args_regularity_evaluation(args = args, ds_dims = simple_extent$dims, : Number of arguments not equal to number of dimensions: 1 vs. 2

In [37]:
output_path <- '/ps/ai-ready/data/Clustering/Tabula_Muris/droplet_Bladder_seurat_tiss.h5Seurat'
SaveH5Seurat(srat1, filename = output_path, overwrite = TRUE, verbose = TRUE)
srat_2 <- LoadH5Seurat(output_path)
srat_2

Warning message:
“Overwriting previous file /ps/ai-ready/data/Clustering/Tabula_Muris/droplet_Bladder_seurat_tiss.h5Seurat”
Creating h5Seurat file for version 3.1.5.9900

Adding counts for RNA

Adding data for RNA

No variable features found for RNA

No feature-level metadata found for RNA

Validating h5Seurat file

Initializing RNA with data

Adding counts for RNA

Adding miscellaneous information for RNA

Adding command information

Adding cell-level metadata

Adding miscellaneous information

Adding tool-specific results

An object of class Seurat
23341 features across 2500 samples within 1 assay
Active assay: RNA (23341 features, 0 variable features)

In [41]:
srat1[["meta.data"]]

ERROR: Error: Cannot find 'meta.data' in this Seurat object

In [27]:
srat1@meta.data

                          orig.ident nCount_RNA nFeature_RNA channel  tissue
10X_P4_3_AAAGTAGAGATGCCAG 10X        10291      2853         10X_P4_3 Bladder
10X_P4_3_AACCGCGTCCAACCAA 10X        17520      4194         10X_P4_3 Bladder
10X_P4_3_AACTCCCGTCGGGTCT 10X        12944      3347         10X_P4_3 Bladder
10X_P4_3_AACTCTTAGTTGCAGG 10X        19594      3851         10X_P4_3 Bladder
10X_P4_3_AACTCTTTCATAACCG 10X        14594      3809         10X_P4_3 Bladder
10X_P4_3_AAGACCTAGATCCGAG 10X        19190      3608         10X_P4_3 Bladder
10X_P4_3_AAGACCTAGGTGGGTT 10X        24484      4347         10X_P4_3 Bladder
10X_P4_3_AAGGAGCGTGCAACTT 10X         5005      1960         10X_P4_3 Bladder
10X_P4_3_AAGTCTGAGATAGTCA 10X         6253      2236         10X_P4_3 Bladder
10X_P4_3_ACAGCTATCATACGGT 10X        15910      3374         10X_P4_3 Bladder
10X_P4_3_ACATACGCAGCTCCGA 10X         2881      1558         10X_P4_3 Bladder
10X_P4_3_ACCAGTACACGTCTCT 10X         6894      2348         10X_P4_3 Bladder
10X_P4_3_ACGAGCCAGATAGCAT 10X         9658      3141         10X_P4_3 Bladder
10X_P4_3_ACGGAGATCGGAATCT 10X        11623      3357         10X_P4_3 Bladder
10X_P4_3_ACGGGCTGTCTGATCA 10X         6878      2285         10X_P4_3 Bladder
10X_P4_3_ACTGAACCATCCGGGT 10X         7428      2319         10X_P4_3 Bladder
10X_P4_3_ACTTTCAAGATGGGTC 10X        10302      2875         10X_P4_3 Bladder
10X_P4_3_AGACGTTTCTTACCGC 10X        10187      3197         10X_P4_3 Bladder
10X_P4_3_AGAGCTTTCTGTTGAG 10X        25039      4812         10X_P4_3 Bladder
10X_P4_3_AGCGGTCTCTGAGTGT 10X        23497      4152         10X_P4_3 Bladder
10X_P4_3_AGCTTGAAGACTAAGT 10X         3102      1431         10X_P4_3 Bladder
10X_P4_3_AGGGAGTCAATCGGTT 10X         6981      2323         10X_P4_3 Bladder
10X_P4_3_AGGGATGAGTCGCCGT 10X         5259      1975         10X_P4_3 Bladder
10X_P4_3_AGGGTGACAGTCGTGC 10X        11231      3314         10X_P4_3 Bladder
10X_P4_3_AGGTCCGAGGACACCA 10X        26565      5040         10X_P4_3 Bladder
10X_P4_3_AGTCTTTAGCTAGTGG 10X         2277      1098         10X_P4_3 Bladder
10X_P4_3_AGTGAGGAGTGTACTC 10X         4800      1888         10X_P4_3 Bladder
10X_P4_3_AGTGAGGTCAGCATGT 10X        19882      3884         10X_P4_3 Bladder
10X_P4_3_AGTGTCACAGTATCTG 10X         6171      2299         10X_P4_3 Bladder
10X_P4_3_ATCACGACAACAACCT 10X        14113      3699         10X_P4_3 Bladder
⋮                         ⋮          ⋮          ⋮            ⋮        ⋮
10X_P7_7_TGTTCCGAGCTAACTC 10X        23228      4255         10X_P7_7 Bladder
10X_P7_7_TGTTCCGAGCTCCCAG 10X        42860      5745         10X_P7_7 Bladder
10X_P7_7_TTAACTCGTCTCTTTA 10X        35751      5422         10X_P7_7 Bladder
10X_P7_7_TTAACTCTCAGAGACG 10X        31618      4440         10X_P7_7 Bladder
10X_P7_7_TTAGGACAGACAAAGG 10X         9988      3201         10X_P7_7 Bladder
10X_P7_7_TTAGGACCAGGGTACA 10X        11756      2880         10X_P7_7 Bladder
10X_P7_7_TTAGGACGTCTCCCTA 10X         8516      2732         10X_P7_7 Bladder
10X_P7_7_TTATGCTAGCCATCGC 10X        14870      3657         10X_P7_7 Bladder
10X_P7_7_TTATGCTCAGATGAGC 10X        16126      3372         10X_P7_7 Bladder
10X_P7_7_TTATGCTCAGCGTTCG 10X         4938      1528         10X_P7_7 Bladder
10X_P7_7_TTATGCTTCCGAACGC 10X        11558      2319         10X_P7_7 Bladder
10X_P7_7_TTATGCTTCCGCGGTA 10X         6376      2580         10X_P7_7 Bladder
10X_P7_7_TTCCCAGTCATGTGGT 10X        34918      5002         10X_P7_7 Bladder
10X_P7_7_TTCGGTCAGTGCGTGA 10X        14304      3511         10X_P7_7 Bladder
10X_P7_7_TTCGGTCCAGCGTAAG 10X        22793      4562         10X_P7_7 Bladder
10X_P7_7_TTCGGTCTCCGGGTGT 10X         8380      2764         10X_P7_7 Bladder
10X_P7_7_TTCTCAAAGAGCCCAA 10X        37286      5356         10X_P7_7 Bladder
10X_P7_7_TTCTCAACAAACGTGG 10X        14565      3769         10X_P7_7 Bladder
10X_P7_7_TTGAACGAGATGTCGG 10X         9558      2972         10X_P7_7 Bladder
10X_P7_7_TTGCGTCCAAAGTGCG 10X        11456      3241         10X_P7_7 Bladder
10X_P7_7_TTGCGTCGTAGGACAC 10X        21269      3633         10X_P7_7 Bladder
10X_P7_7_TTGGAACAGTAGATGT 10X         8974      2831         10X_P7_7 Bladder
10X_P7_7_TTGGAACGTCTAGTCA 10X         6607      2546         10X_P7_7 Bladder
10X_P7_7_TTGGAACGTGTCGCTG 10X        50069      5641         10X_P7_7 Bladder
10X_P7_7_TTGTAGGCACTTGGAT 10X         9666      3087         10X_P7_7 Bladder
10X_P7_7_TTGTAGGTCATGTAGC 10X        22993      4296         10X_P7_7 Bladder
10X_P7_7_TTTACTGGTGTTGAGG 10X         8753      3005         10X_P7_7 Bladder
10X_P7_7_TTTCCTCCATACCATG 10X        14665      3778         10X_P7_7 Bladder
10X_P7_7_TTTGTCAGTTACCGAT 10X        30363      4786         10X_P7_7 Bladder
10X_P7_7_TTTGTCATCTGTGCAA 10X        16524      3979         10X_P7_7 Bladder
                          subtissue mouse.sex mouse.id percent.ercc
10X_P4_3_AAAGTAGAGATGCCAG           M         3-M-8    0
10X_P4_3_AACCGCGTCCAACCAA           M         3-M-8    0
10X_P4_3_AACTCCCGTCGGGTCT           M         3-M-8    0
10X_P4_3_AACTCTTAGTTGCAGG           M         3-M-8    0
10X_P4_3_AACTCTTTCATAACCG           M         3-M-8    0
10X_P4_3_AAGACCTAGATCCGAG           M         3-M-8    0
10X_P4_3_AAGACCTAGGTGGGTT           M         3-M-8    0
10X_P4_3_AAGGAGCGTGCAACTT           M         3-M-8    0
10X_P4_3_AAGTCTGAGATAGTCA           M         3-M-8    0
10X_P4_3_ACAGCTATCATACGGT           M         3-M-8    0
10X_P4_3_ACATACGCAGCTCCGA           M         3-M-8    0
10X_P4_3_ACCAGTACACGTCTCT           M         3-M-8    0
10X_P4_3_ACGAGCCAGATAGCAT           M         3-M-8    0
10X_P4_3_ACGGAGATCGGAATCT           M         3-M-8    0
10X_P4_3_ACGGGCTGTCTGATCA           M         3-M-8    0
10X_P4_3_ACTGAACCATCCGGGT           M         3-M-8    0
10X_P4_3_ACTTTCAAGATGGGTC           M         3-M-8    0
10X_P4_3_AGACGTTTCTTACCGC           M         3-M-8    0
10X_P4_3_AGAGCTTTCTGTTGAG           M         3-M-8    0
10X_P4_3_AGCGGTCTCTGAGTGT           M         3-M-8    0
10X_P4_3_AGCTTGAAGACTAAGT           M         3-M-8    0
10X_P4_3_AGGGAGTCAATCGGTT           M         3-M-8    0
10X_P4_3_AGGGATGAGTCGCCGT           M         3-M-8    0
10X_P4_3_AGGGTGACAGTCGTGC           M         3-M-8    0
10X_P4_3_AGGTCCGAGGACACCA           M         3-M-8    0
10X_P4_3_AGTCTTTAGCTAGTGG           M         3-M-8    0
10X_P4_3_AGTGAGGAGTGTACTC           M         3-M-8    0
10X_P4_3_AGTGAGGTCAGCATGT           M         3-M-8    0
10X_P4_3_AGTGTCACAGTATCTG           M         3-M-8    0
10X_P4_3_ATCACGACAACAACCT           M         3-M-8    0
⋮                         ⋮         ⋮         ⋮        ⋮
10X_P7_7_TGTTCCGAGCTAACTC           F         3-F-56   0
10X_P7_7_TGTTCCGAGCTCCCAG           F         3-F-56   0
10X_P7_7_TTAACTCGTCTCTTTA           F         3-F-56   0
10X_P7_7_TTAACTCTCAGAGACG           F         3-F-56   0
10X_P7_7_TTAGGACAGACAAAGG           F         3-F-56   0
10X_P7_7_TTAGGACCAGGGTACA           F         3-F-56   0
10X_P7_7_TTAGGACGTCTCCCTA           F         3-F-56   0
10X_P7_7_TTATGCTAGCCATCGC           F         3-F-56   0
10X_P7_7_TTATGCTCAGATGAGC           F         3-F-56   0
10X_P7_7_TTATGCTCAGCGTTCG           F         3-F-56   0
10X_P7_7_TTATGCTTCCGAACGC           F         3-F-56   0
10X_P7_7_TTATGCTTCCGCGGTA           F         3-F-56   0
10X_P7_7_TTCCCAGTCATGTGGT           F         3-F-56   0
10X_P7_7_TTCGGTCAGTGCGTGA           F         3-F-56   0
10X_P7_7_TTCGGTCCAGCGTAAG           F         3-F-56   0
10X_P7_7_TTCGGTCTCCGGGTGT           F         3-F-56   0
10X_P7_7_TTCTCAAAGAGCCCAA           F         3-F-56   0
10X_P7_7_TTCTCAACAAACGTGG           F         3-F-56   0
10X_P7_7_TTGAACGAGATGTCGG           F         3-F-56   0
10X_P7_7_TTGCGTCCAAAGTGCG           F         3-F-56   0
10X_P7_7_TTGCGTCGTAGGACAC           F         3-F-56   0
10X_P7_7_TTGGAACAGTAGATGT           F         3-F-56   0
10X_P7_7_TTGGAACGTCTAGTCA           F         3-F-56   0
10X_P7_7_TTGGAACGTGTCGCTG           F         3-F-56   0
10X_P7_7_TTGTAGGCACTTGGAT           F         3-F-56   0
10X_P7_7_TTGTAGGTCATGTAGC           F         3-F-56   0
10X_P7_7_TTTACTGGTGTTGAGG           F         3-F-56   0
10X_P7_7_TTTCCTCCATACCATG           F         3-F-56   0
10X_P7_7_TTTGTCAGTTACCGAT           F         3-F-56   0
10X_P7_7_TTTGTCATCTGTGCAA           F         3-F-56   0
                          percent.ribo ⋯ previous_free_annotation
10X_P4_3_AAAGTAGAGATGCCAG 0.21960937   ⋯ NA
10X_P4_3_AACCGCGTCCAACCAA 0.17671233   ⋯ NA
10X_P4_3_AACTCCCGTCGGGTCT 0.19244438   ⋯ NA
10X_P4_3_AACTCTTAGTTGCAGG 0.35638461   ⋯ NA
10X_P4_3_AACTCTTTCATAACCG 0.15711936   ⋯ NA
10X_P4_3_AAGACCTAGATCCGAG 0.23778009   ⋯ NA
10X_P4_3_AAGACCTAGGTGGGTT 0.32809182   ⋯ NA
10X_P4_3_AAGGAGCGTGCAACTT 0.19020979   ⋯ NA
10X_P4_3_AAGTCTGAGATAGTCA 0.22597153   ⋯ NA
10X_P4_3_ACAGCTATCATACGGT 0.33777498   ⋯ NA
10X_P4_3_ACATACGCAGCTCCGA 0.13259285   ⋯ NA
10X_P4_3_ACCAGTACACGTCTCT 0.20075428   ⋯ NA
10X_P4_3_ACGAGCCAGATAGCAT 0.16328432   ⋯ NA
10X_P4_3_ACGGAGATCGGAATCT 0.15701626   ⋯ NA
10X_P4_3_ACGGGCTGTCTGATCA 0.17214306   ⋯ NA
10X_P4_3_ACTGAACCATCCGGGT 0.17514809   ⋯ NA
10X_P4_3_ACTTTCAAGATGGGTC 0.31819064   ⋯ NA
10X_P4_3_AGACGTTTCTTACCGC 0.09207814   ⋯ NA
10X_P4_3_AGAGCTTTCTGTTGAG 0.18882543   ⋯ NA
10X_P4_3_AGCGGTCTCTGAGTGT 0.36498276   ⋯ NA
10X_P4_3_AGCTTGAAGACTAAGT 0.12250161   ⋯ NA
10X_P4_3_AGGGAGTCAATCGGTT 0.20369575   ⋯ NA
10X_P4_3_AGGGATGAGTCGCCGT 0.16600114   ⋯ NA
10X_P4_3_AGGGTGACAGTCGTGC 0.16222954   ⋯ NA
10X_P4_3_AGGTCCGAGGACACCA 0.27174854   ⋯ NA
10X_P4_3_AGTCTTTAGCTAGTGG 0.16161616   ⋯ NA
10X_P4_3_AGTGAGGAGTGTACTC 0.13708333   ⋯ NA
10X_P4_3_AGTGAGGTCAGCATGT 0.31520974   ⋯ NA
10X_P4_3_AGTGTCACAGTATCTG 0.11181332   ⋯ NA
10X_P4_3_ATCACGACAACAACCT 0.14065046   ⋯ NA
⋮                         ⋮            ⋱ ⋮
10X_P7_7_TGTTCCGAGCTAACTC 0.34092475   ⋯ NA
10X_P7_7_TGTTCCGAGCTCCCAG 0.37134858   ⋯ NA
10X_P7_7_TTAACTCGTCTCTTTA 0.24913988   ⋯ NA
10X_P7_7_TTAACTCTCAGAGACG 0.34100829   ⋯ NA
10X_P7_7_TTAGGACAGACAAAGG 0.14717661   ⋯ NA
10X_P7_7_TTAGGACCAGGGTACA 0.31405240   ⋯ NA
10X_P7_7_TTAGGACGTCTCCCTA 0.14560827   ⋯ NA
10X_P7_7_TTATGCTAGCCATCGC 0.32313383   ⋯ NA
10X_P7_7_TTATGCTCAGATGAGC 0.26851048   ⋯ NA
10X_P7_7_TTATGCTCAGCGTTCG 0.04597003   ⋯ NA
10X_P7_7_TTATGCTTCCGAACGC 0.11792698   ⋯ NA
10X_P7_7_TTATGCTTCCGCGGTA 0.12531368   ⋯ NA
10X_P7_7_TTCCCAGTCATGTGGT 0.29950169   ⋯ NA
10X_P7_7_TTCGGTCAGTGCGTGA 0.16072427   ⋯ NA
10X_P7_7_TTCGGTCCAGCGTAAG 0.24985741   ⋯ NA
10X_P7_7_TTCGGTCTCCGGGTGT 0.14439141   ⋯ NA
10X_P7_7_TTCTCAAAGAGCCCAA 0.36834201   ⋯ NA
10X_P7_7_TTCTCAACAAACGTGG 0.11342259   ⋯ NA
10X_P7_7_TTGAACGAGATGTCGG 0.16970077   ⋯ NA
10X_P7_7_TTGCGTCCAAAGTGCG 0.16096369   ⋯ NA
10X_P7_7_TTGCGTCGTAGGACAC 0.34331656   ⋯ NA
10X_P7_7_TTGGAACAGTAGATGT 0.13527970   ⋯ NA
10X_P7_7_TTGGAACGTCTAGTCA 0.13319207   ⋯ NA
10X_P7_7_TTGGAACGTGTCGCTG 0.40040744   ⋯ NA
10X_P7_7_TTGTAGGCACTTGGAT 0.10862818   ⋯ NA
10X_P7_7_TTGTAGGTCATGTAGC 0.28678293   ⋯ NA
10X_P7_7_TTTACTGGTGTTGAGG 0.12087284   ⋯ NA
10X_P7_7_TTTCCTCCATACCATG 0.11817252   ⋯ NA
10X_P7_7_TTTGTCAGTTACCGAT 0.30701841   ⋯ NA
10X_P7_7_TTTGTCATCTGTGCAA 0.29950375   ⋯ NA
                          previous_cell_ontology_class cluster.ids
10X_P4_3_AAAGTAGAGATGCCAG NA                           0
10X_P4_3_AACCGCGTCCAACCAA NA                           2
10X_P4_3_AACTCCCGTCGGGTCT NA                           5
10X_P4_3_AACTCTTAGTTGCAGG NA                           3
10X_P4_3_AACTCTTTCATAACCG NA                           2
10X_P4_3_AAGACCTAGATCCGAG NA                           6
10X_P4_3_AAGACCTAGGTGGGTT NA                           1
10X_P4_3_AAGGAGCGTGCAACTT NA                           0
10X_P4_3_AAGTCTGAGATAGTCA NA                           4
10X_P4_3_ACAGCTATCATACGGT NA                           1
10X_P4_3_ACATACGCAGCTCCGA NA                           4
10X_P4_3_ACCAGTACACGTCTCT NA                           0
10X_P4_3_ACGAGCCAGATAGCAT NA                           0
10X_P4_3_ACGGAGATCGGAATCT NA                           2
10X_P4_3_ACGGGCTGTCTGATCA NA                           0
10X_P4_3_ACTGAACCATCCGGGT NA                           0
10X_P4_3_ACTTTCAAGATGGGTC NA                           1
10X_P4_3_AGACGTTTCTTACCGC NA                           5
10X_P4_3_AGAGCTTTCTGTTGAG NA                           2
10X_P4_3_AGCGGTCTCTGAGTGT NA                           1
10X_P4_3_AGCTTGAAGACTAAGT NA                           0
10X_P4_3_AGGGAGTCAATCGGTT NA                           0
10X_P4_3_AGGGATGAGTCGCCGT NA                           0
10X_P4_3_AGGGTGACAGTCGTGC NA                           0
10X_P4_3_AGGTCCGAGGACACCA NA                           1
10X_P4_3_AGTCTTTAGCTAGTGG NA                           0
10X_P4_3_AGTGAGGAGTGTACTC NA                           0
10X_P4_3_AGTGAGGTCAGCATGT NA                           1
10X_P4_3_AGTGTCACAGTATCTG NA                           5
10X_P4_3_ATCACGACAACAACCT NA                           2
⋮                         ⋮                            ⋮
10X_P7_7_TGTTCCGAGCTAACTC NA                           1
10X_P7_7_TGTTCCGAGCTCCCAG NA                           1
10X_P7_7_TTAACTCGTCTCTTTA NA                           1
10X_P7_7_TTAACTCTCAGAGACG NA                           4
10X_P7_7_TTAGGACAGACAAAGG NA                           5
10X_P7_7_TTAGGACCAGGGTACA NA                           1
10X_P7_7_TTAGGACGTCTCCCTA NA                           5
10X_P7_7_TTATGCTAGCCATCGC NA                           1
10X_P7_7_TTATGCTCAGATGAGC NA                           4
10X_P7_7_TTATGCTCAGCGTTCG NA                           6
10X_P7_7_TTATGCTTCCGAACGC NA                           6
10X_P7_7_TTATGCTTCCGCGGTA NA                           0
10X_P7_7_TTCCCAGTCATGTGGT NA                           1
10X_P7_7_TTCGGTCAGTGCGTGA NA                           5
10X_P7_7_TTCGGTCCAGCGTAAG NA                           1
10X_P7_7_TTCGGTCTCCGGGTGT NA                           5
10X_P7_7_TTCTCAAAGAGCCCAA NA                           1
10X_P7_7_TTCTCAACAAACGTGG NA                           5
10X_P7_7_TTGAACGAGATGTCGG NA                           5
10X_P7_7_TTGCGTCCAAAGTGCG NA                           5
10X_P7_7_TTGCGTCGTAGGACAC NA                           1
10X_P7_7_TTGGAACAGTAGATGT NA                           5
10X_P7_7_TTGGAACGTCTAGTCA NA                           0
10X_P7_7_TTGGAACGTGTCGCTG NA                           4
10X_P7_7_TTGTAGGCACTTGGAT NA                           7
10X_P7_7_TTGTAGGTCATGTAGC NA                           1
10X_P7_7_TTTACTGGTGTTGAGG NA                           5
10X_P7_7_TTTCCTCCATACCATG NA                           5
10X_P7_7_TTTGTCAGTTACCGAT NA                           1
10X_P7_7_TTTGTCATCTGTGCAA NA                           1
                          cell_ontology_id percent.mt percent.rb percent.hb
10X_P4_3_AAAGTAGAGATGCCAG CL:1001319       0          0          0
10X_P4_3_AACCGCGTCCAACCAA CL:1001319       0          0          0
10X_P4_3_AACTCCCGTCGGGTCT CL:1001319       0          0          0
10X_P4_3_AACTCTTAGTTGCAGG CL:1001428       0          0          0
10X_P4_3_AACTCTTTCATAACCG CL:1001319       0          0          0
10X_P4_3_AAGACCTAGATCCGAG CL:0000738       0          0          0
10X_P4_3_AAGACCTAGGTGGGTT CL:1001428       0          0          0
10X_P4_3_AAGGAGCGTGCAACTT CL:1001319       0          0          0
10X_P4_3_AAGTCTGAGATAGTCA CL:1001428       0          0          0
10X_P4_3_ACAGCTATCATACGGT CL:1001428       0          0          0
10X_P4_3_ACATACGCAGCTCCGA CL:1001428       0          0          0
10X_P4_3_ACCAGTACACGTCTCT CL:1001319       0          0          0
10X_P4_3_ACGAGCCAGATAGCAT CL:1001319       0          0          0
10X_P4_3_ACGGAGATCGGAATCT CL:1001319       0          0          0
10X_P4_3_ACGGGCTGTCTGATCA CL:1001319       0          0          0
10X_P4_3_ACTGAACCATCCGGGT CL:1001319       0          0          0
10X_P4_3_ACTTTCAAGATGGGTC CL:1001428       0          0          0
10X_P4_3_AGACGTTTCTTACCGC CL:1001319       0          0          0
10X_P4_3_AGAGCTTTCTGTTGAG CL:1001319       0          0          0
10X_P4_3_AGCGGTCTCTGAGTGT CL:1001428       0          0          0
10X_P4_3_AGCTTGAAGACTAAGT CL:1001319       0          0          0
10X_P4_3_AGGGAGTCAATCGGTT CL:1001319       0          0          0
10X_P4_3_AGGGATGAGTCGCCGT CL:1001319       0          0          0
10X_P4_3_AGGGTGACAGTCGTGC CL:1001319       0          0          0
10X_P4_3_AGGTCCGAGGACACCA CL:1001428       0          0          0
10X_P4_3_AGTCTTTAGCTAGTGG CL:1001319       0          0          0
10X_P4_3_AGTGAGGAGTGTACTC CL:1001319       0          0          0
10X_P4_3_AGTGAGGTCAGCATGT CL:1001428       0          0          0
10X_P4_3_AGTGTCACAGTATCTG CL:1001319       0          0          0
10X_P4_3_ATCACGACAACAACCT CL:1001319       0          0          0
⋮                         ⋮                ⋮          ⋮          ⋮
10X_P7_7_TGTTCCGAGCTAACTC CL:1001428       0          0          0
10X_P7_7_TGTTCCGAGCTCCCAG CL:1001428       0          0          0
10X_P7_7_TTAACTCGTCTCTTTA CL:1001428       0          0          0
10X_P7_7_TTAACTCTCAGAGACG CL:1001428       0          0          0
10X_P7_7_TTAGGACAGACAAAGG CL:1001319       0          0          0
10X_P7_7_TTAGGACCAGGGTACA CL:1001428       0          0          0
10X_P7_7_TTAGGACGTCTCCCTA CL:1001319       0          0          0
10X_P7_7_TTATGCTAGCCATCGC CL:1001428       0          0          0
10X_P7_7_TTATGCTCAGATGAGC CL:1001428       0          0          0
10X_P7_7_TTATGCTCAGCGTTCG CL:0000738       0          0          0
10X_P7_7_TTATGCTTCCGAACGC CL:0000738       0          0          0
10X_P7_7_TTATGCTTCCGCGGTA CL:1001319       0          0          0
10X_P7_7_TTCCCAGTCATGTGGT CL:1001428       0          0          0
10X_P7_7_TTCGGTCAGTGCGTGA CL:1001319       0          0          0
10X_P7_7_TTCGGTCCAGCGTAAG CL:1001428       0          0          0
10X_P7_7_TTCGGTCTCCGGGTGT CL:1001319       0          0          0
10X_P7_7_TTCTCAAAGAGCCCAA CL:1001428       0          0          0
10X_P7_7_TTCTCAACAAACGTGG CL:1001319       0          0          0
10X_P7_7_TTGAACGAGATGTCGG CL:1001319       0          0          0
10X_P7_7_TTGCGTCCAAAGTGCG CL:1001319       0          0          0
10X_P7_7_TTGCGTCGTAGGACAC CL:1001428       0          0          0
10X_P7_7_TTGGAACAGTAGATGT CL:1001319       0          0          0
10X_P7_7_TTGGAACGTCTAGTCA CL:1001319       0          0          0
10X_P7_7_TTGGAACGTGTCGCTG CL:1001428       0          0          0
10X_P7_7_TTGTAGGCACTTGGAT CL:0000115       0          0          0
10X_P7_7_TTGTAGGTCATGTAGC CL:1001428       0          0          0
10X_P7_7_TTTACTGGTGTTGAGG CL:1001319       0          0          0
10X_P7_7_TTTCCTCCATACCATG CL:1001319       0          0          0
10X_P7_7_TTTGTCAGTTACCGAT CL:1001428       0          0          0
10X_P7_7_TTTGTCATCTGTGCAA CL:1001428       0          0          0
                          percent.plat Doublet_score Is_doublet
10X_P4_3_AAAGTAGAGATGCCAG 0            NA            FALSE
10X_P4_3_AACCGCGTCCAACCAA 0            NA            FALSE
10X_P4_3_AACTCCCGTCGGGTCT 0            NA            FALSE
10X_P4_3_AACTCTTAGTTGCAGG 0            NA            FALSE
10X_P4_3_AACTCTTTCATAACCG 0            NA            FALSE
10X_P4_3_AAGACCTAGATCCGAG 0            NA            FALSE
10X_P4_3_AAGACCTAGGTGGGTT 0            NA            FALSE
10X_P4_3_AAGGAGCGTGCAACTT 0            NA            FALSE
10X_P4_3_AAGTCTGAGATAGTCA 0            NA            FALSE
10X_P4_3_ACAGCTATCATACGGT 0            NA            FALSE
10X_P4_3_ACATACGCAGCTCCGA 0            NA            FALSE
10X_P4_3_ACCAGTACACGTCTCT 0            NA            FALSE
10X_P4_3_ACGAGCCAGATAGCAT 0            NA            FALSE
10X_P4_3_ACGGAGATCGGAATCT 0            NA            FALSE
10X_P4_3_ACGGGCTGTCTGATCA 0            NA            FALSE
10X_P4_3_ACTGAACCATCCGGGT 0            NA            FALSE
10X_P4_3_ACTTTCAAGATGGGTC 0            NA            FALSE
10X_P4_3_AGACGTTTCTTACCGC 0            NA            FALSE

In [21]:
devtools::install_github("cellgeni/sceasy")

Downloading GitHub repo cellgeni/sceasy@HEAD

withr      (2.5.1  -> 2.5.2 ) [CRAN]
reticulate (1.32.0 -> 1.34.0) [CRAN]

Installing 2 packages: withr, reticulate

Installing packages into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

── R CMD build ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/tmp/Rtmp8bvg1x/remotes180a41f1cb63/cellgeni-sceasy-0cfc0e3/DESCRIPTION’ (379ms)
─  preparing ‘sceasy’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘sceasy_0.0.7.tar.gz’

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

In [22]:
sceasy::convertFormat(srat1, from="seurat", to="anndata",
                       outFile='/ps/ai-ready/data/Clustering/Tabula_Muris/droplet_Bladder_seurat_tiss.h5ad')

Warning message in .regularise_df(obj@meta.data, drop_single_values = drop_single_values):
“Dropping single category variables:orig.ident, tissue, subtissue, percent.ercc, previous_free_annotation, previous_cell_ontology_class, percent.mt, percent.rb, percent.hb, percent.plat, Doublet_score, Is_doublet”

AnnData object with n_obs × n_vars = 2500 × 23341
    obs: 'nCount_RNA', 'nFeature_RNA', 'channel', 'mouse.sex', 'mouse.id', 'percent.ribo', 'free_annotation', 'cell_ontology_class', 'res.0.4', 'cluster.ids', 'cell_ontology_id'
    var: 'name'

In [24]:
adata <- LoadAnndata('/ps/ai-ready/data/Clustering/Tabula_Muris/droplet_Bladder_seurat_tiss.h5ad')
adata

AnnData object with n_obs × n_vars = 2500 × 23341
    obs: 'nCount_RNA', 'nFeature_RNA', 'channel', 'mouse.sex', 'mouse.id', 'percent.ribo', 'free_annotation', 'cell_ontology_class', 'res.0.4', 'cluster.ids', 'cell_ontology_id'
    var: 'name'

In [26]:
adata$obs

                          nCount_RNA nFeature_RNA channel  mouse.sex mouse.id
10X_P4_3_AAAGTAGAGATGCCAG 10291      2853         10X_P4_3 M         3-M-8
10X_P4_3_AACCGCGTCCAACCAA 17520      4194         10X_P4_3 M         3-M-8
10X_P4_3_AACTCCCGTCGGGTCT 12944      3347         10X_P4_3 M         3-M-8
10X_P4_3_AACTCTTAGTTGCAGG 19594      3851         10X_P4_3 M         3-M-8
10X_P4_3_AACTCTTTCATAACCG 14594      3809         10X_P4_3 M         3-M-8
10X_P4_3_AAGACCTAGATCCGAG 19190      3608         10X_P4_3 M         3-M-8
10X_P4_3_AAGACCTAGGTGGGTT 24484      4347         10X_P4_3 M         3-M-8
10X_P4_3_AAGGAGCGTGCAACTT  5005      1960         10X_P4_3 M         3-M-8
10X_P4_3_AAGTCTGAGATAGTCA  6253      2236         10X_P4_3 M         3-M-8
10X_P4_3_ACAGCTATCATACGGT 15910      3374         10X_P4_3 M         3-M-8
10X_P4_3_ACATACGCAGCTCCGA  2881      1558         10X_P4_3 M         3-M-8
10X_P4_3_ACCAGTACACGTCTCT  6894      2348         10X_P4_3 M         3-M-8
10X_P4_3_ACGAGCCAGATAGCAT  9658      3141         10X_P4_3 M         3-M-8
10X_P4_3_ACGGAGATCGGAATCT 11623      3357         10X_P4_3 M         3-M-8
10X_P4_3_ACGGGCTGTCTGATCA  6878      2285         10X_P4_3 M         3-M-8
10X_P4_3_ACTGAACCATCCGGGT  7428      2319         10X_P4_3 M         3-M-8
10X_P4_3_ACTTTCAAGATGGGTC 10302      2875         10X_P4_3 M         3-M-8
10X_P4_3_AGACGTTTCTTACCGC 10187      3197         10X_P4_3 M         3-M-8
10X_P4_3_AGAGCTTTCTGTTGAG 25039      4812         10X_P4_3 M         3-M-8
10X_P4_3_AGCGGTCTCTGAGTGT 23497      4152         10X_P4_3 M         3-M-8
10X_P4_3_AGCTTGAAGACTAAGT  3102      1431         10X_P4_3 M         3-M-8
10X_P4_3_AGGGAGTCAATCGGTT  6981      2323         10X_P4_3 M         3-M-8
10X_P4_3_AGGGATGAGTCGCCGT  5259      1975         10X_P4_3 M         3-M-8
10X_P4_3_AGGGTGACAGTCGTGC 11231      3314         10X_P4_3 M         3-M-8
10X_P4_3_AGGTCCGAGGACACCA 26565      5040         10X_P4_3 M         3-M-8
10X_P4_3_AGTCTTTAGCTAGTGG  2277      1098         10X_P4_3 M         3-M-8
10X_P4_3_AGTGAGGAGTGTACTC  4800      1888         10X_P4_3 M         3-M-8
10X_P4_3_AGTGAGGTCAGCATGT 19882      3884         10X_P4_3 M         3-M-8
10X_P4_3_AGTGTCACAGTATCTG  6171      2299         10X_P4_3 M         3-M-8
10X_P4_3_ATCACGACAACAACCT 14113      3699         10X_P4_3 M         3-M-8
⋮                         ⋮          ⋮            ⋮        ⋮         ⋮
10X_P7_7_TGTTCCGAGCTAACTC 23228      4255         10X_P7_7 F         3-F-56
10X_P7_7_TGTTCCGAGCTCCCAG 42860      5745         10X_P7_7 F         3-F-56
10X_P7_7_TTAACTCGTCTCTTTA 35751      5422         10X_P7_7 F         3-F-56
10X_P7_7_TTAACTCTCAGAGACG 31618      4440         10X_P7_7 F         3-F-56
10X_P7_7_TTAGGACAGACAAAGG  9988      3201         10X_P7_7 F         3-F-56
10X_P7_7_TTAGGACCAGGGTACA 11756      2880         10X_P7_7 F         3-F-56
10X_P7_7_TTAGGACGTCTCCCTA  8516      2732         10X_P7_7 F         3-F-56
10X_P7_7_TTATGCTAGCCATCGC 14870      3657         10X_P7_7 F         3-F-56
10X_P7_7_TTATGCTCAGATGAGC 16126      3372         10X_P7_7 F         3-F-56
10X_P7_7_TTATGCTCAGCGTTCG  4938      1528         10X_P7_7 F         3-F-56
10X_P7_7_TTATGCTTCCGAACGC 11558      2319         10X_P7_7 F         3-F-56
10X_P7_7_TTATGCTTCCGCGGTA  6376      2580         10X_P7_7 F         3-F-56
10X_P7_7_TTCCCAGTCATGTGGT 34918      5002         10X_P7_7 F         3-F-56
10X_P7_7_TTCGGTCAGTGCGTGA 14304      3511         10X_P7_7 F         3-F-56
10X_P7_7_TTCGGTCCAGCGTAAG 22793      4562         10X_P7_7 F         3-F-56
10X_P7_7_TTCGGTCTCCGGGTGT  8380      2764         10X_P7_7 F         3-F-56
10X_P7_7_TTCTCAAAGAGCCCAA 37286      5356         10X_P7_7 F         3-F-56
10X_P7_7_TTCTCAACAAACGTGG 14565      3769         10X_P7_7 F         3-F-56
10X_P7_7_TTGAACGAGATGTCGG  9558      2972         10X_P7_7 F         3-F-56
10X_P7_7_TTGCGTCCAAAGTGCG 11456      3241         10X_P7_7 F         3-F-56
10X_P7_7_TTGCGTCGTAGGACAC 21269      3633         10X_P7_7 F         3-F-56
10X_P7_7_TTGGAACAGTAGATGT  8974      2831         10X_P7_7 F         3-F-56
10X_P7_7_TTGGAACGTCTAGTCA  6607      2546         10X_P7_7 F         3-F-56
10X_P7_7_TTGGAACGTGTCGCTG 50069      5641         10X_P7_7 F         3-F-56
10X_P7_7_TTGTAGGCACTTGGAT  9666      3087         10X_P7_7 F         3-F-56
10X_P7_7_TTGTAGGTCATGTAGC 22993      4296         10X_P7_7 F         3-F-56
10X_P7_7_TTTACTGGTGTTGAGG  8753      3005         10X_P7_7 F         3-F-56
10X_P7_7_TTTCCTCCATACCATG 14665      3778         10X_P7_7 F         3-F-56
10X_P7_7_TTTGTCAGTTACCGAT 30363      4786         10X_P7_7 F         3-F-56
10X_P7_7_TTTGTCATCTGTGCAA 16524      3979         10X_P7_7 F         3-F-56
                          percent.ribo free_annotation
10X_P4_3_AAAGTAGAGATGCCAG 0.21960937   Bladder mesenchymal cell
10X_P4_3_AACCGCGTCCAACCAA 0.17671233   Bladder mesenchymal cell
10X_P4_3_AACTCCCGTCGGGTCT 0.19244438   Bladder mesenchymal cell
10X_P4_3_AACTCTTAGTTGCAGG 0.35638461   Luminal bladder epithelial cell
10X_P4_3_AACTCTTTCATAACCG 0.15711936   Bladder mesenchymal cell
10X_P4_3_AAGACCTAGATCCGAG 0.23778009   Monocyte/Macrophage
10X_P4_3_AAGACCTAGGTGGGTT 0.32809182   Basal bladder epithelial cell
10X_P4_3_AAGGAGCGTGCAACTT 0.19020979   Bladder mesenchymal cell
10X_P4_3_AAGTCTGAGATAGTCA 0.22597153   Luminal bladder epithelial cell
10X_P4_3_ACAGCTATCATACGGT 0.33777498   Basal bladder epithelial cell
10X_P4_3_ACATACGCAGCTCCGA 0.13259285   Luminal bladder epithelial cell
10X_P4_3_ACCAGTACACGTCTCT 0.20075428   Bladder mesenchymal cell
10X_P4_3_ACGAGCCAGATAGCAT 0.16328432   Bladder mesenchymal cell
10X_P4_3_ACGGAGATCGGAATCT 0.15701626   Bladder mesenchymal cell
10X_P4_3_ACGGGCTGTCTGATCA 0.17214306   Bladder mesenchymal cell
10X_P4_3_ACTGAACCATCCGGGT 0.17514809   Bladder mesenchymal cell
10X_P4_3_ACTTTCAAGATGGGTC 0.31819064   Basal bladder epithelial cell
10X_P4_3_AGACGTTTCTTACCGC 0.09207814   Bladder mesenchymal cell
10X_P4_3_AGAGCTTTCTGTTGAG 0.18882543   Bladder mesenchymal cell
10X_P4_3_AGCGGTCTCTGAGTGT 0.36498276   Basal bladder epithelial cell
10X_P4_3_AGCTTGAAGACTAAGT 0.12250161   Bladder mesenchymal cell
10X_P4_3_AGGGAGTCAATCGGTT 0.20369575   Bladder mesenchymal cell
10X_P4_3_AGGGATGAGTCGCCGT 0.16600114   Bladder mesenchymal cell
10X_P4_3_AGGGTGACAGTCGTGC 0.16222954   Bladder mesenchymal cell
10X_P4_3_AGGTCCGAGGACACCA 0.27174854   Basal bladder epithelial cell
10X_P4_3_AGTCTTTAGCTAGTGG 0.16161616   Bladder mesenchymal cell
10X_P4_3_AGTGAGGAGTGTACTC 0.13708333   Bladder mesenchymal cell
10X_P4_3_AGTGAGGTCAGCATGT 0.31520974   Basal bladder epithelial cell
10X_P4_3_AGTGTCACAGTATCTG 0.11181332   Bladder mesenchymal cell
10X_P4_3_ATCACGACAACAACCT 0.14065046   Bladder mesenchymal cell
⋮                         ⋮            ⋮
10X_P7_7_TGTTCCGAGCTAACTC 0.34092475   Basal bladder epithelial cell
10X_P7_7_TGTTCCGAGCTCCCAG 0.37134858   Basal bladder epithelial cell
10X_P7_7_TTAACTCGTCTCTTTA 0.24913988   Basal bladder epithelial cell
10X_P7_7_TTAACTCTCAGAGACG 0.34100829   Luminal bladder epithelial cell
10X_P7_7_TTAGGACAGACAAAGG 0.14717661   Bladder mesenchymal cell
10X_P7_7_TTAGGACCAGGGTACA 0.31405240   Basal bladder epithelial cell
10X_P7_7_TTAGGACGTCTCCCTA 0.14560827   Bladder mesenchymal cell
10X_P7_7_TTATGCTAGCCATCGC 0.32313383   Basal bladder epithelial cell
10X_P7_7_TTATGCTCAGATGAGC 0.26851048   Luminal bladder epithelial cell
10X_P7_7_TTATGCTCAGCGTTCG 0.04597003   Monocyte/Macrophage
10X_P7_7_TTATGCTTCCGAACGC 0.11792698   Monocyte/Macrophage
10X_P7_7_TTATGCTTCCGCGGTA 0.12531368   Bladder mesenchymal cell
10X_P7_7_TTCCCAGTCATGTGGT 0.29950169   Basal bladder epithelial cell
10X_P7_7_TTCGGTCAGTGCGTGA 0.16072427   Bladder mesenchymal cell
10X_P7_7_TTCGGTCCAGCGTAAG 0.24985741   Basal bladder epithelial cell
10X_P7_7_TTCGGTCTCCGGGTGT 0.14439141   Bladder mesenchymal cell
10X_P7_7_TTCTCAAAGAGCCCAA 0.36834201   Basal bladder epithelial cell
10X_P7_7_TTCTCAACAAACGTGG 0.11342259   Bladder mesenchymal cell
10X_P7_7_TTGAACGAGATGTCGG 0.16970077   Bladder mesenchymal cell
10X_P7_7_TTGCGTCCAAAGTGCG 0.16096369   Bladder mesenchymal cell
10X_P7_7_TTGCGTCGTAGGACAC 0.34331656   Basal bladder epithelial cell
10X_P7_7_TTGGAACAGTAGATGT 0.13527970   Bladder mesenchymal cell
10X_P7_7_TTGGAACGTCTAGTCA 0.13319207   Bladder mesenchymal cell
10X_P7_7_TTGGAACGTGTCGCTG 0.40040744   Luminal bladder epithelial cell
10X_P7_7_TTGTAGGCACTTGGAT 0.10862818   NA
10X_P7_7_TTGTAGGTCATGTAGC 0.28678293   Basal bladder epithelial cell
10X_P7_7_TTTACTGGTGTTGAGG 0.12087284   Bladder mesenchymal cell
10X_P7_7_TTTCCTCCATACCATG 0.11817252   Bladder mesenchymal cell
10X_P7_7_TTTGTCAGTTACCGAT 0.30701841   Basal bladder epithelial cell
10X_P7_7_TTTGTCATCTGTGCAA 0.29950375   Basal bladder epithelial cell
                          cell_ontology_class     res.0.4 cluster.ids
10X_P4_3_AAAGTAGAGATGCCAG bladder cell            0       0
10X_P4_3_AACCGCGTCCAACCAA bladder cell            2       2
10X_P4_3_AACTCCCGTCGGGTCT bladder cell            5       5
10X_P4_3_AACTCTTAGTTGCAGG bladder urothelial cell 3       3
10X_P4_3_AACTCTTTCATAACCG bladder cell            2       2
10X_P4_3_AAGACCTAGATCCGAG leukocyte               6       6
10X_P4_3_AAGACCTAGGTGGGTT bladder urothelial cell 1       1
10X_P4_3_AAGGAGCGTGCAACTT bladder cell            0       0
10X_P4_3_AAGTCTGAGATAGTCA bladder urothelial cell 4       4
10X_P4_3_ACAGCTATCATACGGT bladder urothelial cell 1       1
10X_P4_3_ACATACGCAGCTCCGA bladder urothelial cell 4       4
10X_P4_3_ACCAGTACACGTCTCT bladder cell            0       0
10X_P4_3_ACGAGCCAGATAGCAT bladder cell            0       0
10X_P4_3_ACGGAGATCGGAATCT bladder cell            2       2
10X_P4_3_ACGGGCTGTCTGATCA bladder cell            0       0
10X_P4_3_ACTGAACCATCCGGGT bladder cell            0       0
10X_P4_3_ACTTTCAAGATGGGTC bladder urothelial cell 1       1
10X_P4_3_AGACGTTTCTTACCGC bladder cell            5       5
10X_P4_3_AGAGCTTTCTGTTGAG bladder cell            2       2
10X_P4_3_AGCGGTCTCTGAGTGT bladder urothelial cell 1       1
10X_P4_3_AGCTTGAAGACTAAGT bladder cell            0       0
10X_P4_3_AGGGAGTCAATCGGTT bladder cell            0       0
10X_P4_3_AGGGATGAGTCGCCGT bladder cell            0       0
10X_P4_3_AGGGTGACAGTCGTGC bladder cell            0       0
10X_P4_3_AGGTCCGAGGACACCA bladder urothelial cell 1       1
10X_P4_3_AGTCTTTAGCTAGTGG bladder cell            0       0
10X_P4_3_AGTGAGGAGTGTACTC bladder cell            0       0
10X_P4_3_AGTGAGGTCAGCATGT bladder urothelial cell 1       1
10X_P4_3_AGTGTCACAGTATCTG bladder cell            5       5
10X_P4_3_ATCACGACAACAACCT bladder cell            2       2
⋮                         ⋮                       ⋮       ⋮
10X_P7_7_TGTTCCGAGCTAACTC bladder urothelial cell 1       1
10X_P7_7_TGTTCCGAGCTCCCAG bladder urothelial cell 1       1
10X_P7_7_TTAACTCGTCTCTTTA bladder urothelial cell 1       1
10X_P7_7_TTAACTCTCAGAGACG bladder urothelial cell 4       4
10X_P7_7_TTAGGACAGACAAAGG bladder cell            5       5
10X_P7_7_TTAGGACCAGGGTACA bladder urothelial cell 1       1
10X_P7_7_TTAGGACGTCTCCCTA bladder cell            5       5
10X_P7_7_TTATGCTAGCCATCGC bladder urothelial cell 1       1
10X_P7_7_TTATGCTCAGATGAGC bladder urothelial cell 4       4
10X_P7_7_TTATGCTCAGCGTTCG leukocyte               6       6
10X_P7_7_TTATGCTTCCGAACGC leukocyte               6       6
10X_P7_7_TTATGCTTCCGCGGTA bladder cell            0       0
10X_P7_7_TTCCCAGTCATGTGGT bladder urothelial cell 1       1
10X_P7_7_TTCGGTCAGTGCGTGA bladder cell            5       5
10X_P7_7_TTCGGTCCAGCGTAAG bladder urothelial cell 1       1
10X_P7_7_TTCGGTCTCCGGGTGT bladder cell            5       5
10X_P7_7_TTCTCAAAGAGCCCAA bladder urothelial cell 1       1
10X_P7_7_TTCTCAACAAACGTGG bladder cell            5       5
10X_P7_7_TTGAACGAGATGTCGG bladder cell            5       5
10X_P7_7_TTGCGTCCAAAGTGCG bladder cell            5       5
10X_P7_7_TTGCGTCGTAGGACAC bladder urothelial cell 1       1
10X_P7_7_TTGGAACAGTAGATGT bladder cell            5       5
10X_P7_7_TTGGAACGTCTAGTCA bladder cell            0       0
10X_P7_7_TTGGAACGTGTCGCTG bladder urothelial cell 4       4
10X_P7_7_TTGTAGGCACTTGGAT endothelial cell        7       7
10X_P7_7_TTGTAGGTCATGTAGC bladder urothelial cell 1       1
10X_P7_7_TTTACTGGTGTTGAGG bladder cell            5       5
10X_P7_7_TTTCCTCCATACCATG bladder cell            5       5
10X_P7_7_TTTGTCAGTTACCGAT bladder urothelial cell 1       1
10X_P7_7_TTTGTCATCTGTGCAA bladder urothelial cell 1       1
                          cell_ontology_id
10X_P4_3_AAAGTAGAGATGCCAG CL:1001319
10X_P4_3_AACCGCGTCCAACCAA CL:1001319
10X_P4_3_AACTCCCGTCGGGTCT CL:1001319
10X_P4_3_AACTCTTAGTTGCAGG CL:1001428
10X_P4_3_AACTCTTTCATAACCG CL:1001319
10X_P4_3_AAGACCTAGATCCGAG CL:0000738
10X_P4_3_AAGACCTAGGTGGGTT CL:1001428
10X_P4_3_AAGGAGCGTGCAACTT CL:1001319
10X_P4_3_AAGTCTGAGATAGTCA CL:1001428
10X_P4_3_ACAGCTATCATACGGT CL:1001428
10X_P4_3_ACATACGCAGCTCCGA CL:1001428
10X_P4_3_ACCAGTACACGTCTCT CL:1001319
10X_P4_3_ACGAGCCAGATAGCAT CL:1001319
10X_P4_3_ACGGAGATCGGAATCT CL:1001319
10X_P4_3_ACGGGCTGTCTGATCA CL:1001319
10X_P4_3_ACTGAACCATCCGGGT CL:1001319
10X_P4_3_ACTTTCAAGATGGGTC CL:1001428
10X_P4_3_AGACGTTTCTTACCGC CL:1001319
10X_P4_3_AGAGCTTTCTGTTGAG CL:1001319
10X_P4_3_AGCGGTCTCTGAGTGT CL:1001428
10X_P4_3_AGCTTGAAGACTAAGT CL:1001319
10X_P4_3_AGGGAGTCAATCGGTT CL:1001319
10X_P4_3_AGGGATGAGTCGCCGT CL:1001319
10X_P4_3_AGGGTGACAGTCGTGC CL:1001319
10X_P4_3_AGGTCCGAGGACACCA CL:1001428
10X_P4_3_AGTCTTTAGCTAGTGG CL:1001319
10X_P4_3_AGTGAGGAGTGTACTC CL:1001319
10X_P4_3_AGTGAGGTCAGCATGT CL:1001428
10X_P4_3_AGTGTCACAGTATCTG CL:1001319
10X_P4_3_ATCACGACAACAACCT CL:1001319
⋮                         ⋮
10X_P7_7_TGTTCCGAGCTAACTC CL:1001428
10X_P7_7_TGTTCCGAGCTCCCAG CL:1001428
10X_P7_7_TTAACTCGTCTCTTTA CL:1001428
10X_P7_7_TTAACTCTCAGAGACG CL:1001428
10X_P7_7_TTAGGACAGACAAAGG CL:1001319
10X_P7_7_TTAGGACCAGGGTACA CL:1001428
10X_P7_7_TTAGGACGTCTCCCTA CL:1001319
10X_P7_7_TTATGCTAGCCATCGC CL:1001428
10X_P7_7_TTATGCTCAGATGAGC CL:1001428
10X_P7_7_TTATGCTCAGCGTTCG CL:0000738
10X_P7_7_TTATGCTTCCGAACGC CL:0000738
10X_P7_7_TTATGCTTCCGCGGTA CL:1001319
10X_P7_7_TTCCCAGTCATGTGGT CL:1001428
10X_P7_7_TTCGGTCAGTGCGTGA CL:1001319
10X_P7_7_TTCGGTCCAGCGTAAG CL:1001428
10X_P7_7_TTCGGTCTCCGGGTGT CL:1001319
10X_P7_7_TTCTCAAAGAGCCCAA CL:1001428
10X_P7_7_TTCTCAACAAACGTGG CL:1001319
10X_P7_7_TTGAACGAGATGTCGG CL:1001319
10X_P7_7_TTGCGTCCAAAGTGCG CL:1001319
10X_P7_7_TTGCGTCGTAGGACAC CL:1001428
10X_P7_7_TTGGAACAGTAGATGT CL:1001319
10X_P7_7_TTGGAACGTCTAGTCA CL:1001319
10X_P7_7_TTGGAACGTGTCGCTG CL:1001428
10X_P7_7_TTGTAGGCACTTGGAT CL:0000115
10X_P7_7_TTGTAGGTCATGTAGC CL:1001428
10X_P7_7_TTTACTGGTGTTGAGG CL:1001319
10X_P7_7_TTTCCTCCATACCATG CL:1001319
10X_P7_7_TTTGTCAGTTACCGAT CL:1001428
10X_P7_7_TTTGTCATCTGTGCAA CL:1001428

In [32]:
adata$X

  [[ suppressing 32 column names ‘Xkr4’, ‘Rp1’, ‘Sox17’ ... ]]

2500 x 23341 sparse Matrix of class "dgCMatrix"

10X_P4_3_AAAGTAGAGATGCCAG . .  . 1 .  . . . . . 1 . . . . . . . . . . . 1 . 1 .
10X_P4_3_AACCGCGTCCAACCAA . .  . . 2  3 . . . . 2 . . . . 2 . . 1 . . . . . 1 .
10X_P4_3_AACTCCCGTCGGGTCT . .  . . 1  1 . 2 . . 1 . . . . . . . . . . . . . 1 .
10X_P4_3_AACTCTTAGTTGCAGG . .  . . 2  . . 1 . . . . . . . . . . . . . . . . . .
10X_P4_3_AACTCTTTCATAACCG . .  . . .  1 . 1 . . . . . 1 . 1 . . . . . . . . . .
10X_P4_3_AAGACCTAGATCCGAG . .  . 2 3  1 . . . . . . . . . . . . . . . . . . . .
10X_P4_3_AAGACCTAGGTGGGTT . .  . . 1  1 . 1 . . 1 . . . . 2 . . . . . . 1 . 3 .
10X_P4_3_AAGGAGCGTGCAACTT . .  . . .  . . . . . . . . . . . . . . . . . . . . .
10X_P4_3_AAGTCTGAGATAGTCA . .  . . .  1 . 1 . . . . . 1 . 1 . . . . 1 . . . 1 .
10X_P4_3_ACAGCTATCATACGGT . .  . . 1  . . . . . 1 . . 2 . . . . . . . . 1 . . .
10X_P4_3_ACATACGCAGCTCCGA . .  . . .  . . . . . . . . . . . . . . . . . . . . .
10X_P4_3_ACCAGTACACGTCTCT . .  . . .  1 . . . . . . . . . . . . . . . . . . . .
10X_P4_3_ACGAGCCAGATAGCAT . .  . . .  . . . . . 1 . . 2 . . . . . . . . . . 1 .
10X_P4_3_ACGGAGATCGGAATCT . .  . . 1  1 . . . . . . . . . . . . . . . . . . 2 .
10X_P4_3_ACGGGCTGTCTGATCA . .  . . .  . . . . . . . . . . . . . . . 1 . . . . .
10X_P4_3_ACTGAACCATCCGGGT . .  . . .  . . . . . 1 . . 1 . . . . . . . . . . . .
10X_P4_3_ACTTTCAAGATGGGTC . .  . 1 .  1 . . . . 2 . . 1 . . . . . . . . . . 1 .
10X_P4_3_AGACGTTTCTTACCGC . .  . . .  . . . . . . . . 1 . . . . . . . . . . . .
10X_P4_3_AGAGCTTTCTGTTGAG . .  . 1 .  . . . . . . . . . . . . . . . 1 . . . 1 .
10X_P4_3_AGCGGTCTCTGAGTGT . .  . 1 1  2 . 1 . . . . . 2 . . . . . . 1 . 1 . 1 .
10X_P4_3_AGCTTGAAGACTAAGT . .  . 1 .  1 . . . . . . . . . . . . . . 1 . . . 1 .
10X_P4_3_AGGGAGTCAATCGGTT . .  . . .  1 . 1 . . 2 . . . . . . . . . . . . . . .
10X_P4_3_AGGGATGAGTCGCCGT . .  . . .  . . . . . . . . . . . . . . . . . . . . .
10X_P4_3_AGGGTGACAGTCGTGC . .  . 1 .  2 . 2 . . . . . . . . . 1 . . . . . . . .
10X_P4_3_AGGTCCGAGGACACCA . .  . . 2  1 . 2 . . . . . 3 . . . . . . 1 . . . . .
10X_P4_3_AGTCTTTAGCTAGTGG . .  . . .  . . 1 . . . . . . . . . . . . . . . . . .
10X_P4_3_AGTGAGGAGTGTACTC . .  . . 2  . . 1 . . . . . . . . . . . . 1 . . . . .
10X_P4_3_AGTGAGGTCAGCATGT . .  . 1 2  1 . 1 . . . . . . . . . . . . . . . . 1 .
10X_P4_3_AGTGTCACAGTATCTG . .  . . .  . . . . . 3 . . 1 . . . . . . . . . . 2 .
10X_P4_3_ATCACGACAACAACCT . .  . . .  2 . . . . . . . 1 . 3 . . . . 1 . . . 1 .
10X_P4_3_ATCGAGTTCTCCAGGG . .  . 1 1  1 . 2 . . 2 . . . . 1 . . . . . . . . 2 .
10X_P4_3_ATTATCCAGTAAGTAC . .  . 1 .  3 . 2 . . . . . . . . . . . . . . . . . .
10X_P4_3_ATTTCTGCATGTTGAC . .  . 1 1  . . . . . . . . 3 . . . . . . . . . . 2 .
10X_P4_3_ATTTCTGGTCAGGACA . .  . . 2  . . . . . . . . 1 . . . . . . . . 1 . . .
10X_P4_3_CAACCAAAGACGCACA . .  . 1 1  2 . 1 . . 1 . . 1 . . . . . . . . . . 1 .
10X_P4_3_CACACCTAGCCCAATT . .  . 1 .  2 . . . . . . . 2 . 1 . . . . . . . . . .
10X_P4_3_CACACCTGTTTGACAC . .  . . .  1 . 3 . . 1 . . 1 . 1 . . . . . . . . 2 .
10X_P4_3_CACATAGCAGATGGCA . .  . . 1  . . 1 . . . . . 1 . . . . . . . . . . 1 .
10X_P4_3_CACATTTTCTGGTATG . .  1 4 3  1 . 2 . . 2 . . 9 . 2 . . . . . . . . . .
10X_P4_3_CACCAGGCAAGGCTCC . .  . . .  . . . . . . . . . . . . . . . . . . . . .
10X_P4_3_CACCTTGAGGACCACA . .  . 2 .  . . 1 . . 1 . . . . 1 . . . . 1 . . . 2 .
10X_P4_3_CACTCCACACATCCAA . .  . 1 1  1 . . . . 2 . . 2 . . . . . . 1 . . . . .
10X_P4_3_CAGAATCTCTCAAGTG . .  . . .  1 . . . . . . . . . . . . . . . . 1 . . .
10X_P4_3_CAGCATAAGATGGGTC . .  . . .  1 . . . . . . . . . . . . . . . . . . 1 .
10X_P4_3_CAGCTGGTCCTTTACA . .  . 2 2  1 . . . . . . . . . 2 . . . . . . . 1 3 .
10X_P4_3_CATTCGCTCTCGTATT . .  1 . .  2 . . . . . . . . . . . . . . . . . . 2 .
10X_P4_3_CCAGCGATCGCTGATA . .  . . .  2 . . . . 3 . . . . 1 . . . . . . . . . .
10X_P4_3_CCCAGTTCACATGACT . .  . 1 .  1 . . . . . . . 1 . . . . . . . . . . 1 .
10X_P4_3_CCGGTAGAGGCAGTCA . .  . 3 3  4 . 3 . . . . . 2 . . . . . . . . . . 4 .
10X_P4_3_CCGGTAGCAGTGGGAT . .  . . .  1 . . . . . . . . . 1 . . . . . . . . . .
10X_P4_3_CCGTGGAGTGAGGGTT . .  . . 1  . . 1 . . . . . 2 . . . . . . . . . . . .
10X_P4_3_CCGTTCAGTTCCCTTG . . 17 1 .  3 . 1 . . . . . . . . . . . . . . . . . .
10X_P4_3_CCTACACAGGGCATGT . .  . 1 1  1 . . . . . . . 1 . . . . . . . . . . 2 .
10X_P4_3_CCTTCGATCTCCGGTT . .  . . .  1 . . . . . . . . . . . . . . . . . . . .
10X_P4_3_CGAGAAGAGGACTGGT . .  . 2 .  . . . . . . . . . . . . . . . . . . . . .
10X_P4_3_CGATTGATCTAACTTC . .  . . 1  . . . . . . . . 1 . 1 . . . . . . . . . .
10X_P4_3_CGGACTGTCTTGTATC . .  . 1 .  . . . . . . . . . . . . . . . . . . . 1 .
10X_P4_3_CGGAGTCAGTACGCCC . .  . 1 2  1 . 3 . . 1 . . . . 1 . . . . . . 2 . 1 .
10X_P4_3_CGGGTCATCGTGGACC . .  . . 1  2 . . . . 1 . . . . . . 1 . . . . . . 3 .
10X_P4_3_CGTAGGCCACGGACAA . .  . . .  2 . 1 . . 2 . . 4 . 1 . . . . 1 . . . 2 .
10X_P4_3_CGTCCATAGTCCTCCT . .  . . 2  2 . . . . . . . 1 . 2 . . . . . . . . 1 .
10X_P4_3_CGTGAGCGTGCACTTA . .  . 2 .  . . . . . . . . . . 2 . . . . . . . . . .
10X_P4_3_CTAGAGTGTCATATCG . .  . . 1  . . . . . 1 . . . . . . . . . . . 1 . 1 .
10X_P4_3_CTAGCCTAGCTGCGAA . .  . 1 1  2 . . . . 1 . . 1 . 1 . . . . . . . . 3 .
10X_P4_3_CTCATTAGTGAAAGAG . .  . . 1  1 . . . . 1 . . 1 . . . . . . 1 . . . . .
10X_P4_3_CTCGAGGAGGCGCTCT . .  . . .  1 . . . . 1 . . 2 . . . . . . . . . . 2 .
10X_P4_3_CTCGAGGAGGGTTTCT . .  . . .  . . . . . . . . . . . . . . . . . . . . .
10X_P4_3_CTCGTACTCAATACCG . .  . . .  1 . . . . . . . 3 . . . . . . . . . . 2 .
10X_P4_3_CTCTAATAGTGAATTG . .  . 2 1  1 . . . . . . . . . . . . . . . . . . . .
10X_P4_3_CTCTAATCACGGCGTT . .  . . .  . . . . . . . . 1 . . . . . . . . . . . .
10X_P4_3_CTCTGGTAGTGTACCT . .  . . 1  3 . . . . . . . . . 1 . . . . . . . . 1 .
10X_P4_3_CTGAAACGTAGTACCT . .  . . 1  . . . . . . . . . . . . . . . . . . . . .
10X_P4_3_CTGCCTACAGCCACCA . .  . . .  2 . . . . . . . 1 . . . . . . 2 . . . . .
10X_P4_3_CTGCGGAGTATGCTTG . .  . 1 .  3 . . . . . . . . . . . . . . . . . . 2 .
10X_P4_3_CTGCTGTTCGTTACGA . .  . 1 .  1 . 1 . . . . . 2 . . . . . . . . . . 2 .
10X_P4_3_CTGTGCTCAATGGACG . .  . 2 1  1 . . . . . . . . . . . . . . 1 . . . . .
10X_P4_3_CTTGGCTCACGAAACG . .  . . 1  4 . . . . 1 . . 1 . 1 . 1 . . . . . . 5 .
10X_P4_3_GAAATGACAATCCAAC . .  . . 1  2 . 2 . . 2 . . . . . . . . . . . . . 1 .
10X_P4_3_GAACATCAGTGTTAGA . .  . 1 .  2 . 2 . . . . . . . 2 . . . . . . . . . .
10X_P4_3_GAACCTACATTAGGCT . .  . . 1  1 . . . . . . . 3 . 1 . . . . 2 . . . 2 .
10X_P4_3_GAAGCAGCACCGATAT . .  . 1 .  2 . 2 . . . . . . . . . . . . 1 . 1 . . .
10X_P4_3_GAATAAGGTCGGCATC . .  . 1 1  2 . . . . . . . 2 . 1 . . . . . . . . 1 .
10X_P4_3_GACGGCTAGTCGTTTG . .  . . .  . . . . . 2 . . . . . . . . . 3 . . . 1 .
10X_P4_3_GACGTTAGTAGGCTGA . .  . . .  . . . . . . . . . . . . . . . . . . . . .
10X_P4_3_GACGTTATCAGGTTCA . .  . 1 .  . . . . . . . . 1 . . . . . . . . . . . .
10X_P4_3_GACTAACCATCGACGC . .  . . .  . . . . . . . . . . 1 . . . . . . . . 2 .
10X_P4_3_GAGGTGATCCAGTATG . .  . 1 .  3 . . . . . . . 1 . . . . . . . . . . . .
10X_P4_3_GATCGCGTCACCCTCA . .  . 2 2  8 . 1 . . . . . 1 . . . . . . 1 . . . 1 .
10X_P4_3_GATTCAGCAGTGGAGT . .  . . .  . . . . . . . . . . . . . . . . . . . . .
10X_P4_3_GCAAACTAGAGCCCAA . .  . 1 .  1 . . . . 1 . . . . 1 . . . . . . . . . .
10X_P4_3_GCATGATCATATGGTC . .  . . 2  2 . 1 . . . . . . . 1 . . . . 1 . . . . .
10X_P4_3_GCGACCAAGGGATCTG . .  . . .  6 . 2 . . 1 . . 3 . . . . . . . . 2 . 3 .
10X_P4_3_GCGACCACACCAACCG . .  1 . .  . . . . . 1 . . . . . . . . . . . . . . .
10X_P4_3_GCGAGAACACATGGGA . .  . 1 .  . . . . . 1 . . 1 . . . . . . . . . . . .
10X_P4_3_GCGAGAATCCCTCTTT . .  . 1 .  . . 1 . . . . . . . . . . . . . . . . 1 .
10X_P4_3_GCTGCTTTCAAAGTAG . .  . . .  2 . 2 . . . . . 3 . . . . . . . . . . . .
10X_P4_3_GGAATAATCATTCACT . .  . . .  . . 1 . . 1 . . 2 . . . . . . . . . . . .
10X_P4_3_GGACAGACATTCACTT . .  . . .  1 . . . . 1 . . . . 2 . . . . . . . . . .
10X_P4_3_GGCGTGTCATTGGGCC . .  . . .  1 . . . . . . . 1 . 1 . . . . . . 1 . . .
10X_P4_3_GGCTCGAAGCGTGAGT . .  . . .  1 . . . . 1 . . 1 . . . . . . 1 . . . . .
10X_P4_3_GGGCATCTCCGTTGTC . .  . . 1  1 . 1 . . 1 . . . . 1 . . . . 2 . . . 1 .
10X_P4_3_GGTGCGTAGAGGTACC . .  . 1 2  . . 1 . . 2 . . . . . . . . . . . . . . .
10X_P4_3_GTAACGTTCAGGCGAA . .  . . .  1 . . . . 1 . . 1 . . . . . . . . . . 1 .
10X_P4_3_GTAACTGCAGCATACT . .  . . .  1 . . . . 1 . . 1 . . . . . . 1 . . . 1 .
10X_P4_3_GTACGTACACACCGAC . .  . 1 3  . . . . . 1 . . 3 . . . . . . . . . . 3 .
10X_P4_3_GTACTCCTCGCCTGTT . .  . . 1  . . 2 . . . . . 1 . 1 . . . . . . . . . .
10X_P4_3_GTAGTCAAGACGACGT . .  . 1 .  1 . . . . . . . . . . . . . . . . . . 1 .
10X_P4_3_GTATCTTGTAGAGGAA . .  . . .  1 . . . . . . . . . . . . . . . . . . . .
10X_P4_3_GTATCTTTCGCCATAA . .  . . .  . . . . . . . . . . 1 . . . . . . . 1 1 .
10X_P4_3_GTCACAATCACTTCAT . .  . . .  2 . . . . . . . . . . . . . . . . . . . .
10X_P4_3_GTCACAATCTACTCAT . .  . . .  1 . . . . . . . . . 1 . . . . . . . . . .
10X_P4_3_GTCATTTGTCTTGCGG . .  . . 1  1 . . . . 1 . . . . . . . . . . . . . 3 .
10X_P4_3_GTCGGGTAGGCCGAAT . .  . . .  1 . . . . . . . . . . . . . . . . . . . .
10X_P4_3_GTCTCGTCAAACTGTC . .  . . 1  . . . . . . . . . . . . . . . . . . . . .
10X_P4_3_GTGCAGCGTGGTACAG . .  1 . 2  2 . . . . . . . . . . . . . . . . . . 1 .
10X_P4_3_GTGCAGCTCAGTTAGC . .  . . 1  1 . 1 . . . . . 2 . . . . . . . . . 1 2 .
10X_P4_3_GTGGGTCAGATGTGGC . .  . . 2  1 . 2 . . 2 . . . . . . . . . 1 . . . 2 .
10X_P4_3_GTGTGCGTCAGTTCGA . .  . . 1  1 . . . . . . . . . . . . . . 1 . 1 . 1 .
10X_P4_3_GTTAAGCCACCAGGTC . .  . 1 .  2 . . . . . . . . . 1 . . . . . . . . 3 .
10X_P4_3_GTTCTCGGTGCTTCTC . .  . . .  2 . . . . 1 . . 1 . . . . . . . . . . . .
10X_P4_3_GTTTCTAAGGACTGGT . .  . 1 .  . . 3 . . 1 . . 1 . . . . . . . . . . . .
10X_P4_3_TAAGAGAAGCTATGCT . .  . 1 3  1 . 1 . . . . . . . 1 . . . . . . . . . .
10X_P4_3_TAAGCGTAGAAACCGC . .  . . 2  2 . . . . . . . . . . . . . . . . . . 1 .
10X_P4_3_TACGGATAGGTACTCT . .  . 1 1  . . . . . . . . . . . . . . . . . . . . .
10X_P4_3_TACTTGTGTGTTCTTT . .  . . .  1 . 1 . . . . . . . . . . . . . . . . 1 .
10X_P4_3_TAGCCGGAGGACTGGT . .  . . .  . . . . . 1 . . . . . . . . . . . . . 2 .
10X_P4_3_TAGGCATTCTATCCTA . .  . . 3  2 . . . . . . . . . . . . . 1 . . . . . .
10X_P4_3_TCAACGACAATGGTCT . .  . . 1  1 . . . . . . . . . . . . . . . . 1 . 1 .
10X_P4_3_TCCACACCAGCTGCTG . .  . . 2  2 . . . . . . . 2 . 1 . . . . . . 1 . 2 .
10X_P4_3_TCTTCGGGTTTAGGAA . .  . . .  1 . . . . . . . 1 . 1 . . . . 1 . 1 . . .
10X_P4_3_TCTTTCCTCCGCATAA . .  . . 2  1 . . . . 2 . . . . . 1 . . . 1 . . . 2 .
10X_P4_3_TGAGAGGAGACATAAC . .  . 1 1  4 . 1 . . 1 . . . . . . . . . . . . . 2 .
10X_P4_3_TGAGAGGAGCGATATA . .  . . .  1 . . . . . . . . . 1 . . . . . . . . . .
10X_P4_3_TGAGCATAGTGGAGTC . .  4 . .  . . . . . . . . . . . . . . . . . 1 . 1 .
10X_P4_3_TGCGGGTTCTTTACGT . .  1 . 1  4 . 2 . . 3 . . 1 . 1 . . . . . . . . 3 .
10X_P4_3_TGGACGCTCCGATATG . .  . 2 .  . . . . . . . . 1 . . . . . 1 1 . . . . .
10X_P4_3_TGGACGCTCTGCAGTA . .  . . 2  1 . 1 . . . . . . . 1 . . . . 1 . . . . .
10X_P4_3_TGGCTGGGTCGCTTCT . .  . . 1  1 . 2 . . 2 . . 1 . 5 . . . . 1 . . . . .
10X_P4_3_TGGGAAGAGTAGGCCA . .  . 1 .  2 . . . . 1 . . 1 . . . . . . . . . . . .
10X_P4_3_TTCTACAAGGCAGTCA . .  . . .  . . . . . 1 . . . . . . . . . . . 1 . . .
10X_P4_3_TTGAACGTCTCTTATG . .  . 1 .  . . . . . 1 . . . . . . . . . . . . . 1 .
10X_P4_3_TTGCCGTCACGCCAGT . .  . . .  1 . . . . . . . . . . . . . . . . . . . .
10X_P4_3_TTGGAACGTTAGGGTG . .  . . .  1 . . . . 1 . . . . . . . . . . . . . . .
10X_P4_3_TTGGCAACATGATCCA . .  . . 2  2 . 1 . . 4 . . . . . . . . . . . . . . .
10X_P4_3_TTGGCAAGTCCGTTAA . .  . . .  . . . . . . . . . . 1 . . . . . . . . 1 .
10X_P4_3_TTGTAGGCATCCGGGT . .  . 1 .  . . 2 . . 2 . . 2 . 1 . . . . . . . . 1 .
10X_P4_3_TTTACTGCACACGCTG . .  . . .  . . . . . . . . . . 2 . . . . 1 . . . 1 .
10X_P4_3_TTTACTGCAGGACGTA . .  . 2 1  3 . . . . 1 . . . . . . . . . . . . . . .
10X_P4_3_TTTGTCAGTTGCGTTA . .  . . .  . . . . . . . . . . . . . . . . . . . . .
10X_P4_4_AAACCTGCAGACAAGC . .  . . .  . . . . . . . . . . . . . . . . . . . . .
10X_P4_4_AAACGGGAGATCCCAT . .  . . .  4 . . . . . . . 1 . . . . . . 1 . . . 1 .
10X_P4_4_AAACGGGCAGTACACT . .  . . .  1 . 1 . . 1 . . 1 . . . . . . 1 . . . . .
10X_P4_4_AAACGGGGTTGGACCC . .  . . .  1 . . . . 2 . . 2 . . . . . . . . . . . .
10X_P4_4_AAACGGGTCGCGATCG . .  . 1 .  . . . . . . . . . . . . . . . . . . . . .
10X_P4_4_AAACGGGTCTCGTATT . .  . . .  . . . . . . . . 1 . . . . . . 1 . . . . .
10X_P4_4_AAACGGGTCTTAGCCC . .  . . .  . . 2 . . . . . . . . . . . . . . . . . .
10X_P4_4_AAAGATGAGACAATAC . .  . 1 1  1 . . . . 1 . . . . . . . . . . . . . . .
10X_P4_4_AAAGATGCAAGTAGTA . .  . . .  1 . . . . . . . . . 2 . . . . . . . . . .
10X_P4_4_AAAGATGCACAAGACG . .  . . 1  1 . . 1 . . . . . . . . . . . . . . . 1 .
10X_P4_4_AAAGATGGTCAAAGCG . .  . . .  . . . . . . . . . . . . . . . . . . . . .
10X_P4_4_AAAGATGGTCCGTCAG . .  . . .  2 . . . . 1 . . 1 . . . . . . . . . . . .
10X_P4_4_AAAGATGTCACTATTC . .  . 2 1  3 . . . . 1 . . 2 . . . . . . . . . . 4 .
10X_P4_4_AAAGATGTCCACGTGG . .  . . 1  3 . . . . 1 . . . . 1 . . . . . . . . . .
10X_P4_4_AAAGTAGCACAGACAG . .  . . 1  . . . . . . . . 1 . . . . . . . . . . 1 .
10X_P4_4_AAAGTAGCACAGCCCA . .  . 2 .  3 . . . . . . . 1 . . . . . . . . . . 1 .
10X_P4_4_AAAGTAGGTACCCAAT . .  . . 1  . . . . . . . . . . . . . . . . . . . . .
10X_P4_4_AAAGTAGTCATCGGAT . .  . . 1  . . . . . 1 . . 3 . . . . . . 1 . . . . .
10X_P4_4_AAAGTAGTCGGTCTAA . .  . . .  1 . 1 . . . . . . . . . . . . 1 . . . 1 .
10X_P4_4_AAATGCCAGCTCAACT . .  . . .  1 . . . . . . . . . . . . . . . . . . . .
10X_P4_4_AAATGCCAGGATATAC . .  . . .  3 . . . . . . . 1 . . . . . . . . . . . .
10X_P4_4_AAATGCCTCTGTCAAG . .  . . .  1 . . . . . . . . . . . . . . . . . . . .
10X_P4_4_AACACGTAGAGAACAG . .  . . 1  1 . . . . . . . 1 . 1 . . . . . . . . 1 .
10X_P4_4_AACACGTGTACCTACA . .  . . .  . . 1 . . . . . . . . . . . . . . . . . .
10X_P4_4_AACACGTGTGAAGGCT . .  . 1 1  2 . 3 . . 2 . . . . . . . . . 1 . . . 1 .
10X_P4_4_AACACGTGTTTGACTG . .  . 1 .  . . . . . . . . 2 . . . . . . . . . . 1 .
10X_P4_4_AACACGTTCCAATGGT . .  . 3 .  . . . . . 1 . . 1 . . . . . . . . . . 1 .
10X_P4_4_AACACGTTCTTAACCT . .  . 3 2  3 . 1 . . . . . 4 . 2 . . . . . . . . 2 .
10X_P4_4_AACCATGAGCATGGCA . .  . 1 2  1 . 4 . . 1 . . 1 . . 1 . . . . . . . . .
10X_P4_4_AACCATGGTATTCGTG . .  . . 1  . . 1 . . 1 . . . . 1 . . . . 1 . . . . .
10X_P4_4_AACCGCGCACAGCGTC . .  . . .  1 . . . . . . . 1 . 1 . . . . . . . . 1 .
10X_P4_4_AACCGCGCACCAGTTA . .  . . .  1 . 1 . . 2 . . . . . . . . . . . 1 . . .
10X_P4_4_AACCGCGGTCCGTGAC . .  . . .  . . . . . 1 . . . . . . . . . . . . . . .
10X_P4_4_AACCGCGGTGATGCCC . .  . . .  . . . . . . . . . . . . . . . . . . 1 . .
10X_P4_4_AACCGCGGTGTCGCTG . .  . . 1  1 . . . . . . . . . 3 . . . . 3 . . . . .
10X_P4_4_AACGTTGAGAACTCGG . .  . 1 2  2 . 2 . . . . . 1 . 1 . . . . 2 . . . 2 .
10X_P4_4_AACGTTGAGGGTCTCC . .  . . .  . . 1 . . . . . . . . . . . . . . . . . .
10X_P4_4_AACGTTGCACACATGT . .  . 1 1  . . . . . . . . . . . . . . . . . . . . .
10X_P4_4_AACGTTGCACTGCCAG . .  . . 1  2 . 1 . . 1 . . 2 . . . . . . 1 . . . 3 .
10X_P4_4_AACGTTGCAGGACGTA . .  . . 2  . . . . . . . . . . . . . . . . . . . 1 .
10X_P4_4_AACGTTGCATGATCCA . .  . . 1  . . . . . 1 . . 2 . . . . . . . . . . 1 .
10X_P4_4_AACGTTGGTGTGACGA . .  . . .  . . . . . . . . . . . . . . . 1 . . . . .
10X_P4_4_AACTCAGAGATTACCC . .  . 1 1  . . . . . . . . 1 . 1 . . . . . . . . 1 .
10X_P4_4_AACTCAGAGCTATGCT . .  . . .  . . . . . . . . . . . . . . . . . 1 . . .
10X_P4_4_AACTCAGCAACAACCT . .  . 3 .  . . . . . . . . 1 . . . . . . . . . . . .
10X_P4_4_AACTCAGGTCCCGACA . .  . 1 1  4 . . . . 3 . . 2 . . . . . . 1 . . . . .
10X_P4_4_AACTCAGTCACAATGC . .  . . .  . . . . . . . . 1 . . . . . . 2 . . . 1 .
10X_P4_4_AACTCCCCATGTAAGA . .  . . .  . . . . . . . . . . . . . . . . . . . 2 .
10X_P4_4_AACTCCCGTTATTCTC . .  . . .  . . . . . 2 . . 1 . 1 . . . . . . . . . .
10X_P4_4_AACTCTTAGACAGGCT . .  . . .  1 . . . . . . . . . 1 . . . . . . . . 2 .
10X_P4_4_AACTCTTAGAGGTAGA . .  . . .  . . 2 . . . . . 1 . 1 . . . . . . . . . .
10X_P4_4_AACTCTTCATGTTGAC . .  . . 2  . . . . . . . . 1 . 1 . . . . . . . . . .
10X_P4_4_AACTCTTGTAATCGTC . .  . . .  1 . . . . . . . . . . . . . . . . . . . .
10X_P4_4_AACTCTTTCCGCAGTG . .  . . .  . . . . . . . . . . 2 . . . . 2 . . . 2 .
10X_P4_4_AACTCTTTCGTTTATC . .  . . 1  1 . 2 . . 3 . . 2 . . 1 . . . 1 . . . 3 .
10X_P4_4_AACTGGTAGTCAAGCG . .  . . .  . . . . . 1 . . . . . . . . . 1 . . . . .
10X_P4_4_AACTGGTCAAGCCGTC . .  . 1 .  . . . . . . . . 1 . . . . . . . . . . . .
10X_P4_4_AACTTTCAGACAAAGG . .  . . 2  4 . . . . 1 . . 1 . . . . . . . . 1 . 1 .
10X_P4_4_AACTTTCCAATCTGCA . .  . . 1  1 . 1 . . . . . 2 . . . . . . . . . . 1 .
10X_P4_4_AACTTTCCAGCGTAAG . .  . 1 .  2 . . . . 1 . . . . . . . . . . . . . . .
10X_P4_4_AACTTTCGTACACCGC . .  . . 1  . . . . . . . . . . . . . . . . . . . . .
10X_P4_4_AAGACCTAGAGCTGCA . .  . 2 1  . . . . . . . . 2 . 1 . . . . 1 . . . . .
10X_P4_4_AAGACCTAGGGTGTGT . .  . 1 .  3 . . . . . . . 1 . 2 . . . . . . 1 . 1 .
10X_P4_4_AAGACCTCAACTGCTA . .  . 1 1  1 . . . . 1 . . 1 . . . . . . . . . . . .
10X_P4_4_AAGACCTCAAGTCATC . .  . 1 .  2 . . . . 2 . . . . . . . . . 1 . . . . .
10X_P4_4_AAGACCTTCGAGCCCA . .  . 1 .  . . 1 . . 1 . . . . . . . . . . . . . 1 .
10X_P4_4_AAGCCGCCATAGGATA . .  . . .  1 . 1 . . . . . . . . . . . . . . . . . .
10X_P4_4_AAGCCGCGTTTAGGAA . .  . . 1  . . . . . . . . 1 . . . . . . . . . . . .
10X_P4_4_AAGCCGCTCAACCATG . .  . 1 .  1 . . . . . . . . . . . . . . . . . . . .
10X_P4_4_AAGCCGCTCTCCCTGA . .  . . .  . . . . . . . . . . . 1 . . . . . . . . .
10X_P4_4_AAGGAGCCATCTGGTA . .  . . .  . . . . . 1 . . . . 1 . . . . . . . . . .
10X_P4_4_AAGGAGCTCGCATGGC . .  . . 1  1 . . . . . . . 1 . . . . . . 1 . . . 2 .
10X_P4_4_AAGGAGCTCTTCTGGC . .  . 1 .  1 . . . . . . . . . . . . . . . . . . . .
10X_P4_4_AAGGCAGCAGTATAAG . .  . . 1  1 . . . . . . . . . . . . . . . . . . . .
10X_P4_4_AAGGCAGGTCGACTGC . .  . 1 .  1 . . . . . . . . . . . . . . . . . . . .
10X_P4_4_AAGGCAGGTGCCTGTG . .  . 1 .  1 . 1 . . . . . 1 . . . . . . . . . . 2 .
10X_P4_4_AAGGCAGTCACTTACT . .  . . .  . . . . . 1 . . . . . . . . . . . . . . .
10X_P4_4_AAGGCAGTCGAATCCA . .  . . .  . . . . . 1 . . 1 . . . . . . . . . . 1 .
10X_P4_4_AAGGCAGTCGCTTAGA . .  . . .  1 . . . . . . . . . . . . . . . . . . . .
10X_P4_4_AAGGTTCAGACTTTCG . .  . . .  . . . . . . . . . . . . . . . . . . . . .
10X_P4_4_AAGGTTCCACATCCAA . .  . 1 .  . . 1 . . 1 . . 1 . . . . . . . . . . . .
10X_P4_4_AAGGTTCGTACAGCAG . .  . 1 1  1 . 1 . . 2 . . . . . . . . . 1 . . . 2 .
10X_P4_4_AAGGTTCGTAGCCTAT . .  . . .  . . . . . . . . 3 . . . . . . . . . . . .
10X_P4_4_AAGGTTCGTTCGTTGA . .  . . 1  . . . . . . . . . . . . . . . . . . . 1 .
10X_P4_4_AAGGTTCTCAACGGGA . .  . 1 1  . . 2 . . . . . 2 . 1 . . . . 1 . . . . .
10X_P4_4_AAGGTTCTCGCGTAGC . .  . . .  1 . . . . . . . . . . . . . . . . . . . .
10X_P4_4_AAGTCTGAGAGTCGGT . .  . . .  . . . . . . . . . . . . . . . . . . . . .
10X_P4_4_AAGTCTGAGGTAAACT . .  . 1 .  . . . . . . . . . . 1 . . . . 1 . . . . .
10X_P4_4_AAGTCTGGTACCTACA . .  . 1 1  2 . . . . . . . . . . . . . . . . . . . .
10X_P4_4_AAGTCTGGTCTGCAAT . .  . . 3  . . . . . 1 . . 1 . 2 . . . . . . . . . .
10X_P4_4_AAGTCTGTCTGTCTCG . .  . . .  . . . . . . . . . . 2 . . . . . . . . 3 .
10X_P4_4_AATCCAGTCACCCGAG . .  . 1 3  . . . . . . . . 1 . 1 . . . . . . 1 . . .
10X_P4_4_AATCCAGTCGGAGCAA . .  . . 1  . . . 2 . . . . 1 . 1 . . . . . . . . . .
10X_P4_4_AATCGGTAGGGTCGAT . .  . . .  2 . . . . 1 . . . . . . . . . . . . . . .
10X_P4_4_AATCGGTAGGTGACCA . .  . . .  1 . . . . 1 . . . . 1 . . . . . . . . . .
10X_P4_4_AATCGGTCATACGCCG . .  . . .  1 . . . . . . . 3 . 2 . . . . . . . . . .
10X_P4_4_ACACCAAAGAGATGAG . .  . . .  2 . . . . . . . 1 . . . . . . . . . . 1 .
10X_P4_4_ACACCAACATCCTAGA . .  . . .  . . . . . . . . . . 1 . . . . . . 1 . . .
10X_P4_4_ACACCAACATCGATTG . .  . 1 .  . . . . . 2 . . 1 . . . . . . . . . . 1 .
10X_P4_4_ACACCAATCATAAAGG . .  . 2 2  3 . 2 . . 1 . . . . . . . . . . . . . 1 .

In [29]:
srat_qc <- CreateSeuratObject(counts=srat[['RNA']]@counts, meta.data=srat@meta.data, project = Project(srat))
srat_qc

An object of class Seurat
23341 features across 2500 samples within 1 assay
Active assay: RNA (23341 features, 0 variable features)

In [30]:
output_path <- '/ps/ai-ready/data/Clustering/Tabula_Muris/droplet_Bladder_seurat_tiss.h5Seurat'
SaveH5Seurat(srat_qc, filename = output_path, overwrite = TRUE, verbose = TRUE)
srat_qc_1 <- LoadH5Seurat(output_path)
srat_qc_1

Warning message:
“Overwriting previous file /ps/ai-ready/data/Clustering/Tabula_Muris/droplet_Bladder_seurat_tiss.h5Seurat”
Creating h5Seurat file for version 3.1.5.9900

Adding counts for RNA

Adding data for RNA

No variable features found for RNA

No feature-level metadata found for RNA

Validating h5Seurat file

Initializing RNA with data

Adding counts for RNA

Adding miscellaneous information for RNA

Adding command information

Adding cell-level metadata

ERROR: Error in args_regularity_evaluation(args = args, ds_dims = simple_extent$dims, : Number of arguments not equal to number of dimensions: 1 vs. 2

In [16]:
output_path <- '/ps/ai-ready/data/Clustering/Tabula_Muris/droplet_Bladder_seurat_tiss.h5Seurat'
SaveH5Seurat(srat, filename = output_path, overwrite = TRUE, verbose = TRUE)
srat1 <- LoadH5Seurat(output_path)
srat1

Warning message:
“Overwriting previous file /ps/ai-ready/data/Clustering/Tabula_Muris/droplet_Bladder_seurat_tiss.h5Seurat”
Creating h5Seurat file for version 3.1.5.9900

Adding counts for RNA

Adding data for RNA

No variable features found for RNA

No feature-level metadata found for RNA

Validating h5Seurat file

Initializing RNA with data

Adding counts for RNA

Adding miscellaneous information for RNA

Adding command information

Adding cell-level metadata

ERROR: Error in args_regularity_evaluation(args = args, ds_dims = simple_extent$dims, : Number of arguments not equal to number of dimensions: 1 vs. 2

In [ ]:
srat <- subset(srat, subset = Is_doublet != 'True')

In [ ]:
srat[["meta.data"]]

In [ ]:
Cells(srat)

In [ ]:
srat <- NormalizeData(srat, normalization.method = "LogNormalize", scale.factor = 10000)
srat <- FindVariableFeatures(srat, selection.method = "vst")
srat <- ScaleData(srat, features = rownames(srat))
srat
dim(srat)
dim(srat@meta.data)

In [ ]:
srat[['Doublet_score']][sapply(srat[['Doublet_score']], is.na)] <- 0
srat[['Doublet_score']]

In [ ]:
srat[['Doublet_score']] <- !is.na(srat[['Doublet_score']])

In [ ]:
# srat <- subset(srat, subset = percent.rb >= 0)
srat <- subset(srat, subset = is.na(Is_doublet))
srat

In [ ]:
srat[['Is_doublet']] <- !is.na(srat[['Is_doublet']])

In [ ]:
srat <- subset(srat, subset = Is_doublet != 'True')
srat

In [ ]:
srat@meta.data

In [ ]:
'nCount_RNA' %in% names(srat@meta.data)

In [ ]:
result <- GetMetadataFromSeurat(path)
result

In [ ]:
suffix <- tolower(get_suffix(path))
suffix

In [ ]:
seurat_object <- LoadSeurat(path)
seurat_object

In [ ]:
'umap' %in% names(seurat_object@reductions)

In [ ]:
genes <- rownames(seurat_object)
typeof(genes)
genes

In [ ]:
cells <- Cells(seurat_object)
typeof(cells)
cells

In [ ]:
pca <- Embeddings(object = seurat_object, reduction = "pca")
typeof(pca)
pca

In [ ]:
name <- load(path)
seurat_object <- UpdateSeuratObject(get(name))

In [ ]:
seurat_object

In [ ]:
features <- seurat_object[['RNA']]@var.features
typeof(features)
features

In [ ]:
#获取当前用的Idents
Idents(seurat_object)
levels(seurat_object)

In [ ]:
#总数目
nCells <- ncol(seurat_object)
nGenes <- nrow(seurat_object)

nCells
nGenes